### ISSUE TITLE
发现一些问题

### ISSUE THREAD

**Issue by anglesgirl** [yjqiang/bili2.0#1]
运行一定时间以后

[2018-07-12 16:42:46] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:46] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:46] 风纪委员会共获取0件案例，其中有效投票0件
ffffdjjjdcgcdhtdtdchtrhtcrcrthctrhhctrctrhctrhcrhtctrhcrthchtrhct
智能睡眠 0
hhhhhhhhhhhhhhhh 0 judge
hhhhhhhhhhhhhhhh 1 judge
hhhhhhhhhhhhhhhh 2 judge
本次未获取到案件
[2018-07-12 16:42:46] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:46] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:46] 风纪委员会共获取0件案例，其中有效投票0件
ffffdjjjdcgcdhtdtdchtrhtcrcrthctrhhctrctrhctrhcrhtctrhcrthchtrhct
智能睡眠 0
hhhhhhhhhhhhhhhh 0 judge
hhhhhhhhhhhhhhhh 1 judge
hhhhhhhhhhhhhhhh 2 judge
本次未获取到案件
[2018-07-12 16:42:46] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:46] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:46] 风纪委员会共获取0件案例，其中有效投票0件
ffffdjjjdcgcdhtdtdchtrhtcrcrthctrhhctrctrhctrhcrhtctrhcrthchtrhct
智能睡眠 0
hhhhhhhhhhhhhhhh 0 judge
hhhhhhhhhhhhhhhh 1 judge
hhhhhhhhhhhhhhhh 2 judge
本次未获取到案件
[2018-07-12 16:42:47] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:47] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:47] 风纪委员会共获取0件案例，其中有效投票0件
ffffdjjjdcgcdhtdtdchtrhtcrcrthctrhhctrctrhctrhcrhtctrhcrthchtrhct
智能睡眠 0
hhhhhhhhhhhhhhhh 0 judge
hhhhhhhhhhhhhhhh 1 judge
hhhhhhhhhhhhhhhh 2 judge
本次未获取到案件
[2018-07-12 16:42:47] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:47] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:47] 风纪委员会共获取0件案例，其中有效投票0件
ffffdjjjdcgcdhtdtdchtrhtcrcrthctrhhctrctrhctrhcrhtctrhcrthchtrhct
智能睡眠 0
hhhhhhhhhhhhhhhh 0 judge
hhhhhhhhhhhhhhhh 1 judge
hhhhhhhhhhhhhhhh 2 judge
本次未获取到案件
[2018-07-12 16:42:48] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:48] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:48] 风纪委员会共获取0件案例，其中有效投票0件
ffffdjjjdcgcdhtdtdchtrhtcrcrthctrhhctrctrhctrhcrhtctrhcrthchtrhct
智能睡眠 0
hhhhhhhhhhhhhhhh 0 judge
hhhhhhhhhhhhhhhh 1 judge
hhhhhhhhhhhhhhhh 2 judge
本次未获取到案件
[2018-07-12 16:42:48] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:48] 风纪委员会共获取0件案例，其中有效投票0件
本次未获取到案件
[2018-07-12 16:42:48] 风纪委员会共获取0件案例，其中有效投票0件
ffffdjjjdcgcdhtdtdchtrhtcrcrthctrhhctrctrhctrhcrhtctrhcrthchtrhct
智能睡眠 0

**Comment by anglesgirl** [comment]
会一直重复获取这个玩意

**Comment by yjqiang** [comment]
会关注的，这应该不是最新版吧，task的逻辑最近修改过

**Comment by anglesgirl** [comment]
刚刚已经删除重新下载，持续使用中
        
            
                
                    
                            
                                
                            
                            
                                115235847
                            
                    
                        
                            
                                    邮箱：115235847@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master
在2018年07月12日 17:04，yjqiang 写道： 会关注的，这应该不是最新版吧，task的逻辑最近修改过

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yjqiang/bili2.0","title":"yjqiang/bili2.0","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/yjqiang/bili2.0"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yjqiang in #1: 会关注的，这应该不是最新版吧，task的逻辑最近修改过"}],"action":{"name":"View Issue","url":"https://github.com/yjqiang/bili2.0/issues/1#issuecomment-404443522"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/yjqiang/bili2.0/issues/1#issuecomment-404443522",
"url": "https://github.com/yjqiang/bili2.0/issues/1#issuecomment-404443522",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [yjqiang/bili2.0] 发现一些问题 (#1)",
"sections": [
{
"text": "",
"activityTitle": "**yjqiang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@yjqiang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"yjqiang/bili2.0\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"yjqiang/bili2.0\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/yjqiang/bili2.0/issues/1#issuecomment-404443522"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 355585427\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by anglesgirl** [comment]
邮箱回复，竟然自动把发件人收件人一起引用…
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yjqiang/bili2.0","title":"yjqiang/bili2.0","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/yjqiang/bili2.0"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yjqiang in #1: 会关注的，这应该不是最新版吧，task的逻辑最近修改过"}],"action":{"name":"View Issue","url":"https://github.com/yjqiang/bili2.0/issues/1#issuecomment-404443522"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/yjqiang/bili2.0/issues/1#issuecomment-404443522",
"url": "https://github.com/yjqiang/bili2.0/issues/1#issuecomment-404443522",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [yjqiang/bili2.0] 发现一些问题 (#1)",
"sections": [
{
"text": "",
"activityTitle": "**yjqiang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@yjqiang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"yjqiang/bili2.0\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"yjqiang/bili2.0\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/yjqiang/bili2.0/issues/1#issuecomment-404443522"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 355585427\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by yjqiang** [comment]
fixed
