### ISSUE TITLE
关于控制台查询的建议

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#10]
能否增加单独账户查询？（可根据UID或者其他识别账户的凭证指定查询）。
1.查询参与抽奖结果时，没有识别名，不清楚那个是哪个账户的结果，自己一一对应麻烦。
2.查询黑屋状态时，同上，只有id查看，自己查id要慢慢数第几个个账户进了黑屋。
3.今日任务完成情况上一个结果和下一个结果头尾连在一起，界限分不清楚。（同样没有识别名）
4.最后有个错误，不知道是什么情况，
![qq 20180816072047](https://user-images.githubusercontent.com/42423154/44178569-87435980-a125-11e8-9b1b-3ad1f83a587e.png)
感谢作者。

**Comment by yjqiang** [comment]
单用户在计划中
1.识别名也在做，有的已经支持
2.同上，不过可能稍微改些东西
3.同1
4.https://github.com/yjqiang/bilibili-live-tools/issues/81

**Comment by yjqiang** [comment]
已确定原因，但是处理逻辑仍在考虑
