### ISSUE TITLE
用户使用repo没清理旧文件，导致错误

### ISSUE THREAD

**Issue by 1076472672** [yjqiang/bili2.0#100]
[root@VM_0_6_centos bili2.0]# python3 run.py
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    from danmu import monitor_danmu_raffle
ImportError: cannot import name 'monitor_danmu_raffle'
python版本为3.6.1和3.6.5和3.6.2都试过了，百度也查询了，弄都一天了目前无解
真心求解

**Comment by yjqiang** [comment]
把代码完全删除之后重新下载  什么都不要改  还是报错？

**Comment by 1076472672** [comment]
什么都没改，就是添加了conf的文件，没有改动py。唤灵师centos7.5

**Comment by yjqiang** [comment]
> 什么都没改，就是添加了conf的文件，没有改动py。唤灵师centos7.5

不存在这个错误的……  你是命令行执行还是pycharm之类的？

**Comment by 1076472672** [comment]
xshell执行的，我在华为云试过，可以用，在腾讯云就炸了。我折腾了一天还是不行……

**Comment by yjqiang** [comment]
你ls命令我看看内部文件情况

**Comment by yjqiang** [comment]
我不知道具体原因 但是我windows ios执行都没问题

**Comment by 1076472672** [comment]
明天我再给您看吧，昨天我通宵了，今天太累了。
感谢开发大大的热情回复，我先睡觉了

**Comment by 1076472672** [comment]
ls内部文件？哪一个？

**Comment by yjqiang** [comment]
…… 项目内  ls 命令  就是run.py所在的位置

**Comment by 1076472672** [comment]
明早我再去看，先谢谢了

**Comment by 1076472672** [comment]
[root@VM_0_6_centos bili2.0]# ls
bili_console.py     danmu             monitor_danmu.py             reqs              user_status.py
bili_global.py      danmu.py          monitor_substance_raffle.py  requirements.txt  utils.py
bili_statistics.py  Dockerfile        notifier.py                  run.py            web_session.py
bug                 dyn               printer.py                   substance
conf                exceptions.py     __pycache__                  tasks
conf_loader.py      get-pip.py        raffle_handler.py            user.py
ctrl.sample.toml    json_rsp_ctrl.py  README.md                    user.sample.toml

**Comment by yjqiang** [comment]
> [root@VM_0_6_centos bili2.0]# ls
> bili_console.py     danmu             monitor_danmu.py             reqs              user_status.py
> bili_global.py      danmu.py          monitor_substance_raffle.py  requirements.txt  utils.py
> bili_statistics.py  Dockerfile        notifier.py                  run.py            web_session.py
> bug                 dyn               printer.py                   substance
> conf                exceptions.py     __pycache__                  tasks
> conf_loader.py      get-pip.py        raffle_handler.py            user.py
> ctrl.sample.toml    json_rsp_ctrl.py  README.md                    user.sample.toml
> 

你截图吧

**Comment by 1076472672** [comment]
![QQ截图20190406081710](https://user-images.githubusercontent.com/36905062/55662329-bd645380-5844-11e9-9df5-e80d14234d3a.jpg)

**Comment by yjqiang** [comment]
把这个文件夹全删了，rm会用吧。然后重新用git下载一个全新的文件夹。

**Comment by 1076472672** [comment]
wget行吗，git我不会弄

**Comment by 1076472672** [comment]
感谢开发者，发现问题了，确实是repo没清理旧文件。
谢谢
