### ISSUE TITLE
开启了动态抽奖，变成了这样

### ISSUE THREAD

**Issue by zhz1237ok** [yjqiang/bili2.0#101]
config那边已经设置好了要@的两个人，把动态抽奖开启了，然后运行脚本，变成了这样
![Snipaste_2019-04-06_18-45-44](https://user-images.githubusercontent.com/38283893/55668424-e0baed00-589c-11e9-8b74-909d3ae042f7.png)

同时B站账号发了以下一条动态
![Snipaste_2019-04-06_18-45-52](https://user-images.githubusercontent.com/38283893/55668425-e0baed00-589c-11e9-9d87-40a2f961fedb.png)

请问我的使用姿势哪里错误了

**Comment by zhz1237ok** [comment]
用户生成动态 {'code': 0, 'msg': 'success', 'message': 'success', 'data': {'doc_id': '18930778'}}( 用户id:0 名字:XXXXXXXXXXXXXX)

https://api.vc.bilibili.com/link_draw/v1/doc/delete?doc_id=18930778

**Comment by yjqiang** [comment]
del_dny_by_docid这个api失效了，目前不知道怎么办。。。

**Comment by zhz1237ok** [comment]
> del_dny_by_docid这个api失效了，目前不知道怎么办。。。

那就好，我以为是我的使用姿势出错了

**Comment by yjqiang** [comment]
@zhz1237ok fixed

**Comment by zhz1237ok** [comment]
> @zhz1237ok fixed

用户生成动态 {'code': 110011, 'msg': '需要成为正式会员才能发布图片', 'message': '需要成为正式会员 才能发布图片', 'data': []}(用户id:0 名字:XXXXXXXXXX)

现在变成这样了，cookies无法引用嘛还是什么

**Comment by yjqiang** [comment]
不知道。动态我这里正常，你重启试试看

**Comment by zhz1237ok** [comment]
> 不知道。动态我这里正常，你重启试试看
> 
> > 用户生成动态 {'code': 0, 'msg': 'success', 'message': 'success', 'data': {'doc_id': '18930778'}}( 用户id:0 名字:XXXXXXXXXXXXXX)
> 
> 用户生成动态这里不是对了么？哪里一样？

用户生成动态 {'code': 0, 'msg': 'success', 'message': 'success', 'data': {'doc_id': '18948599'}}( 用户id:0 名字:XXXXXXXXXXXX)

重启了一下这个doc id这样算是对了嘛

**Comment by zhz1237ok** [comment]
所以像以下这样的显示是正常在运作的？

is_dyn_raffle: 18947784 code: 0
18947784 {"a_id":100}
_____________________________________
is_dyn_raffle: 18947785 code: 0
18947785 {"a_id":100}
_____________________________________
is_dyn_raffle: 18947786 code: 0
18947786 {"a_id":100}
_____________________________________
is_dyn_raffle: 18947787 code: 0
18947787 {"a_id":100}
_____________________________________
is_dyn_raffle: 18947788 code: 110001
可能不存在或者到达定点
_____________________________________
is_dyn_raffle: 18947789 code: 0
18947789 {"a_id":100}
_____________________________________
is_dyn_raffle: 18947790 code: 0
18947790 {"a_id":100}
_____________________________________
is_dyn_raffle: 18947791 code: 0
18947791 {"emoji_type":1}
_____________________________________
is_dyn_raffle: 18947792 code: 0
18947792 {"emoji_type":1}
_____________________________________
is_dyn_raffle: 18947793 code: 0
18947793 {"a_id":100}

**Comment by yjqiang** [comment]
> > 不知道。动态我这里正常，你重启试试看
> > > 用户生成动态 {'code': 0, 'msg': 'success', 'message': 'success', 'data': {'doc_id': '18930778'}}( 用户id:0 名字:XXXXXXXXXXXXXX)
> > 
> > 
> > 用户生成动态这里不是对了么？哪里一样？
> 
> 用户生成动态 {'code': 0, 'msg': 'success', 'message': 'success', 'data': {'doc_id': '18948599'}}( 用户id:0 名字:XXXXXXXXXXXX)
> 
> 重启了一下这个doc id这样算是对了嘛

对啊。还有一个删除提示。

**Comment by yjqiang** [comment]
> 所以像以下这样的显示是正常在运作的？
> 
> is_dyn_raffle: 18947784 code: 0
> 18947784 {"a_id":100}
> 
> is_dyn_raffle: 18947785 code: 0
> 18947785 {"a_id":100}
> 
> is_dyn_raffle: 18947786 code: 0
> 18947786 {"a_id":100}
> 
> is_dyn_raffle: 18947787 code: 0
> 18947787 {"a_id":100}
> 
> is_dyn_raffle: 18947788 code: 110001
> 可能不存在或者到达定点
> 
> is_dyn_raffle: 18947789 code: 0
> 18947789 {"a_id":100}
> 
> is_dyn_raffle: 18947790 code: 0
> 18947790 {"a_id":100}
> 
> is_dyn_raffle: 18947791 code: 0
> 18947791 {"emoji_type":1}
> 
> is_dyn_raffle: 18947792 code: 0
> 18947792 {"emoji_type":1}
> 
> is_dyn_raffle: 18947793 code: 0
> 18947793 {"a_id":100}

对

**Comment by zhz1237ok** [comment]
> > 所以像以下这样的显示是正常在运作的？
> > is_dyn_raffle: 18947784 code: 0
> > 18947784 {"a_id":100}
> > is_dyn_raffle: 18947785 code: 0
> > 18947785 {"a_id":100}
> > is_dyn_raffle: 18947786 code: 0
> > 18947786 {"a_id":100}
> > is_dyn_raffle: 18947787 code: 0
> > 18947787 {"a_id":100}
> > is_dyn_raffle: 18947788 code: 110001
> > 可能不存在或者到达定点
> > is_dyn_raffle: 18947789 code: 0
> > 18947789 {"a_id":100}
> > is_dyn_raffle: 18947790 code: 0
> > 18947790 {"a_id":100}
> > is_dyn_raffle: 18947791 code: 0
> > 18947791 {"emoji_type":1}
> > is_dyn_raffle: 18947792 code: 0
> > 18947792 {"emoji_type":1}
> > is_dyn_raffle: 18947793 code: 0
> > 18947793 {"a_id":100}
> 
> 对

动态抽奖不是要转发什么的，这样就行了？转发完自动会删除动态？删除了也算是记录在案了？

**Comment by yjqiang** [comment]
> 动态抽奖不是要转发什么的，这样就行了？转发完自动会删除动态？删除了也算是记录在案了？

这是没有搜索到抽奖动态而已。直到抽奖出来结果才删除。
