### ISSUE TITLE
docker使用时候会提示user.toml为文件夹？

### ISSUE THREAD

**Issue by Muromi-Rikka** [yjqiang/bili2.0#103]
Traceback (most recent call last):
  File "./run.py", line 38, in <module>
    dict_user = conf_loader.read_user()
  File "/app/conf_loader.py", line 89, in read_user
    return var.read_user()
  File "/app/conf_loader.py", line 59, in read_user
    with open(self.file_user, encoding="utf-8") as f:
IsADirectoryError: [Errno 21] Is a directory: '/app/conf/user.toml'

**Comment by yjqiang** [comment]
@zsnmwy 。。。我也不知道啥原因


> Traceback (most recent call last):
> File "./run.py", line 38, in 
> dict_user = conf_loader.read_user()
> File "/app/conf_loader.py", line 89, in read_user
> return var.read_user()
> File "/app/conf_loader.py", line 59, in read_user
> with open(self.file_user, encoding="utf-8") as f:
> IsADirectoryError: [Errno 21] Is a directory: '/app/conf/user.toml'

你自己手动查看conf里面是否有异常文件。

**Comment by zsnmwy** [comment]
1. 更新docker镜像（我刚刚重新构建了下，详见[这里](https://hub.docker.com/r/zsnmwy/bili2.0/builds)）
```
docker pull zsnmwy/bili2.0 #重新拉取就完事了
```

2. 把你需要替换的文件，重新下一次。确保跟主项目是保持同一个版本。不然各种报错。。。

**Comment by zsnmwy** [comment]
> @zsnmwy 。。。我也不知道啥原因
> 
> > Traceback (most recent call last):
> > File "./run.py", line 38, in
> > dict_user = conf_loader.read_user()
> > File "/app/conf_loader.py", line 89, in read_user
> > return var.read_user()
> > File "/app/conf_loader.py", line 59, in read_user
> > with open(self.file_user, encoding="utf-8") as f:
> > IsADirectoryError: [Errno 21] Is a directory: '/app/conf/user.toml'
> 
> 你自己手动查看conf里面是否有异常文件。以及/app/conf/user.toml是正常路径么？

/app/conf/user.toml是正常路径。

因为在dockerfile里面，是直接把项目clone到/app里面的。
```
git clone https://github.com/yjqiang/bili2.0.git /app
```
主要是，每次运行都会跟随着主项目的代码一起更新。`git pull`

但是，用户的配置文件不是跟着更新的。

因为用户的配置文件是从容器外面替换进来的，不是用容器内主项目里面的最新配置文件。

**Comment by yjqiang** [comment]
@Muromi-Rikka 你看看好了么？

**Comment by Muromi-Rikka** [comment]
> @Muromi-Rikka 你看看好了么？
