### ISSUE TITLE
yjmonitor v2更新后的节奏风暴开启方式改变了吗，原来是去除两个注释，现在一共找到三个

### ISSUE THREAD

**Issue by zhz1237ok** [yjqiang/bili2.0#105]
除了保留的https://github.com/yjqiang/bili2.0/blob/master/danmu/monitor_danmu_raffle.py#L79
以外
https://github.com/yjqiang/bili2.0/commit/6ca72c75e2f82a02f976204063eda4cb6f1c0eb1#diff-2b31016d85206ad572c030c4e1c11827R76
https://github.com/yjqiang/bili2.0/commit/6ca72c75e2f82a02f976204063eda4cb6f1c0eb1#diff-2b31016d85206ad572c030c4e1c11827R219
还需要把这两条注释去除才能打开节奏风暴嘛

**Comment by zhz1237ok** [comment]
https://github.com/yjqiang/bili2.0/commit/6ca72c75e2f82a02f976204063eda4cb6f1c0eb1#diff-2b31016d85206ad572c030c4e1c11827R171 默默问一下这又是啥´_＞`

**Comment by yjqiang** [comment]
还需要大改弹幕模块。那个更新是配合yjmonitor的tcp ws推送做的设置。但是还没启用，具体逻辑也要改。

**Comment by yjqiang** [comment]
https://github.com/yjqiang/blivedm
弹幕主体逻辑在这里
