### ISSUE TITLE
api code = 3

### ISSUE THREAD

**Issue by yjqiang** [yjqiang/bili2.0#11]
![image](https://user-images.githubusercontent.com/8900942/44307771-1d53da00-a3db-11e8-8ad7-ac17fa9dfca7.png)

**Comment by yjqiang** [comment]
由于设计原因，无法从web_hub反馈值，暂时无法解决

**Comment by yjqiang** [comment]
这个问题应该可能是cookie token等过期

**Comment by rabbit2rabbit** [comment]
这个问题曾在以下情况后偶尔出现：
1.配置文件中有空白的账号
2.登陆一个新的账号
3.其中一个账号更改密码

现在是用旧的配置文件，一启动就必定api错误

**Comment by yjqiang** [comment]
已经完美解决，逻辑推敲了，应该不会出问题（flag）
