### ISSUE TITLE
环境没问题，运行闪退

### ISSUE THREAD

**Issue by Jutean** [yjqiang/bili2.0#110]
看到大佬更新了一些东西，然后重新下载了，按同样的方法设置运行闪退

**Comment by yjqiang** [comment]
安装decorator模块

**Comment by Jutean** [comment]
大佬，求条指令qaq

**Comment by yjqiang** [comment]
cmd 运行`pip3 install decorator`，不行就百度pip 安装模块。

**Comment by Jutean** [comment]
谢谢了，已经装好

**Comment by Jutean** [comment]
大佬，新版的又需要安装什么库吗？

**Comment by Jutean** [comment]
大佬，“动态抽奖开关在run.py ，需要在/conf/ctrl.toml更新dyn_lottery_friends，参与的抽奖会在dyn里面产生一个database数据库（sqlite3）。注意：在数据库格式更新的commit前运行过动态抽奖的用户请先运行add_colomn_joined2old_staus_table.py升级数据库。”这个新设置该怎么设置

**Comment by yjqiang** [comment]
？按说明啊 你另开issue

**Comment by Jutean** [comment]
说明的都安装了，就两个模块呗

**Comment by yjqiang** [comment]
看不懂你在说什么，requirements里面就是所需模块。
