### ISSUE TITLE
请问勋章

### ISSUE THREAD

**Issue by chy89224** [yjqiang/bili2.0#111]
可以用银瓜子兑换勋章的功能吗

**Comment by yjqiang** [comment]
b站不支持吧 似乎只能金瓜子了吧

**Comment by Jutean** [comment]
可以购买，有个油猴插件支持这样买

**Comment by Jutean** [comment]
https://greasyfork.org/zh-CN/scripts/368635-bilibili%E7%9B%B4%E6%92%AD%E9%97%B4%E5%8A%A9%E6%89%8B
