### ISSUE TITLE
统计错误

### ISSUE THREAD

**Issue by wwh1004** [yjqiang/bili2.0#113]
统计有点问题，有小数

![Snipaste_2019-04-12_22-12-43](https://user-images.githubusercontent.com/27536652/56043602-2a5d7900-5d70-11e9-89c0-2d87497998e6.png)

**Comment by yjqiang** [comment]
> 统计有点问题，有小数
> 
> ![Snipaste_2019-04-12_22-12-43](https://user-images.githubusercontent.com/27536652/56043602-2a5d7900-5d70-11e9-89c0-2d87497998e6.png)
> 

代码对全区推送的统计数目策略为（1/区数），所以当有恰好断开期间，统计可能为小数。不是bug
