### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by 1536297967** [yjqiang/bili2.0#115]
![捕获](https://user-images.githubusercontent.com/49566242/56052964-53d4cf80-5d85-11e9-93d4-a014b1657ea4.PNG)

C:\Users\Administrator>cd C:\Users\Administrator\Desktop\bili2.0-master

C:\Users\Administrator\Desktop\bili2.0-master>python run.py
[2019-04-13 00:40:46] token有效期检查: 仍有效 (用户id:0 名字:省略)
Traceback (most recent call last):
  File "run.py", line 74, in <module>
    printer_danmu = loop.run_until_complete(get_printer_danmu())
  File "C:\python\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "run.py", line 61, in get_printer_danmu
    yjmonitor_danmu_roomid = other_control['yjmonitor_danmu_roomid']
KeyError: 'yjmonitor_danmu_roomid'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000000038EED68>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000000003A25
D68>, 59384.14)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000000038EEE48>

C:\Users\Administrator\Desktop\bili2.0-master>

**Comment by yjqiang** [comment]
更新ctrl.toml，目前与example不匹配
