### ISSUE TITLE
保持指定房间的在线状态

### ISSUE THREAD

**Issue by wwh1004** [yjqiang/bili2.0#116]
能不能添加一个这样的功能，就是模拟用户一直开着一个直播间页面。
如果上船了而且一直打开某个房间的页面，这里的名字会显示为红色（红色的那坨马赛克），我就是想要这个，可以假装自己一直在线O_O。
![Snipaste_2019-04-13_23-14-10](https://user-images.githubusercontent.com/27536652/56081627-ffdbf080-5e41-11e9-9f52-4e9dc7e6a1ed.png)
我抓了一下包，然后拿fiddler测试了一下，抓到的api是
https://api.live.bilibili.com/guard/heart?ruid={主播的uid}
然后headers用pc端的那个，cookie用登录得到的就行
![Snipaste_2019-04-13_23-19-08](https://user-images.githubusercontent.com/27536652/56081692-bcce4d00-5e42-11e9-971b-7ab8654d68f1.png)
我用chrome试了一下，2次间隔是5分钟，意思就是5分钟发送一次应该就可以模拟保持一直在线。
![Snipaste_2019-04-13_23-35-50](https://user-images.githubusercontent.com/27536652/56081922-0cae1380-5e45-11e9-9334-3de9ddbf6e0c.png)
不知道能不能添加一个这样的功能。
目前只是看得懂py，要改起py来还是力不从心，没学过

**Comment by yjqiang** [comment]
这个就是为了好看么……

**Comment by wwh1004** [comment]
嗯....毕竟也算挂机，不会写py就没法自己改了

**Comment by yjqiang** [comment]
加可以加 但是不好处理……因为主播uid这些东西不能一次一获取。而且多用户没法控制。而且万一你有100个上舰房间，你用哪个？

**Comment by wwh1004** [comment]
这个可以同时在线的，测试发现打开了网页就行，不需要管浏览器是否一直保持这个页面在前台，比如我同时打开100个页面也是可以的，100个上船的房间就发100个请求
https://api.live.bilibili.com/live_user/v1/UserInfo/get_info_in_room?roomid={房间ID}
这个api是得到主播uid的
![Snipaste_2019-04-14_09-30-04](https://user-images.githubusercontent.com/27536652/56087169-f1202880-5e97-11e9-8085-1489980ffb20.png)
或者这个api一次获取所有上船信息
![Snipaste_2019-04-14_09-35-05](https://user-images.githubusercontent.com/27536652/56087200-a9e66780-5e98-11e9-9f49-d6e09f1ba9fc.png)
https://api.live.bilibili.com/i/api/guard?page=1&pageSize=1000

pageSize可以填大点，我写的是1000，一次获取全就行

**Comment by wwh1004** [comment]
你有开发群或者讨论群么，能不能拉我进去，群里说方便些

**Comment by yjqiang** [comment]
这东西我个人没什么意愿开发。主要没实际意义，而且5分钟的间隔来说，这个请求是一个很大的流量负载。目前我还在想办法缩减不必要的请求呢。

**Comment by yjqiang** [comment]
如果实现就是手动指认某个用户在哪些房间保持这种心跳。但是指认用户这里我直到现在也没想到设置办法。

**Comment by wwh1004** [comment]
多用户应该要改配置文件格式，我之前打算给我的项目用的配置文件的格式是一个全局配置文件，然后每个用户再弄一个，用户的配置文件可以重写全局配置文件，比如全局的配置是
A=1
B=2
然后用户配置文件是
A=2
那最终用户的配置就是
A=2
B=2
但是感觉用的人可能会搞不明白，开发难度可能也大很多

**Comment by yjqiang** [comment]
这个不是问题。问题是指认是具体哪个用户。

**Comment by wwh1004** [comment]
全局配置里面把在哪些房间保持心跳设置为空，然后在每个用户具体的配置里面设置，比如全局的是
{
GuardHeart:null
}
然后有用户A,B,C,D
想让A保持心跳，那就在用户A的配置里面添
{
GuardHeart:[1,2,3,4,5,6]
}

**Comment by yjqiang** [comment]
我不打算这么做，这样如果某个值可以很多种，那么估计用户使用起来就自闭了。
目前个人打算是全局+自定义。
自定义如下:
```toml
[user_A]
heart_beat = true

[userB]
send_gift = false
```

**Comment by zhz1237ok** [comment]
> 这个就是为了好看么……

![image](https://user-images.githubusercontent.com/38283893/56193797-11044780-6064-11e9-8833-22f6fef840d2.png)

挂机有经验，希望能推出这个功能，等级到30还能开友爱社´_＞`

**Comment by yjqiang** [comment]
> > 这个就是为了好看么……
> 
> ![image](https://user-images.githubusercontent.com/38283893/56193797-11044780-6064-11e9-8833-22f6fef840d2.png)
> 
> 挂机有经验，希望能推出这个功能，等级到30还能开友爱社´_＞`
> 出个配置文件，用户手动填写房间id就好了

这是另一个心跳，已经支持了。
