### ISSUE TITLE
bili2.0下次架构推翻计划

### ISSUE THREAD

**Issue by yjqiang** [yjqiang/bili2.0#117]
待解决的问题：
- [x] 当前task返回值过于复杂，包含间隔、下一步的步骤指定、下一步的执行对象等。
- [x] 需要循环执行的task（例如心跳、风纪委）循环是写在task函数内的，这导致休眠、具体执行过于复杂。

新架构发布计划：
- [x] 设计与模拟
- [x] 验证
- [ ] 正式应用新架构

Calendar：
一两个月左右

**Comment by yjqiang** [comment]
更新：如果使用全局定时器，按时下发任务，那么需要`ensure_future`之前注册，否则可能重复？当然这里还是存疑，因为eventloop是一个poll，再次执行同一个全局时，task应该已经开始执行了。再说，就是重复注册了，那之后判定还是会筛选掉的。

**Comment by yjqiang** [comment]
更新：如果长期task，比如风机委，如何cancel/stop等？

**Comment by AncientFires** [comment]
https://github.com/ckx000/openbilibili/blob/master/app/service/live/xlottery/service/v1/storm.go
大佬看了这份代码吗？

**Comment by yjqiang** [comment]
> https://github.com/ckx000/openbilibili/blob/master/app/service/live/xlottery/service/v1/storm.go
> 大佬看了这份代码吗？

看了  感觉并没有什么帮助  而且似乎封禁具体逻辑之类的感兴趣的地方并没有。

**Comment by yjqiang** [comment]
1. 对于unique task（例如签到、送礼等），user里面加一个dict，为TaskFunction对应的task(`asyncio.ensure_future`)。下个时间点的总体推送来到时，如果task not done，则不执行。待解决的点，如何cancel？

**Comment by anampa** [comment]
大佬这个怎么设置多用户

**Comment by yjqiang** [comment]
@anampa 
1. 请另开issue，不要在issue里面讨论与改主题不一致的话题
1. 请善用github提供的issue搜索功能，https://github.com/yjqiang/bili2.0/issues/49#issuecomment-462133243

**Comment by yjqiang** [comment]
Schedule 设计将借助https://schedule.readthedocs.io/en/stable/ ，两个控制，一个负责整体的休眠/唤醒，一个负责添加固定任务
