### ISSUE TITLE
开启自动投满佩戴勋章当日亲密度后，一天投出辣条超过每日亲密度上限

### ISSUE THREAD

**Issue by 526462712** [yjqiang/bili2.0#118]
开启自动投满佩戴勋章当日亲密度后，一天内在同一个直播间投出了2700多个辣条，所戴勋章每日亲密度限制是1500。是不是如果只想把所戴勋章投满的话，只需要把“自动投满佩戴勋章当日亲密度”改成true，短房间号留空就可以了？
![U89ZLSYVFZC KEK$OC B77L](https://user-images.githubusercontent.com/34618949/56404047-15647680-6297-11e9-8399-3a361e106b88.png)

![@ BTNDH5SAHANNPI)XFBTL5](https://user-images.githubusercontent.com/34618949/56404070-388f2600-6297-11e9-98e0-db57045d89cd.png)

**Comment by yjqiang** [comment]
是的，否则会叠加重复。
