### ISSUE TITLE
关于使用server酱进行每日微信推送的功能

### ISSUE THREAD

**Issue by dirrory** [yjqiang/bili2.0#119]
毕竟是处于长期挂机状态的，不可能说每天都去查询一下当日的状态，是否掉线等等。。能不能基于server酱的功能进行定制微信推送功能呢，比如说每日的领取数量，辣条总量，是否小黑屋，每日任务完成度等等~

**Comment by yjqiang** [comment]
可以使用控制台查看是否完成任务。目前架构比较难以做到推送，我还在继续考虑架构问题。

**Comment by AncientFires** [comment]
吃瓜：
https://github.com/ckx000/openbilibili/blob/master/app/service/live/xlottery/service/v1/storm.go

**Comment by yjqiang** [comment]
#176
