### ISSUE TITLE
动态抽奖无法使用

### ISSUE THREAD

**Issue by ALICEOFALICE** [yjqiang/bili2.0#120]
在更新代码并使用了一段时间后，发现动态抽奖并未激活，重启脚本后发现拉取抽奖信息大多为过期的抽奖信息

![TIM截图20190421170321](https://user-images.githubusercontent.com/41146748/56467899-85b9f600-6457-11e9-92bc-c81d22bb4347.png)
在观察一段时间脚本后，发现一直查找实物抽奖，但未执行且一直回传 #【】
![TIM截图20190421170544](https://user-images.githubusercontent.com/41146748/56467918-c1ed5680-6457-11e9-9113-3b4ed9c80d2f.png)

而且查看账户后发现并没有添加互动抽奖关注组，也没有任何转发抽奖
代码于2019/4/21日更新，直接下载源码并于screen使用
系统环境：Linux izwz92q1gvb6chqemq5bvjz 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
服务器为深圳阿里云

**Comment by yjqiang** [comment]
实物抽奖是直播，动态抽奖为主站转发。请务必区分。

**Comment by ALICEOFALICE** [comment]
原来如此，是我理解错误了，抱歉
