### ISSUE TITLE
多用户情况下如何使用两份不同的ctrl.toml

### ISSUE THREAD

**Issue by zhz1237ok** [yjqiang/bili2.0#122]
如题，如果不同用户想要送辣条给不同房间，是不是还没开发这个功能

**Comment by yjqiang** [comment]
暂时没有支持 主要是没法写配置文件……

**Comment by yjqiang** [comment]
目前是一个ctrl，其实我一直在考虑多用户这种ctrl怎么设置。users单独写着在user.toml里面，而ctrl需要和user挂钩的。怎么指认具体哪个用户对应哪个控制就很麻烦了……

**Comment by zhz1237ok** [comment]
> 目前是一个ctrl，其实我一直在考虑多用户这种ctrl怎么设置。users单独写着在user.toml里面，而ctrl需要和user挂钩的。怎么指认具体哪个用户对应哪个控制就很麻烦了……

[custom_task_control]  # 与global_task_control对应。针对某个具体用户的自定义(如果用户没有自定义的部分，就使用前面global那里的配置)
    [custom_task_control.username]  # sub-table({'custom_task_control': {'user0': {}, 'user1': {}}})，name与user.toml内的相同
    givecoin = 5
    [custom_task_control."xxx.qq.com"]  # 用户名如果包含.这个特殊符号需要使用双引号括起来，这里xx.qq.com就是username
    givecoin = 5



[other_control]  # 其他细节控制

这些更新的具体写法怎么写，比如我有两个账号，给第二个账号一个独特的设置的话像这样写嘛：

[custom_task_control]  # 与global_task_control对应。针对某个具体用户的自定义(如果用户没有自定义的部分，就使用前面global那里的配置)
    [custom_task_control.ABC] 
    # 清理即将过期礼物，请true之后一定要把紧随其后的clean-expiring-gift2room设置为真实房间号
clean-expiring-gift = false
# 单位秒，这是控制定义过期礼物何时为“过期”的阈值
set-expiring-time = 0
# 对过期礼物是否优先投递到其他勋章(按照勋章等级由大到小顺序投递)，之后会剩余的清理掉至clean-expiring-gift2room
clean_expiring_gift2all_medal = false
clean-expiring-gift2room = 0

# 一天最多一个硬币兑换机会
silver2coin = true

# 自动投满佩戴勋章当日亲密度
send2wearing-medal = true
# 短房间号(与投满亲密度send2wearing-medal的一起使用)。注意⚠️如果只需要投佩戴的勋章，不用修改send2medal
send2medal = []

# 输入数字 0-5 表示主站每日自动投币
givecoin = 0
# av获取(bilitop或者uper)分别代表b站随机或者根据up主mid选取
fetchrule = "bilitop"
# up主list([123]或者[123, 234, 123]等)
mid = []

# 抽奖@的人，格式为 uid = "用户名"（例如 {332704117 = "白上吹雪Official", 339567211 = "赤井心Official"}）
# 要求被@的人不能经常改名字，这样也就说明这些用户也可控，即不得随意骚扰他人
dyn_lottery_friends = {}



[other_control]  # 其他细节控制

**Comment by yjqiang** [comment]
不确定你就不要换顺序，按照解释的样子写
