### ISSUE TITLE
ctrl里控制单个账号不动态抽奖

### ISSUE THREAD

**Issue by someash** [yjqiang/bili2.0#125]
我觉得这个功能得run.py和ctrl里面同时打开才生效，双开关，这就控制哪些抽奖，哪些不抽，而不需要开第二个脚本。
(希望大佬有空能加上这个功能)

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/commit/9d7c34cf22e2068b17e2bb1165f0f4cfc07b713e
