### ISSUE TITLE
大航海检测是否过于少了

### ISSUE THREAD

**Issue by yushengleiming** [yjqiang/bili2.0#129]
我看见别人的每日的航海亲密度高达2000+，我们的脚本是不是检测太少了日均都没有过100亲密度

**Comment by yjqiang** [comment]
给他留言了，他应该会看到的

**Comment by pjy612** [comment]
大航海全检索的话需要配合大佬的另一个项目 YjMonitor 监控。
不过 监控 搭建 步骤有点复杂。
功能大概就是用去监控近千的房间。
接收到后 推送给 bili 端。然后 bili 执行领取操作。
