### ISSUE TITLE
把控制台判断小黑屋情况列表 输入9直接导出txt

### ISSUE THREAD

**Issue by Twoleaf** [yjqiang/bili2.0#131]
如题  输入9直接把当前在小黑屋的账号列表导出Blacklist.txt   每次输入9覆盖txt

**Comment by yjqiang** [comment]
可能比较难做，那这样其实还不如弄个server酱之类的吧

**Comment by pjy612** [comment]
=。= 嘛 小黑屋一般是多久啊？还有是不是挂着了最好就别在其他地方操作了？
我弄了个小号去监听和抢，大号只抢。然后 大号进去了。。。
小号还跑的风生水起的囧。。。
另外是不是和节奏风暴的几率也有关系？大号没设置 估计是 100%...

**Comment by yjqiang** [comment]
@pjy612 请不要在他人的不想干话题下讨论新的话题

**Comment by yjqiang** [comment]
#176

**Comment by yjqiang** [comment]
算是一类问题
