### ISSUE TITLE
是不是可以加上log

### ISSUE THREAD

**Issue by pjy612** [yjqiang/bili2.0#137]
就是把 print 封装一下，在打印的基础上一部分直接输出到txt？
这样就可以定时输出收益什么的。万一程序崩了也好有个记录查看？

**Comment by yjqiang** [comment]
log写文件花费时间，不需要。只需要把warn等写入即可

**Comment by yjqiang** [comment]
打印转发为文件这里在linux下可以很方便的改 系统级别的
