### ISSUE TITLE
模拟进入房间

### ISSUE THREAD

**Issue by wwh1004** [yjqiang/bili2.0#139]
不知道是最近更新的还是我以前没注意到，网页版B站直播通过弹幕推送进入的抽奖房间，url有query部分，比如 https://live.bilibili.com/720?live_lottery_type=1&broadcast_type=0&from=28003&extra_jump_from=28003 ，最近我的号进了2次小黑屋，不过很快出来了，就特别留心了一下是不是有什么不对劲的，然后发现了这个

**Comment by yjqiang** [comment]
我觉得没什么大用。。。我一直跑着，快半个月没进了
