### ISSUE TITLE
8月23日新增的修改导致403

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#14]
使用8月23日修改过的版本，会出现403频繁，关闭之后同一时间用回上一个8月20日修改的版本，403频繁没有出现。没截图

**Comment by yjqiang** [comment]
可否查出是具体哪个修改么

**Comment by yjqiang** [comment]
刚刚修改了一些东西，更新一下看看

**Comment by rabbit2rabbit** [comment]
更新了使用5分钟，暂时没有发现403错误。（之前的一开始运行就会立马出现403）

**Comment by yjqiang** [comment]
再更新一下，现在找到了
