### ISSUE TITLE
小黑屋判断有问题

### ISSUE THREAD

**Issue by wwh1004** [yjqiang/bili2.0#140]
有的时候早就进小黑屋了，但是脚本一直没识别出来，这次提示访问拒绝了，但是还是没判断出

![Snipaste_2019-06-05_19-37-33](https://user-images.githubusercontent.com/27536652/58953565-70abe300-87c9-11e9-9ac5-5ec118cf3a92.png)

**Comment by yjqiang** [comment]
en这里我没写。。。哈哈哈哈

**Comment by wwh1004** [comment]
我觉得可以这样判断进小黑屋，比如抽奖了10次，但是一次辣条都没给，脚本很多时候不会显示访问被拒绝之类的文字，只是不停的加入抽奖，但是没返回结果

**Comment by yjqiang** [comment]
> 我觉得可以这样判断进小黑屋，比如抽奖了10次，但是一次辣条都没给，脚本很多时候不会显示访问被拒绝之类的文字，只是不停的加入抽奖，但是没返回结果，而且脚本也没识别为进了小黑屋，经常是手动关脚本

不需要的，识别返回“拒绝”这种关键词，直接判定小黑屋就行

**Comment by wwh1004** [comment]
不是，我最近的抽奖进小黑屋，B站压根不返回拒绝，一点提示都没

**Comment by yjqiang** [comment]
不可能啊。。。不返回小黑屋，你怎么知道进去的？

**Comment by wwh1004** [comment]
作死又开了下脚本

![Snipaste_2019-06-05_20-03-56](https://user-images.githubusercontent.com/27536652/58954969-3d6b5300-87cd-11e9-9d64-2bec065372c8.png)
![Snipaste_2019-06-05_20-04-32](https://user-images.githubusercontent.com/27536652/58954971-3e03e980-87cd-11e9-9e90-93df240d058a.png)
![Snipaste_2019-06-05_20-05-03](https://user-images.githubusercontent.com/27536652/58954968-3d6b5300-87cd-11e9-86e9-4f824651d0a0.png)
不知道脚本到底检测到进了没，反正一直在抽奖...

**Comment by yjqiang** [comment]
你输入`9`看看

**Comment by wwh1004** [comment]
那看来是进了，然后最开始那张图的是咋回事，之前看到提示个访问被拒绝就觉得有点奇怪了，以为脚本判断有问题

**Comment by yjqiang** [comment]
各个 api 的小黑屋提示不一样，有的我就没写，所以可能没检测到而已。
