### ISSUE TITLE
大佬们帮一下蟹蟹

### ISSUE THREAD

**Issue by heatded** [yjqiang/bili2.0#141]
完全没学过代码,所以尽管使用说明已经够简单易懂了
我还是不知道第五条
"Python 和需要模块都装好了直接 cmd 运行 python run.py"
的cmd在哪里......

**Comment by yjqiang** [comment]
https://baike.baidu.com/item/CMD%E5%91%BD%E4%BB%A4

**Comment by heatded** [comment]
> https://baike.baidu.com/item/CMD%E5%91%BD%E4%BB%A4

懂了懂了,蟹蟹大佬
