### ISSUE TITLE
动态抽奖是否被b站自动过滤异常转发行为，导致转发不成功

### ISSUE THREAD

**Issue by ma823478550** [yjqiang/bili2.0#142]
![image](https://user-images.githubusercontent.com/39283232/59393491-bff59480-8d30-11e9-9568-d8c8135f9fb0.png)

![image](https://user-images.githubusercontent.com/39283232/59393537-e4ea0780-8d30-11e9-80db-e2b5da57fc72.png)

最后一次更新动态是在5月29号，那之后每次更新都重新覆盖之前的，包括conf文件夹里的文件都单独修改过，cmd里也没有出现参与动态抽奖的信息，怀疑是被b站自动过滤导致的

![image](https://user-images.githubusercontent.com/39283232/59393621-34c8ce80-8d31-11e9-9da5-a76356e9bbac.png)

**Comment by yjqiang** [comment]
我这里正常，如果你重启之后可以使用，那就是b站可能返回了异常的返回值，导致停止。如果你重启之后仍然不正常，那就是你自己的问题了。。。

**Comment by yjqiang** [comment]
b站不会过滤这里，b站只会过滤开奖这里

**Comment by yjqiang** [comment]
@ma823478550 重启之后正常了么？

**Comment by ma823478550** [comment]
![image](https://user-images.githubusercontent.com/39283232/59417827-ce699d80-8d7c-11e9-99ff-827d7cba2300.png)
还是没有，尝试重新下了一遍还是一样
有出现dyn raffle的东西但是每次就那个24353081后面就没了
