### ISSUE TITLE
是不是设置没对呀，既不领航海也没见过风暴

### ISSUE THREAD

**Issue by darknessice** [yjqiang/bili2.0#144]
![TIM截图20190617174448](https://user-images.githubusercontent.com/33441677/59595111-ba7cbd80-9127-11e9-817f-efa689750815.png)

**Comment by yjqiang** [comment]
大航海以及风暴是只在当前房间内推送，开源版本不包含推送功能。

**Comment by pjy612** [comment]
体验可以试试 #146 
对编程有了解的可以参考
https://github.com/yjqiang/bili2.0/issues/129#issuecomment-498970870
