### ISSUE TITLE
请问舰长遗漏统计覆盖率为0%，哪里可以改成100%

### ISSUE THREAD

**Issue by chy89224** [yjqiang/bili2.0#145]

**Comment by yjqiang** [comment]
。。。没有舰长监控自然就是覆盖率为0了，这怎么可能改为100%？

**Comment by pjy612** [comment]
有python编程基础可以参考大佬 conf 中 的 YjMonitor 协同监控，在另一个项目里面。
或者赞助下大佬，大佬那儿好像也有部署监控。
我这儿没外网的，不然可以共享一个出来试试效果。
