### ISSUE TITLE
分享一个yjmonitor配置以感受大佬的强大

### ISSUE THREAD

**Issue by pjy612** [yjqiang/bili2.0#146]
首先感谢@yjqiang 大佬开源能研究这个东西
在此分享一个监控服务配置 体验效果 为白嫖添砖加瓦 应该能用一段时间
非本人服务器 只分配 1000 用户 仅供学习 请勿滥用
```python
#ctrl.toml 
yjmonitor_tcp_addr = 'tcp://27.159.82.209:8002'
yjmonitor_tcp_key = '>oK-)-l+ac|y1lmH'
```
如果觉得好用 可以在首页打赏@yjqiang 大佬

**Comment by yjqiang** [comment]
@pjy612 我理论上不允许直接这样打广告 毕竟我们自己也有收费监控

**Comment by pjy612** [comment]
囧，嘛没想打广告的说。只是看着这种问题也比较多，算是弄个途径给他们感觉下“完全体”大概是啥样。
以后会注意的_(:з」∠)_
