### ISSUE TITLE
快过期辣条投喂到不同直播间。

### ISSUE THREAD

**Issue by yushengleiming** [yjqiang/bili2.0#148]
现在每天都有非常多的辣条，单一直播间很容易送满，浪费亲密度。所以可以设置多个直播间 送满亲密度了就换下一个直播间吗

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/master/conf/task.sample.toml#L37

**Comment by yushengleiming** [comment]
gift2room可以填写多个直播间吗 用逗号隔开是吗

**Comment by yjqiang** [comment]
> gift2room可以填写多个直播间吗 用逗号隔开是吗

不可以，同时指定多个直播间怎么知道每个投多少。。。

**Comment by yushengleiming** [comment]
可以做成喂满第一个然后再喂第二个吗

**Comment by yjqiang** [comment]
改这个，自动帮你送勋章https://github.com/yjqiang/bili2.0/blob/master/conf/task.sample.toml#L41
