### ISSUE TITLE
房间开通舰长增加当前佩戴勋章亲密

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#15]
今天发现可以在开通舰长的房间里面增加当前佩戴勋章亲密度+1.
随意抓包，看看能否增加进助手里面。
![1](https://user-images.githubusercontent.com/42423154/44701192-22daaf80-aac0-11e8-8304-50d5e7d7f10f.png)
![2](https://user-images.githubusercontent.com/42423154/44701194-22daaf80-aac0-11e8-8512-0c224cc314c1.png)

**Comment by yjqiang** [comment]
单用户已经加入，目前问题是不广播，比较难处理

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bilibili-live-tools/issues/88

**Comment by yjqiang** [comment]
最新版加入了支持，请测试

**Comment by rabbit2rabbit** [comment]
能否实现查询近期开通的舰长，再进行抽奖，或许会有些帐号遗漏，或者是因情况关闭脚本，重新开启的时候可以再次参与期间没有抽到的舰长

**Comment by yjqiang** [comment]
这个没有api的

**Comment by yjqiang** [comment]
应该不会有bug了

**Comment by rabbit2rabbit** [comment]
发现舰长提督没有参与到，看了代码在你的舰长和提督测试beta中，bilibili.py中的def get_gift_中，post的数据与我抓的数据包少了一个csrf_token,是不是这个原因呢?
![default](https://user-images.githubusercontent.com/42423154/45185543-14795a00-b25d-11e8-91b4-3e89cdf570cb.png)

**Comment by yjqiang** [comment]
舰长只有当前房间有
