### ISSUE TITLE
请问验证服务器拒绝除了等还能咋办

### ISSUE THREAD

**Issue by lixuqi** [yjqiang/bili2.0#154]
是不是能用cookie登录？
还有切换验证码输入方式具体怎么操作。。
原谅我有点小白

**Comment by yjqiang** [comment]
可以自己弄cookie token这些  就写在user.toml里面  或者换ip

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/master/tasks/login.py#L78 改成LoginReq.input_captcha(binary_rsp)
