### ISSUE TITLE
验证服务器挂了

### ISSUE THREAD

**Issue by ghosx** [yjqiang/bili2.0#156]
验证服务器挂了

**Comment by yjqiang** [comment]
https://github.com/Dawnnnnnn
没办法，这货没修。

**Comment by ghosx** [comment]
有没有其他办法

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/154

**Comment by ghosx** [comment]
https://github.com/Dawnnnnnn/bilibili-captcha 自己搭建验证服务器 然后就好了
