### ISSUE TITLE
大佬，有办法查看自己的实物礼物的情况吗

### ISSUE THREAD

**Issue by someash** [yjqiang/bili2.0#159]
就是一个小号中了实物但是忘记领了，要是能判断没有填地址然后自动提醒就好了，或者输入哪个数字代码可以查看实物奖品的情况吗？

**Comment by pjy612** [comment]
用sqlite去查substance下的db。可以看到是否有中奖。

**Comment by yjqiang** [comment]
#176 算是一类问题
