### ISSUE TITLE
批量监控弹幕

### ISSUE THREAD

**Issue by yjqiang** [yjqiang/bili2.0#16]
如舰长、风暴等，python ios仅能425左右房间

**Comment by yjqiang** [comment]
基本完成，不对外公开

**Comment by rabbit2rabbit** [comment]
能否本地多开做到监控1w以上房间？感觉机器性能过剩（得益于脚本优化不错）。
又或者单独把监控脚本放到一个专门的服务端，在2.0里面连接（我可以资助），就可以多监控房间了。
ps.接受捐赠吗？

**Comment by yjqiang** [comment]
本地测试过，可能最高500房间左右，之后会开源出来python的

**Comment by yjqiang** [comment]
> 能否本地多开做到监控1w以上房间？感觉机器性能过剩（得益于脚本优化不错）。
> 又或者单独把监控脚本放到一个专门的服务端，在2.0里面连接（我可以资助），就可以多监控房间了。
> ps.接受捐赠吗？

https://github.com/yjqiang/YjMonitor
