### ISSUE TITLE
动态抽奖 id 穷举扫描优化

### ISSUE THREAD

**Issue by pjy612** [yjqiang/bili2.0#163]
目前 是 如果有doc_id 为了判断是否封顶，在发现code 为 110001 后会 +10 去范围尝试，如果code 都是 110001，就认为是没有了。如果有任意有效的就以那个doc_id继续loop。

这样会有个问题，如果刚好有连续10+的人发了动态后又删除了。这样 就会卡住。
然后 观察了一下 如果是用户发布过的动态 就算 code为110001。
也会包含 data.item 和 data.user ，但是未使用过的 没有 data.item 和 data.user 。
这里是不是可以考虑加一下。 如果 有 data.item 和 data.user  就跳过就好了。
没有 data.item 和 data.user 才认为是 404。再走 +10 检索的逻辑。

**Comment by pjy612** [comment]
因为发现连续几天都是一个id重复。就查了一下，发现也不是json解析问题。就研究了下。
emmm 现在看了下和距离最新的间隔了100w+囧。慢慢往上查询中。。。

**Comment by yjqiang** [comment]
居然还真有10个人连续删除……

**Comment by pjy612** [comment]
_(:з」∠)_嘛 如果刚好有十几个人都用你这个一起挂的话 或者其他挂机的批量转发然后删除。。。
所以 没直接粗暴的把 +10 换成+100 ... 23333

**Comment by yjqiang** [comment]
> 然后 观察了一下 如果是用户发布过的动态 就算 code为110001。
> 也会包含 data.item 和 data.user ，但是未使用过的 没有 data.item 和 data.user 。
> 这里是不是可以考虑加一下。 如果 有 data.item 和 data.user 就跳过就好了。
> 没有 data.item 和 data.user 才认为是 404。再走 +10 检索的逻辑。

确定么，确定的话其实你可以自己改嘛，pr就可以了

**Comment by yjqiang** [comment]
https://api.vc.bilibili.com/link_draw/v1/doc/detail?doc_id=2131220
https://api.vc.bilibili.com/link_draw/v1/doc/detail?doc_id=91312230

**Comment by pjy612** [comment]
我那个自用分支改动太多了。。。
https://github.com/pjy612/bili2.0/tree/local
加了代理什么的，风暴逻辑也改了一下。
不过这个应该可以抽出来 单独 pr
我单独抽出来看看

**Comment by yjqiang** [comment]
> 我那个自用分支改动太多了。。。
> https://github.com/pjy612/bili2.0/tree/local
> 加了代理什么的，风暴逻辑也改了一下。
> 不过这个应该可以抽出来 单独 pr
> 我单独抽出来看看

风暴这里自用即可，不要把具体代码公布出来

**Comment by pjy612** [comment]
> 
> 风暴这里自用即可，不要把具体代码公布出来
已删回复...稍后 pr

**Comment by pjy612** [comment]
下次还是 提供解决方案 让大佬上吧。。。好想死。。。
