### ISSUE TITLE
老爷用户的直播经验有时不加

### ISSUE THREAD

**Issue by xiaozouwwwwww** [yjqiang/bili2.0#166]
好像随机的 重启脚本又有可能加经验了

**Comment by yjqiang** [comment]
我觉得挺奇怪的，心跳这里直出json_rsp，应该不存在异常格式无法识别的

**Comment by xiaozouwwwwww** [comment]
我也觉得情况，会不会有可能压根就没执行呢

**Comment by yjqiang** [comment]
我目前还是正确无误加经验的

**Comment by yjqiang** [comment]
感觉没啥问题。。。反正我一直正常，如果还不正常的话，只可能是控制逻辑问题，影响了心跳功能
