### ISSUE TITLE
用户无法登陆，提示 Cannot connect to host 115.159.205.242:19951

### ISSUE THREAD

**Issue by 526462712** [yjqiang/bili2.0#168]
最近几天发现脚本任务没在做，于是今天更新了脚本，用户信息重新填写了，运行报错如下
![TH MVY(YM)E@8M2QU`DL937](https://user-images.githubusercontent.com/34618949/61357333-a0f79e80-a8aa-11e9-9c1a-9d49da075c2e.png)
![_~RP }TD}(@ DC~SU`NW8T](https://user-images.githubusercontent.com/34618949/61357341-a523bc00-a8aa-11e9-91ea-67a8a50e809c.png)

**最后确认**
- [x] 我仔细看了requirements.txt，确认里面的模块我都安装并及时更新了
- [ ] 我代码上次更新时间距今没有超过 2 个月以上
- [ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/156
