### ISSUE TITLE
不能自动解除小黑屋状态

### ISSUE THREAD

**Issue by NPBeta** [yjqiang/bili2.0#17]
如果在脚本运行过程中某一用户小黑屋状态解除，不能自动更新小黑屋状态，也不会抽奖，必须重开脚本
但其实在心跳过程中，已经不会有检测为小黑屋提示
怀疑是忘写了（逃

**Comment by yjqiang** [comment]
下次加入

**Comment by NPBeta** [comment]
感谢!

**Comment by yjqiang** [comment]
心跳模块弄一块去了，似乎有个心跳礼包多东西，这个会返回400小黑屋提示
