### ISSUE TITLE
大航海和PK和节奏风暴监控key购买地址

### ISSUE THREAD

**Issue by D3ee** [yjqiang/bili2.0#171]
[http:///www.maods.cn/?cid=3&tid=8](http:///www.maods.cn/?cid=3&tid=8)  大航海、pk、节奏风暴监控key购买地址

**Comment by lovezm** [comment]
买了  但是不知道tcp地址 -，-

**Comment by D3ee** [comment]
> 买了但是不知道tcp地址 - ， -
yjmonitor_tcp_addr = 'tcp://room.lc4t.cn:8002'

**Comment by kazehayaccc** [comment]
好像有问题，买不了key，显示签名校验失败

**Comment by D3ee** [comment]
> 好像有问题，买不了键，显示签名验证失败

联系QQ23337673或1050420416

**Comment by DarrenIce** [comment]
key的购买地址失效了吗，页面无法打开了

**Comment by D3ee** [comment]
> key的购买地址无效了吗，页面无法打开了

已经恢复了

**Comment by ShmilyChen** [comment]
这个会推送raffle吗
