### ISSUE TITLE
Bili Live for Python 3.7.4(amd64) not load

### ISSUE THREAD

**Issue by 8MiYile** [yjqiang/bili2.0#174]
Requirements has installed
But i try "python run.py"

> D:\bili2.0-master>python run.py
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    from bili_console import BiliConsole
  File "D:\bili2.0-master\bili_console.py", line 9, in <module>
    from .utils import UtilsTask
ImportError: attempted relative import with no known parent package

- [X] Python-3.7.4安装完毕后立马执行自动配置requirements.txt，确认里面的模块我都安装并及时更新了
- [X] 我代码上次更新时间距今没有超过 1 周以上
- [X] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

Error Log Photo
![S%Y{{CMPRB}{9OZT2IVQ2SV](https://user-images.githubusercontent.com/25455400/64343598-647d2f00-d01f-11e9-9a61-7926ae665872.png)

**Comment by rabbit2rabbit** [comment]
![image](https://user-images.githubusercontent.com/42423154/64916475-4bf3de00-d7b0-11e9-9223-1a5319515a54.png)
和反馈的line6不同

**Comment by 8MiYile** [comment]
知道怎么回事了，这个是直接下载zip导致出现的bug，已靠Git解决
