### ISSUE TITLE
建议添加cnn服务器地址到配置文件

### ISSUE THREAD

**Issue by Fader10** [yjqiang/bili2.0#178]
翻了下issues，发现很多人都出现了无法连接验证码服务器的问题，而验证服务器又是开源的，我觉得可以将验证服务器的地址写在配置文件里面，而不是直接写在代码里面
毕竟每次改完reqs/login.py以后要pull更新的话又要重新改，对于自建cnn服务器的人来说很麻烦
望大佬采纳

**Comment by yjqiang** [comment]
控制文件是toml，导入不到tasks的类里面去，我考虑看看有没有骚办法

**Comment by pjy612** [comment]
Utils 全局变量？

**Comment by yjqiang** [comment]
> Utils 全局变量？

我就是这么想的 就怕被揍

**Comment by yjqiang** [comment]
cnn 估计都快没用了，我考虑了一下，没啥必要灵活起来，写死吧
