### ISSUE TITLE
请教这是什么问题，运行不了

### ISSUE THREAD

**Issue by meanie520** [yjqiang/bili2.0#179]
![Screenshot_20190927-112119](https://user-images.githubusercontent.com/55865737/65740002-dfff6700-e119-11e9-8b1c-e417a705adca.jpg)
一点都看不懂。

**Comment by yjqiang** [comment]
toml模块或者你的toml文件填写错了。我倾向于后者，你写错了toml格式

**Comment by meanie520** [comment]
可是我10分钟还在用的，关闭之后重新打开就这样了，我又重新安装过模块还是一样

**Comment by meanie520** [comment]
> toml模块或者你的toml文件填写错了。我倾向于后者，你写错了toml格式

请问有什么方法解决吗？我现在在尝试重新python和模块，东西我都没修改啥，就是关了cmd之后重新开就这样了。

**Comment by meanie520** [comment]
> toml模块或者你的toml文件填写错了。我倾向于后者，你写错了toml格式
感谢您的解答，重新安装py之后好了。看来py出问题了
