### ISSUE TITLE
没有上船奖励领取？

### ISSUE THREAD

**Issue by MHcute** [yjqiang/bili2.0#182]
没有找到配置的地方
测试之后发现不会自动领取上船奖励

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/181

**Comment by MHcute** [comment]
> #181

感谢回复
我的配置文件是这样的：
join_dyn_raffle = -1  # 动态 dyn_raffle_handler.py
join_guard_raffle = -1  # 舰队 guard_raffle_handler.py
join_storm_raffle = 0  # 风暴 storm_raffle_handler.py
join_substance_raffle = -1  # 实物 substance_raffle_handler.py
join_tv_raffle = -1  # 小电视 tv_raffle_handler.py
join_pk_raffle = -1  # PK pk_raffle_handler.py

heartbeat = -1  # 直播心跳 live_daily_job.py
recv_heart_gift = -1  # 心跳礼物 live_daily_job.py
open_silver_box = -1  # 直播宝箱 live_daily_job.py
recv_daily_bag = -1  # 每日礼包 live_daily_job.py
sign = -1  # 直播签到  live_daily_job.py
watch_tv = -1  # 双端观看任务 live_daily_job.py
sign_fans_group = -1  # 应援团签到 live_daily_job.py
send_gift = -1  # 勋章赠送礼物、赠送即将过期的礼物 live_daily_job.py
exchange_silver_coin = -1  # 每日瓜子硬币兑换 live_daily_job.py

judge_case = -1  # 风纪委 main_daily_job.py
bili_main = -1  # 主站每日任务，投币、分享、观看、登录 main_daily_job.py



[custom_task_arrangement]  # 与global_task_arrangement对应。针对某个具体用户的自定义(如果用户没有自定义的部分，就使用前面global那里的配置)
    [custom_task_arrangement.username]  # sub-table({'custom_task_arrangement': {'user0': {}, 'user1': {}}})，name与user.toml内的相同
    join_storm_raffle = -1
    probability_join_storm_raffle = 0.7

舰队开了-1  也没有probability限制几率。

**Comment by MHcute** [comment]
其他都没有改动过，我就在最下面开了
send2wearing-medal = true
这个选项

是还需要设置哪里吗？

**Comment by yjqiang** [comment]
舰队大部分不公开推送的，个人基本没法弄。你可能需要按照上面链接那样购买我们的统一监控

**Comment by MHcute** [comment]
> 舰队大部分不公开推送的，个人基本没法弄。你可能需要按照上面链接那样购买我们的统一监控

看到了原来在#171里
