### ISSUE TITLE
节奏风暴的抽奖频率和中奖几率问题

### ISSUE THREAD

**Issue by shadow7755** [yjqiang/bili2.0#186]
我买了监控key，返现抽节奏风暴时，只显示2行抽奖信息，都显示未抽中。
而且感觉中奖几率好低，差不多5-6次才中一次。
请问节奏风暴默认是只抽2次吗？默认设置的抽奖频率和时间间隔是多少？能修改吗？

**Comment by yjqiang** [comment]
可以自己调 代码在 tasks/storm.py 里面
