### ISSUE TITLE
动态抽奖问题(lottery 判定)

### ISSUE THREAD

**Issue by 2604237845** [yjqiang/bili2.0#187]
现在动态抽奖功能一直显示正在查找需要参与的和结束的，但是我看到其实有很多动态抽奖，实际一直没有转发过动态抽奖，是不是已经失效了？
![1](https://user-images.githubusercontent.com/54972064/66711302-cc136080-edbb-11e9-9aff-e74c297c5492.png)

**Comment by yjqiang** [comment]
如果设置了不马上参与，只有在该抽奖即将结束的时候餐与。正常。
倒是动态抽奖应该一路暴力循环的……这个好像没有

**Comment by 2604237845** [comment]
> 如果设置了不立即参与，只有在该该抽奖即将结束的时候餐餐与。正常。
> 倒是动态抽奖应该一路暴力循环的……这个好像没有

我设置的是暴力搜索到就立刻参与，但是除了第一次运行在搜索之外，之后就没有见过在搜索了一直都是这样...有办法解决吗
# 动态抽奖开关
dyn_raffle = true
# 立刻参与的话，暴力搜索到就参与；否则就等到快开始抽奖了，才会参与
join_dyn_raffle_at_once = true

**Comment by yjqiang** [comment]
你查看一下最后的刷新显示的dynamic id；问题应该是刷新这里的

**Comment by 2604237845** [comment]
> 你查看一下最后的刷新显示的dynamic id；问题应该是刷新这里的

是在monitor_dyn_raffle.py这个文件里看吗

**Comment by yjqiang** [comment]
打开初始化就开始循环搜索dynamic id了

**Comment by 2604237845** [comment]
懂了，我刚刚将dyn文件夹里的data.db这个可能是搜索出来的数据库删除了，重新打开重新后目前正在暴力循环搜索，不知道会不会像第一次一样突然停止，如果停止了我在看最后一个dynamic id是啥，在回复哈

**Comment by 2604237845** [comment]
> 输出打印这里在打开初始化就开始循环搜索dynamic id了

懂了，我刚刚将dyn文件夹里的data.db这个可能是搜索出来的数据库删除了，重新打开重新后目前正在暴力循环搜索，不知道会不会像第一次一样突然停止，如果停止了我在看最后一个dynamic id是啥，在回复哈

**Comment by 2604237845** [comment]
> 输出打印这里在打开初始化就开始循环搜索dynamic id了

到这里就不在循环搜索了，就变成一开始那样凉...
![1](https://user-images.githubusercontent.com/54972064/66726384-a47bd100-ee6b-11e9-92b0-31053015ff85.png)
![2](https://user-images.githubusercontent.com/54972064/66726385-a47bd100-ee6b-11e9-890b-747351fe26a0.png)

**Comment by pjy612** [comment]
囧 麻蛋 还能有 没 titile 的 然后崩了也不知道。。。才发现。。。得
现在 39xxx 出错的时候 36xxx 300w 个id 漏了。。。

**Comment by 2604237845** [comment]
> 囧 麻蛋 还能有 没 titile 的 然后崩了也不知道。。。才发现。。。得
> 现在 39xxx 出错的时候 36xxx 300w 个id 漏了。。。

是我的问题吗...

**Comment by pjy612** [comment]
> > 囧 麻蛋 还能有 没 titile 的 然后崩了也不知道。。。才发现。。。得
> > 现在 39xxx 出错的时候 36xxx 300w 个id 漏了。。。
> 
> 是我的问题吗...

不是 我这也有问题 要改代码修复了

**Comment by 2604237845** [comment]
哦哦好的，目前就是停止之后就不在启动了，删掉dyn里的data才可以启动，但是一段时间后又停止了




------------------ 原始邮件 ------------------
发件人: "pjy612"<notifications@github.com>;
发送时间: 2019年10月14日(星期一) 下午4:50
收件人: "yjqiang/bili2.0"<bili2.0@noreply.github.com>;
抄送: "凉游浅笔深画眉💤"<2604237845@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yjqiang/bili2.0] 动态抽奖问题 (#187)



  
囧 麻蛋 还能有 没 titile 的 然后崩了也不知道。。。才发现。。。得
 现在 39xxx 出错的时候 36xxx 300w 个id 漏了。。。
  
是我的问题吗...
  
不是 我这也有问题 要改代码修复了

**Comment by 2604237845** [comment]
> > > 囧 麻蛋 还能有 没 titile 的 然后崩了也不知道。。。才发现。。。得
> > > 现在 39xxx 出错的时候 36xxx 300w 个id 漏了。。。
> > 
> > 
> > 是我的问题吗...
> 
> 不是 我这也有问题 要改代码修复了

哦哦好的，目前就是停止之后就不在启动了，删掉dyn里的data才可以启动，但是一段时间后又停止了

**Comment by scott90578** [comment]
![image](https://user-images.githubusercontent.com/24499006/66765485-931fdc80-eede-11e9-862a-b1e96668cbb9.png)
最后的刷新显示的dynamic id  ：36109204 ，重新运行后也会卡在这里

**Comment by yjqiang** [comment]
@pjy612 title 整个字段是不是删了，反正我看了俩，都没有

**Comment by pjy612** [comment]
> @pjy612 title 整个字段是不是删了，反正我看了俩，都没有

应该不是的，我刚刚动态找了个近期有互动抽奖的，里面有titile，如果没有titile的貌似是垃圾数据。
https://api.vc.bilibili.com/link_draw/v1/doc/detail?doc_id=38771371

**Comment by pjy612** [comment]
> > @pjy612 title 整个字段是不是删了，反正我看了俩，都没有
> 
> 应该不是的，我刚刚动态找了个近期有互动抽奖的，里面有titile，如果没有titile的貌似是垃圾数据。
> https://api.vc.bilibili.com/link_draw/v1/doc/detail?doc_id=38771371

不对。。。没有 title 的 好像也有抽奖 囧....这蛋疼了...

**Comment by 2604237845** [comment]
> > > @pjy612 title 整个字段是不是删了，反正我看了俩，都没有
> > 
> > 
> > 应该不是的，我刚刚动态找了个近期有互动抽奖的，里面有titile，如果没有titile的貌似是垃圾数据。
> > https://api.vc.bilibili.com/link_draw/v1/doc/detail?doc_id=38771371
> 
> 不对。。。没有 title 的 好像也有抽奖 囧....这蛋疼了...

大佬....我这都39XXX了，怎么给他弄回36XXXX....难受了

**Comment by pjy612** [comment]
> > > > @pjy612 title 整个字段是不是删了，反正我看了俩，都没有
> > > 
> > > 
> > > 应该不是的，我刚刚动态找了个近期有互动抽奖的，里面有titile，如果没有titile的貌似是垃圾数据。
> > > https://api.vc.bilibili.com/link_draw/v1/doc/detail?doc_id=38771371
> > 
> > 
> > 不对。。。没有 title 的 好像也有抽奖 囧....这蛋疼了...
> 
> 大佬....我这都39XXX了，怎么给他弄回36XXXX....难受了

那个 sqlite db 里面改 小一点 再启动。
ps：300w的id 也要跑好久 重新来比较快 反正我没中过 23333

**Comment by yjqiang** [comment]
@pjy612 感觉可能删了这个字段了。。。我跑一下测试看看

**Comment by yjqiang** [comment]
[2019-10-15 12:46:46] lott_cfg={'lottery_id': 36050}|||doc_id=36109204
[2019-10-15 13:33:10] lott_cfg={'callbackId': 10, 'lottery_id': 36052, 'lottery_time': 1569154200, 'title': '互动抽奖'}|||doc_id=36114455

**Comment by pjy612** [comment]
> [2019-10-15 12:46:46] lott_cfg={'lottery_id': 36050}|||doc_id=36109204
> [2019-10-15 13:33:10] lott_cfg={'callbackId': 10, 'lottery_id': 36052, 'lottery_time': 1569154200, 'title': '互动抽奖'}|||doc_id=36114455

我感觉改成 有 lottery_id 就放行。然后又后面的接口去判断 code 来确认是否是抽奖。
我目前这么改的。。。
