### ISSUE TITLE
新弹幕抽奖类型（**座流星雨抽奖）

### ISSUE THREAD

**Issue by mzth** [yjqiang/bili2.0#189]
星座流星雨

**Comment by yjqiang** [comment]
?什么样的格式

**Comment by mzth** [comment]
用其他抽奖软件检测到的
房间 649091 开启了第 449797 轮天秤座流星雨抽奖

**Comment by yjqiang** [comment]
没看到这个东西 可能测试吧

**Comment by 2604237845** [comment]
这个不好搞吧...生日的话那就有其他星座了还要特定生日才可以，不好抓取

**Comment by mzth** [comment]
![Uploading Inked流星雨_LI.jpg…]()
就是红圈这个礼物

**Comment by mzth** [comment]
![Inked流星雨_LI](https://user-images.githubusercontent.com/53244094/67071704-d23b7f80-f1b5-11e9-8593-912739580e16.jpg)
就红圈这个礼物，房间号9906982

**Comment by yjqiang** [comment]
找了一晚上，没监控到，欢迎帮助搜索

**Comment by pjy612** [comment]
有记录到吧？我刚抓了下好像有。。。
![image](https://user-images.githubusercontent.com/4072526/67481770-1b4b7200-f695-11e9-9946-314f43a3721c.png)

**Comment by pjy612** [comment]
```
全区广播：<%叫我阿Kay%>送给<%肥宅快乐-瓷%>1个天蝎座流星雨，点击前往TA的直播间去抽奖吧~
```

**Comment by pjy612** [comment]
我屮艸芔茻...多谢 yj大佬 竟然弄到了 小电视？！？！？！ 才发现！

**Comment by zdthn00** [comment]
监控到了 但没参与

**Comment by yjqiang** [comment]
确认收到 @pjy612 close

**Comment by yjqiang** [comment]
> 监控到了 但没参与

api应该还是tv的，注意的是，参与中的记录一律是小电视，所以可能参与了只不过你没对应上。

**Comment by zdthn00** [comment]
![mmexport1571932000906](https://user-images.githubusercontent.com/53288770/67506684-1a7c0580-f6c0-11e9-9f97-fa3a4404f3e7.jpg)

**Comment by yjqiang** [comment]
这个抽奖有问题 b站的 之前有人发现刷新不会提醒 很诡异 但是又是tv的

**Comment by pjy612** [comment]
另外就是 返回值是不是不一样 导致哪里异常了？目前没抓取到返回值。
还有可能是不是 现在用的查电视的接口 查不到这种流星雨？还是要登录后才能查到。
就要一一排除了。。。囧

**Comment by zdthn00** [comment]
@yjqiang  刚看了下星座能参与了
