### ISSUE TITLE
关于辣条绕黑屋功能

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#19]
我在别的绕黑屋软件抓了数据包，看到了POST的频率和目标URL，这个方法应该可行，看能否增加进助手里面，检测到小黑屋的时候开启这个功能。
![qq 20180902111655](https://user-images.githubusercontent.com/42423154/44951841-05cc2500-aea2-11e8-8a26-238a411f48a4.png)

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bilibili-live-tools/issues/70
有时间我尝试一下

**Comment by rabbit2rabbit** [comment]
这是过了最高的极限频率没有？需要我把抓包的完整数据发给你？从检测到抽奖开始到抽奖结束。也不一定要百分之百每次都能绕过，能做到保底是最好的，不能的话只能退而求其次了。今天凌晨我就把数据包打包传上来吧。

**Comment by yjqiang** [comment]
不用 原理就是无脑就是暴力请求

**Comment by rabbit2rabbit** [comment]
此方法已经被和谐，使用过的都会封

**Comment by yjqiang** [comment]
。。。。这 gg
