### ISSUE TITLE
节奏风暴设置及控制台正确使用命令

### ISSUE THREAD

**Issue by 2604237845** [yjqiang/bili2.0#190]
[custom_task_arrangement]  # 与global_task_arrangement对应。针对某个具体用户的自定义(如果用户没有自定义的部分，就使用前面global那里的配置)
    [custom_task_arrangement.username]  # sub-table({'custom_task_arrangement': {'user0': {}, 'user1': {}}})，name与user.toml内的相同
    join_storm_raffle = -1
    probability_join_storm_raffle = 0.7
已经购买监控KEY之后这里的0.7需要改成100还是1才能百分百概率参与节奏风暴
另外就是用银瓜子或银币购买勋章的正确使用命令是什么，是否需要先切换监听房间到需要购买勋章的房间......小白研究半天没弄明白

**Comment by 2604237845** [comment]
小白还望大佬不要见怪...

**Comment by yjqiang** [comment]
0.7就是70%了

**Comment by yjqiang** [comment]
不需要切换房间

**Comment by 2604237845** [comment]
命令是23 -u 0 房间号  这样吗

**Comment by 2604237845** [comment]
> 购买勋章不需要切换房间

大佬命令是23 -u 0 房间号 这样吗。。

**Comment by yjqiang** [comment]
23 -p 房间号 -c silver

**Comment by 2604237845** [comment]
好的，非常感谢大佬
