### ISSUE TITLE
反馈大乱斗及大航海两个小问题

### ISSUE THREAD

**Issue by 2604237845** [yjqiang/bili2.0#191]
第一个是大航海领取亲密度返回的信息变成了辣条X1，而不是亲密度X1
第二个是用户进入黑名单后PK大乱斗仍然会进行领取
下面是显示截图大佬看一下~

![1](https://user-images.githubusercontent.com/54972064/67175447-afe57400-f3f8-11e9-8066-7acabaf52e84.png)
![2](https://user-images.githubusercontent.com/54972064/67175448-b07e0a80-f3f8-11e9-9ffb-d1186b263c01.png)

**Comment by 2604237845** [comment]
不知道大航海显示领取变成了辣条是不是挂的号多了...

**Comment by yjqiang** [comment]
大乱斗这里我没写处理小黑屋的逻辑；大航海你没有佩戴勋章就会只领辣条
