### ISSUE TITLE
这里mac环境，python3.8版本，运行失败

### ISSUE THREAD

**Issue by Lambda982** [yjqiang/bili2.0#192]
**再确认一次 issue 题目**
这里mac环境，python3.8版本，运行失败

**问题描述**
![image](https://user-images.githubusercontent.com/16385325/67177855-ede79580-f402-11e9-87b4-ff215c7e5c92.png)

今天在mac上搭的新环境，但是无法运行，账号信息都如实填写。
但是运行就如图无法正常运行

**最后确认**
- [☑️] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [☑️ ] 我代码上次更新时间距今没有超过 2 个月以上
- [ ☑️] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [☑️ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
ssl错误 可能python问题或者你把aiohttp的ssl验证关了试试
