### ISSUE TITLE
使用银瓜子兑换勋章功能无法兑换

### ISSUE THREAD

**Issue by 2604237845** [yjqiang/bili2.0#193]
![QQ截图20191022151453](https://user-images.githubusercontent.com/54972064/67265207-c4506c00-f4df-11e9-92b3-38a3a69899c0.png)
提示请升级到最新版本
用的命令是23 -p 14896661 -c silver
大佬请问是不是失效了......

**Comment by yjqiang** [comment]
可能就是失效了吧  毕竟老接口了

**Comment by 2604237845** [comment]
> 可能就是无效了吧毕竟老接口了

我昨天试了一下油猴的那个插件，发现还可以用硬币兑换，这个可以把接口替换成那个不

**Comment by yjqiang** [comment]
有啊  -c metal

**Comment by mzth** [comment]
应该是不能用银瓜子兑换了，之前在概念版上用瓜子兑换就失败，用硬币还是可以的
