### ISSUE TITLE
运行一段时间后会报错

### ISSUE THREAD

**Issue by JerryRich** [yjqiang/bili2.0#194]
win7系统，多次出现在运行数日后报错并停止运行的情况
![image](https://user-images.githubusercontent.com/31468229/67639760-1e7b7380-f8ca-11e9-9d66-4f3209ce2f45.png)

**Comment by yjqiang** [comment]
安装python3.8

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/85
