### ISSUE TITLE
请问节奏风暴storm_raffle_handler.py的逻辑怎么自由定制

### ISSUE THREAD

**Issue by shadow7755** [yjqiang/bili2.0#195]
storm_raffle_handler.py 中由于没有参数的注释，请问要自由定制时具体要修改
哪行代码，以及修改什么参数，来控制抢风暴的次数，以及时间间隔等等

**Comment by yjqiang** [comment]
这个你自己看了……  join是负责每个用户每次请求的具体执行过程   check负责获取storm信息

**Comment by 2604237845** [comment]
> 这个你自己看了…… join是负责每个用户每次请求的具体执行过程 check负责获取storm信息

大佬我也想问一下，这里我这样修改可以让它多尝试几次节奏风暴吗？修改的有没有问题？
![1](https://user-images.githubusercontent.com/54972064/67651083-6bb71e00-f97a-11e9-9ace-53ffa30df037.png)

**Comment by yjqiang** [comment]
> > 这个你自己看了…… join是负责每个用户每次请求的具体执行过程 check负责获取storm信息
> 
> 大佬我也想问一下，这里我这样修改可以让它多尝试几次节奏风暴吗？修改的有没有问题？
> ![1](https://user-images.githubusercontent.com/54972064/67651083-6bb71e00-f97a-11e9-9ace-53ffa30df037.png)
> 

可以

**Comment by shadow7755** [comment]
就是，如果我想添加尝试次数，就像上图里只要不断添加这个参数到数组里就行了是吧。添加一组就多抢一次？

**Comment by yjqiang** [comment]
> 就是，如果我想添加尝试次数，就像上图里只要不断添加这个参数到数组里就行了是吧。添加一组就多抢一次？

对

**Comment by shadow7755** [comment]
好的，谢谢。我明白了，我想问题的就是这个，这个问题可以关闭了。非常感谢。
