### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by qq312785889** [yjqiang/bili2.0#200]
启动报错，报错信息：ModuleNotFoundError: No module named 'aiohttp'
![image](https://user-images.githubusercontent.com/39783725/68095763-26996b80-fee7-11e9-9f56-7e08fb057f83.png)
第一次接触pip和python，是我操作有问题吗，求大佬解答

**Comment by yjqiang** [comment]
自己百度……

**Comment by pjy612** [comment]
看看项目说明
