### ISSUE TITLE
无法获取到小电视抽奖

### ISSUE THREAD

**Issue by Kjcdkcnjji** [yjqiang/bili2.0#202]
昨天到现在都不正常
![DEBUG1](https://user-images.githubusercontent.com/41225012/68216870-96f5d900-001c-11ea-97ef-913ce4036ecb.jpg)

**Comment by pjy612** [comment]
但是 返回值是 None 的话 
看代码 就是 可能是房间初始化那里 出问题了？

**Comment by yjqiang** [comment]
很奇怪

**Comment by pjy612** [comment]
血崩
![image](https://user-images.githubusercontent.com/4072526/68260827-24671680-0079-11ea-8264-70ab512ca077.png)

**Comment by pjy612** [comment]
不对 好像没啥影响。。。
![image](https://user-images.githubusercontent.com/4072526/68261001-af481100-0079-11ea-8234-8905c00392cc.png)

B站在搞事情！这尼玛3分钟到底发生了啥？！

**Comment by yjqiang** [comment]
我这里是正常的

**Comment by Kjcdkcnjji** [comment]
更新到10/28版后正常 感谢各位大佬
