### ISSUE TITLE
账号登录相关

### ISSUE THREAD

**Issue by 2604237845** [yjqiang/bili2.0#203]
大佬，比如我加了一个新账号，可以不用重启重新让这个新账号进行登录挂机吗，每次添加新账号需要修改配置文件重启程序，有点不方便，可以直接登录或者通过控制台命令来直接添加一个新账号不用修改配置文件来登录就好了。
还有就是求大佬告知程序是多久自动尝试将账号移出小黑屋的，在哪里可以修改这个检测时间

**Comment by yjqiang** [comment]
暂时不支持……这个可能要后续增强了

**Comment by yjqiang** [comment]
user.py里面有个sleep 那就是控制休眠时间点

**Comment by 2604237845** [comment]
> user.py里面有个sleep 那就是控制休眠时间点

大佬，刚刚好像出现了新的抽奖类型
![1](https://user-images.githubusercontent.com/54972064/68444549-26b0a880-0212-11ea-88a3-0603bc2730b3.png)
没有注意是否参与了抽奖....请大佬看一下

**Comment by 2604237845** [comment]
> user.py里面有个sleep 那就是控制休眠时间点

刚刚确定有参加魔法降临抽奖，但是没有看到参加小电视地图抽奖

**Comment by 2604237845** [comment]
小电视推送遗漏统计的覆盖率好像一下变低了好多....是不是漏了挺多抽奖？

**Comment by 2604237845** [comment]
好像有出息了一个33电视地图抽奖....
![1](https://user-images.githubusercontent.com/54972064/68460219-39db6c80-0242-11ea-8235-6ee213ad27b6.png)

**Comment by yjqiang** [comment]
欢迎pr

**Comment by 2604237845** [comment]
> 欢迎pr

大佬这是啥意思....

**Comment by pjy612** [comment]
> > 欢迎pr
> 
> 大佬这是啥意思....

欢迎自己改代码支持后 提交 pull request
