### ISSUE TITLE
程序报错

### ISSUE THREAD

**Issue by 2604237845** [yjqiang/bili2.0#206]
换了个服务器重装了Python3.7之后出现错误，求大佬帮忙看一下什么问题。。。。
![1](https://user-images.githubusercontent.com/54972064/68637223-ee260d00-0538-11ea-929e-d141e9197494.png)
![2](https://user-images.githubusercontent.com/54972064/68637230-f1b99400-0538-11ea-91c9-539769412bae.png)

**Comment by yjqiang** [comment]
ssl错误  自己搜索之前的issue  里面有说明   机器ssl问题

**Comment by 2604237845** [comment]
> ssl错误 自己搜索之前的issue 里面有说明 机器ssl问题
大佬我应该怎么操作。。。我搜索了好久还是没弄好....小白不好意思

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/3

**Comment by 2604237845** [comment]
> #3
实在是太感谢大佬了！小白实在抱歉，啥也不懂，麻烦大佬了，感谢感谢！！！

**Comment by 2604237845** [comment]
解决了
