### ISSUE TITLE
task.toml 的用户自定义设置无法生效

### ISSUE THREAD

**Issue by NPBeta** [yjqiang/bili2.0#209]
以自动投喂勋章任务为例，若出现自定义选项与全局默认选项不一致的情况时，脚本会报错提示。
具体内容如下图：

![image](https://user-images.githubusercontent.com/17808640/68828108-6a5a5500-06df-11ea-97cd-f78903c872d2.png)

若自定义选项与全局选项一致，则不会报错。

task.toml 中的相关配置如下：
[custom_task_arrangement]
    [custom_task_arrangement."752xxxxx@qq.com"]
    send_gift = 0

感谢！

**Comment by yjqiang** [comment]
不清楚你指的是啥……建议把文件打码一下贴上来

**Comment by NPBeta** [comment]
![image](https://user-images.githubusercontent.com/17808640/68830048-94af1100-06e5-11ea-9934-9eabc59b2713.png)
图片上全局配置是 send_gift = -1
下面自定义设置部分是 send_gift = 0
我一共挂了三个号，有一个号是不需要自动投喂礼物的，所以这样设置

**Comment by yjqiang** [comment]
https://paste.ubuntu.com/

**Comment by yjqiang** [comment]
你可能把`send2medal_by_uid`误删了

**Comment by NPBeta** [comment]
的确是这里的问题，已经解决，感谢！
