### ISSUE TITLE
无法登陆美国账号。

### ISSUE THREAD

**Issue by dreamitpossibile** [yjqiang/bili2.0#210]
**再确认一次 issue 题目**
请记得把 issue 标题改成问题描述的概述，而不是简单的一句话，《电脑开不了了》、《闪退了》、《救命啊》这些

**问题描述**
尽量详细叙述发生时间等

**截图或者视频或者报错文字**
截图请务必把名字等信息打码

**必要的系统信息描述等**
python 版本以及系统版本信息

**最近何时更新的脚本**
几天前还是几小时前

**最后确认**
- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ ] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

不是所有的美国账号不能登陆，一部分可以，一部分不行。
在user.toml会显示一段错误的反馈。

1. access_key = ""
2. cookie = ""
3. csrf = "{'ts': 1573742337, 'code': -2111, 'url': 'https://www.bilibili.com/blackboard/version_upgradetip.html', 'message': '设备验证请升级到最新版本'}"
4. uid = "NULL"
5. refresh_token = ""****### 

python3.7.2 运行其他账号没有问题，应该不是机器的问题。

一个星期前安装的。

出问题的b站账号发给你，这个账号可以在网页登陆，app登陆。

**Comment by pjy612** [comment]
在app关设备保护

**Comment by yjqiang** [comment]
b站到app设备保护真的逗比……正常人都是发一个推送app确认，这货是发一个手机号你自己输入……

**Comment by dreamitpossibile** [comment]
感谢解决了问题
