### ISSUE TITLE
广播信息内容有变更，正则表达式匹配后会报错

### ISSUE THREAD

**Issue by BugCreatorZane** [yjqiang/bili2.0#212]
今天突然发现bili_danmu_monitor一直在报错，监听到的小电视是0
打印了下消息发现消息结构变了
![image](https://user-images.githubusercontent.com/47816065/69214278-717ed880-0ba1-11ea-9421-d440a8198049.png)
broadcast_type要改为获取link_url的最后一位吗

**Comment by yjqiang** [comment]
需要测试这个字段是否正确

**Comment by yjqiang** [comment]
不管用  这个字段没用

**Comment by BugCreatorZane** [comment]
> 不管用 这个字段没用

今天好像改了不少字段名称，live_daily_job的签到状态，msg改成了message

**Comment by azalaza** [comment]
是的 我也遇到了同样的问题 目前只领取舰队亲密度 如果有小电视 摩天大楼 除了小地图抽奖 其他的一律会报错 并且不参与抽奖

**Comment by yjqiang** [comment]
> > 不管用 这个字段没用
> 
> 今天好像改了不少字段名称，live_daily_job的签到状态，msg改成了message

这个修复了

**Comment by yjqiang** [comment]
你们讨论其他修改尽量另开issue
