### ISSUE TITLE
每日签到状态检查循环检查问题

### ISSUE THREAD

**Issue by BugCreatorZane** [yjqiang/bili2.0#213]
![image](https://user-images.githubusercontent.com/47816065/69219436-c9234100-0bad-11ea-86b3-f01709d100da.png)
live_daily_job的每日签到接口返回结构有变更，code返回改为了-1，msg改为了message
返回条件不符合导致一直在循环查询

**Comment by 2604237845** [comment]
你这个问题在你上一个话题就已经解决了...你是不是没仔细看哦
![1](https://user-images.githubusercontent.com/54972064/69219857-b8bf9600-0bae-11ea-9e17-656c9d5f081e.png)

**Comment by BugCreatorZane** [comment]
> 你这个问题在你上一个话题就已经解决了...你是不是没仔细看哦
> ![1](https://user-images.githubusercontent.com/54972064/69219857-b8bf9600-0bae-11ea-9e17-656c9d5f081e.png)

看到了，但是只改了输出，没改下面的if条件，导致最新代码会一直循环检查……

**Comment by yjqiang** [comment]
thx
