### ISSUE TITLE
建议增加检测大会员领B币功能（提醒：B币券领取之后切勿在IOS端使用）

### ISSUE THREAD

**Issue by Jutean** [yjqiang/bili2.0#214]
自动检测加自动给自己送
如果不给自己套现，当标题没说

**Comment by 2604237845** [comment]
不觉得有这个必要....

**Comment by pjy612** [comment]
感觉可以有，不过一个月就领一次...

**Comment by Silentely** [comment]
没必要  每个月自己手动领

**Comment by Jutean** [comment]
你觉得时间成本廉价并不代表所有人，谢谢。愿意花钱定制，不白嫖。

发自我的iPhone

在 2019年11月22日，20:31，丶Silently <notifications@github.com> 写道：

﻿

没必要 每个月自己手动领

**Comment by yjqiang** [comment]
友好交流  我觉得这个功能没啥问题  我已经忘记领不少次了

**Comment by someash** [comment]
建议顺便加一个是否自动投个自己的开关。。
