### ISSUE TITLE
 0号数据连接发生致命错误{'code': -1, 'type': 'error', 'data': {'msg': '服务器拉黑了你'}}

### ISSUE THREAD

**Issue by Lambda982** [yjqiang/bili2.0#215]
昨晚到今天一直报异常，但是并没有小黑屋。
不知道是为什么
![7154E86A-BD57-48E3-BE04-85F008FE82E4](https://user-images.githubusercontent.com/16385325/69395637-a4001100-0d1a-11ea-8eb2-d8eca016b7ce.png)

**Comment by yjqiang** [comment]
舰长服务器拉黑了你的ip  等半天就好了

**Comment by pjy612** [comment]
应该是Key到期了

**Comment by Lambda982** [comment]
> 应该是Key到期了

我也是这么想的，然后去看key已经没有库存了，买不了。

**Comment by 2604237845** [comment]
> > 应该是Key到期了
> 
> 我也是这么想的，然后去看key已经没有库存了，买不了。

我也是发现了，然后已经联系大佬加库存了
