### ISSUE TITLE
动态抽奖 id 穷举扫描间隔时间

### ISSUE THREAD

**Issue by 2604237845** [yjqiang/bili2.0#217]
请问大佬动态抽奖 id 穷举扫描是否可以自定义扫描的间隔时间？是修改哪一项？

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/master/dyn/monitor_dyn_raffle.py#L90

**Comment by 2604237845** [comment]
> https://github.com/yjqiang/bili2.0/blob/master/dyn/monitor_dyn_raffle.py#L90

谢谢大佬
