### ISSUE TITLE
前天开始登录新账号，大概率出现服务器繁忙

### ISSUE THREAD

**Issue by azalaza** [yjqiang/bili2.0#220]
2019年11月27日开始，登录新账号，会大概率出现服务器繁忙，有些时候需要尝试登陆 8 9次才能登陆成功，群内有出现类似的情况。服务器版本为2012R2 Py版本是3.6.6 程序为最新的程序，具体图片无法上传。-449，服务器繁忙，请稍后再试

**Comment by azalaza** [comment]
手动使用浏览器，登陆繁忙的账号，可以一次登陆进去，是否是因为验证码服务器挂了。

**Comment by 2604237845** [comment]
这个奇怪好像是B站最近弄的啥吊东西限制，正常的
