### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by lyf1134** [yjqiang/bili2.0#225]
**问题描述**
[2019-12-10 16:12:38] 5号数据连接异常或主动断开，正在处理剩余信息
Task exception was never retrieved
future: <Task finished name='Task-10037' coro=<Client._read_datas() done, defined at C:\Users\\Desktop\bilibili-live-tools-master\bili2.0\danmu\client.py:58> exception=AttributeError("'NoneType' object has no attribute 'group'")>
Traceback (most recent call last):
  File "C:\Users\\Desktop\bilibili-live-tools-master\bili2.0\danmu\client.py", line 60, in _read_datas
    if not await self._read_one():
  File "C:\Users\\Desktop\bilibili-live-tools-master\bili2.0\danmu\bili_danmu.py", line 71, in _read_one
    if not self.handle_danmu(json.loads(body.decode('utf-8'))):
  File "C:\Users\\Desktop\bilibili-live-tools-master\bili2.0\danmu\bili_danmu_monitor.py", line 100, in handle_danmu
    description0, raffle_name = self.NOTICE_MSG_TV_PATTERN.match(msg_common).group(1, 2)
AttributeError: 'NoneType' object has no attribute 'group'
[2019-12-10 16:12:38] 5号数据连接退出，剩余任务处理完毕

**必要的系统信息描述等**
python 3.8 windows 19041

**最近何时更新的脚本**
1h

**最后确认**
- [ V] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [V ] 我代码上次更新时间距今没有超过 2 个月以上
- [V] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ V] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
b站zz弹幕已经废了……

**Comment by pjy612** [comment]
```
{'cmd': 'NOTICE_MSG', 'full': {'head_icon': 'https://i0.hdslb.com/bfs/live/00f26756182b2e9d06c00af23001bc8e10da67d0.webp', 'tail_icon': 'https://i0.hdslb.com/bfs/live/822da481fdaba986d738db5d8fd469ffa95a8fa1.webp', 'head_icon_fa': 'https://i0.hdslb.com/bfs/live/77983005023dc3f31cd599b637c83a764c842f87.png', 'tail_icon_fa': 'https://i0.hdslb.com/bfs/live/38cb2a9f1209b16c0f15162b0b553e3b28d9f16f.png', 'head_icon_fan': 36, 'tail_icon_fan': 4, 'background': '#6098FFFF', 'color': '#FFFFFFFF', 'highlight': '#FDFF2FFF', 'time': 20}, 'half': {'head_icon': 'https://i0.hdslb.com/bfs/live/358cc52e974b315e83eee429858de4fee97a1ef5.png', 'tail_icon': '', 'background': '#7BB6F2FF', 'color': '#FFFFFFFF', 'highlight': '#FDFF2FFF', 'time': 15}, 'side': {'head_icon': 'https://i0.hdslb.com/bfs/live/7ef6f2b7fe01c550f93dd569ca4b573b80b9e6a5.png', 'background': '#E6F4FFFF', 'color': '#51A8FBFF', 'highlight': '#0081F0FF', 'border': '#BDD9FFFF'}, 'roomid': 302816, 'real_roomid': 302816, 'msg_common': '', 'msg_self': '<%枕边小软%>本场大乱斗获胜可获得双倍神力值，快点投喂道具支持ta~', 'link_url': '', 'msg_type': 2, 'shield_uid': -1, 'business_id': '302816'}
```
捞了下出错的 = =。貌似不是礼物。。。为空的屏蔽掉好了。。。

**Comment by yjqiang** [comment]
link_url你看看判定可行么

**Comment by pjy612** [comment]
感觉可以。。。
这个好像是在当前直播间乱斗中的通知，提醒观众打钱的 23333

**Comment by yjqiang** [comment]
@pjy612 msg_common 吧，url 这个和今日33地图历险冲突……
