### ISSUE TITLE
因为辣条机而被封禁账号（非小黑屋，是封禁）

### ISSUE THREAD

**Issue by 8MiYile** [yjqiang/bili2.0#228]
本issues是收集挂辣条机导致被主站莫名其妙的封号

> 开此帖的目的是因为从12月20号开始 我的账号列表内的号全被主站封号,而这些账号仅用于单推主播

**Comment by 8MiYile** [comment]
您好，这边核实为异常注册导致账号封禁，烦请核对下述信息，核实无误可以为您操作解封。

请根据下述信息提供出信息内容，后续会有相关工作人员会根据您提供的内容进行核实判断。 

①常用登陆地
②账号绑定的手机号和邮箱号
③注册时间，地点与方式
④实名认证
⑤曾经通过何种方式修改过密码+相应时间（PC端修改 或 移动端修改）
⑥绑过的第三方账号信息+相应时间
⑦所设置过的密保问题及答案（包括现用问题及答案）+相应时间
⑧所使用过的昵称+相应时间
⑨常用浏览器&插件（包括第三方插件）上述内容，如没有的话就填写无即可。

**Comment by yjqiang** [comment]
请详细描述情况 包括且不限于你是否在不同ip下登陆或挂机、你是否长时间不休眠挂机以及你是否可能泄露过账号密码等

**Comment by 8MiYile** [comment]
工作环境

**Comment by yjqiang** [comment]
等解封情况吧  或者直接找客服查询

**Comment by 8MiYile** [comment]
你好，尊敬的用户:
你的工单 #1503550338，用户留言-上海用户 已有回复内容更新，请查阅！

您也可以点击下方的链接登录查看更多的工单记录或进行工单回复。
查看详情https://service.bilibili.com/console/helpCenter
以下为最近的工单回复记录
——————————————————
回复用户：无双
回复时间：2019-12-20 16:22:20
回复内容：
抱歉让您久等了，经与工作人员反复核实争取，该账号违规情况属实，工作人员没有误判，故无法为您解封，请见谅。封禁只会限制互动功能的，封禁的账号也是可以观看，收藏视频，不影响游戏的使用，如有需要建议您重新注册账号使用。也非常感谢您对bilibili的支持，谢谢。

——————————————————
创建用户：a-8yl@outlook.com
创建时间：2019-12-20 16:10:14
工单内容：uid 470181913账户永久封禁可以恢复正常使用么？




昵称：上海用户
邮箱：a-8yl@outlook.com
——————————————————

**Comment by yjqiang** [comment]
具体是哪方面违规了？有说明么

**Comment by 8MiYile** [comment]
登录过账号查看了,只有小黑屋记录没有系统通知

**Comment by yjqiang** [comment]
…你直接问客服啊  就问他你让他说清楚是哪一点原因被封禁   b站不是有在线客服么

**Comment by 8MiYile** [comment]
追问了一次 没有反应

**Comment by yjqiang** [comment]
不清楚具体原因那就难办了  可能几天后我会关掉这个issue  希望你可以尽快搞清楚原因

**Comment by luckysyq** [comment]
个人感觉是ip的锅，广电的ip大多处于波动状态。如果你设置了定时重启，可以说每次重启都是一个新的ip也不为过

**Comment by Jutean** [comment]
围观一下，如果像楼上所说，到时候云到期了扔公司服务器上去。

**Comment by lovezm** [comment]
小号被封是很正常的，如果是大号你可以找找原因，小号的话 并非此程序导致，所有的挂机程序都有可能，别问我怎么知道的 300个小号 主站全封 我还接码绑定了手机。

**Comment by wzxyisme** [comment]
我刚才两个号就因为突然短时间内抽了1万多根辣条，IP被ban了😂

**Comment by wzxyisme** [comment]
可以给辣条机加个阈值设置吗？

**Comment by yjqiang** [comment]
@wzxyisme https://github.com/yjqiang/bili2.0/blob/master/conf/task.sample.toml#L3-L5

**Comment by luckrhyme7** [comment]
我几天之前也被封了,现在还没解除,问了客服说十几天会解,真的假的?之前还只是小黑屋脚本能登,现在使用脚本已经无法登陆了

**Comment by luckrhyme7** [comment]
没有影响主站,但是跟关小黑屋又不一样,登陆模块返回449登录繁忙,无法登陆
