### ISSUE TITLE
登陆不了

### ISSUE THREAD

**Issue by pxmxxp** [yjqiang/bili2.0#229]
**再确认一次 issue 题目**
登录不了

**问题描述**
每一次登陆都是
# <class 'tasks.login.LoginTask'>
# ((-2, None),)

我登陆时填写用户名和密码

**截图或者视频或者报错文字**
截图请务必把名字等信息打码

**必要的系统信息描述等**
python 3.8

**最近何时更新的脚本**
2019年12月21日

**最后确认**
- [ ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ ] 我代码上次更新时间距今没有超过 2 个月以上
- [ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by suzuka1** [comment]
同，昨天下午开始的

**Comment by luckysyq** [comment]
> 同，昨天下午开始的

尝试3.7x 版本，我尝试了未见异常

**Comment by popo-bear** [comment]
> > 同，昨天下午开始的
> 
> 尝试3.7x 版本，我尝试了未见异常

如果，重新获取USER信息无论puthon版本都会运行不下去。

**Comment by popo-bear** [comment]
群里有人说V2 V3的 反馈是一样的，看来是破站改了东西 。         运行只到-2不走，是message那条修改的缘故，把message改回msg，程序可以跑下去但是-499繁忙，和以前端口问题相同的运行结果。

**Comment by yjqiang** [comment]
确认是bug

**Comment by 2604237845** [comment]
我也是一样的，登陆不了，卡住不动了

**Comment by popo-bear** [comment]
> 确认是bug
我把message该回去，可以执行下去，发现还是449错误，和之前端口错误是一样的。应该是随机码验证哪里又改了。

**Comment by popo-bear** [comment]
> 我也是一样的，登陆不了，卡住不动了

用以前的user文件，可以跳过凑合几天，直到令牌过期。

**Comment by 2604237845** [comment]
> > 我也是一样的，登陆不了，卡住不动了
> 
> 用以前的user文件，可以跳过凑合几天，直到令牌过期。

谢谢告知！我的就是令牌过期了.....不知道有没有直接提取的办法

**Comment by 2604237845** [comment]
找到了一个非常麻烦的办法...先用曙光那边的登录好之后，再提前令牌cookie等，就可以通过了

**Comment by gouku** [comment]
尝试了上面的最新commit，全新的账号（未使用过bili2.0），出现验证码循环

```
此次登录出现验证码,识别结果为yn7mm
此次登录出现验证码,识别结果为dgmyg
此次登录出现验证码,识别结果为y7cp7
此次登录出现验证码,识别结果为7bbdb
此次登录出现验证码,识别结果为y875a
此次登录出现验证码,识别结果为2xp4n
此次登录出现验证码,识别结果为a8ab8
此次登录出现验证码,识别结果为6nwb4
此次登录出现验证码,识别结果为ayc4x
此次登录出现验证码,识别结果为bnc7b
此次登录出现验证码,识别结果为w2gea
此次登录出现验证码,识别结果为ndf72
此次登录出现验证码,识别结果为dxb7b
此次登录出现验证码,识别结果为p3b78
此次登录出现验证码,识别结果为y5xf5
此次登录出现验证码,识别结果为2y8n5
此次登录出现验证码,识别结果为w6a4c
此次登录出现验证码,识别结果为233e
此次登录出现验证码,识别结果为n6fnn
此次登录出现验证码,识别结果为3mc27
此次登录出现验证码,识别结果为dpy78
此次登录出现验证码,识别结果为6d7x8
此次登录出现验证码,识别结果为y4b3e
```

**Comment by yjqiang** [comment]
@gouku https://github.com/yjqiang/bili2.0/issues/224
