### ISSUE TITLE
APP心跳失败

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#23]
![1](https://user-images.githubusercontent.com/42423154/45331919-1abd4e00-b55d-11e8-9bfe-f6a24b50d7df.png)
![2](https://user-images.githubusercontent.com/42423154/45331923-1f820200-b55d-11e8-8676-af27db5ff768.png)

**Comment by yjqiang** [comment]
只要不是一直蹦，不是bug，就是各种网络问题而已
