### ISSUE TITLE
无法完成观看视频任务

### ISSUE THREAD

**Issue by scyraxs** [yjqiang/bili2.0#232]
**问题描述**
无法完成观看视频任务

**截图或者视频或者报错文字**
开始获取视频观看经验
获取视频观看 {'code': 0, 'message': '0', 'ttl': 1}

**必要的系统信息描述等**
python3.7.4

**最近何时更新的脚本**
今天

**最后确认**
- [ ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ ] 我代码上次更新时间距今没有超过 2 个月以上
- [ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
b站延迟，参与后可能几小时才更新状态，我这里正常
