### ISSUE TITLE
toml无法读取

### ISSUE THREAD

**Issue by lovezm** [yjqiang/bili2.0#234]
![image](https://user-images.githubusercontent.com/10624938/71387361-7a464c80-262e-11ea-8722-912f4973bfe0.png)

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/71387403-b5488000-262e-11ea-890f-7595eaa643a1.png)

**Comment by lovezm** [comment]
诶 我图怎么老挂
![RWKP6~__ZDERWOZYIES4_GA.png](https://i.loli.net/2019/12/24/ZEdUGePwbn7Hy1v.png)

**Comment by lovezm** [comment]
https://i.loli.net/2019/12/24/ZEdUGePwbn7Hy1v.png

**Comment by lovezm** [comment]
试着新建了user配置文件 还是同样的报错 不知为何

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/233 
你们扎堆来搞我心态？

**Comment by 2604237845** [comment]
不要用记事本修改！用Notepad来修改

**Comment by lovezm** [comment]
不是手打的问题 --  编码UTF8改成无bom就好了

**Comment by Jutean** [comment]
> 不要用记事本修改！用Notepad来修改，中英文符合分清楚
别用反华的notepad了  用VScode
