### ISSUE TITLE
关于查询统计情况时去掉多余信息请求

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#237]
![image](https://user-images.githubusercontent.com/42423154/71439331-30e02500-2734-11ea-9898-c877ab9f9c17.png)
使用控制台查询统计情况时，会输出不需要的数据。希望能改进。

另外问下，长指令和短指令二选一都可以是吗？

**Comment by yjqiang** [comment]
可以二选一，那个是调试统计，之后会去掉
