### ISSUE TITLE
“同时”有大量小电视，会导致过期后仍然还尝试抽取

### ISSUE THREAD

**Issue by Twoleaf** [yjqiang/bili2.0#240]
小电视过期后，后续还是会队列参加，导致不参加还没过期的小电视
建议如果这个小电视的id如果判断为过期，后面还没参加的账号就放弃这个小电视id

**Comment by yjqiang** [comment]
之前以为是notifier这里判定一下就行……发现不太对  延迟发生地点在web_session这里，notifier管不到了。

**Comment by 2604237845** [comment]
是的，目前凌晨的时候高能领不完都过期了....本来不会403频繁因为领取了很多过期的就频繁了...很难受

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/259
集中讨论在这里👆
