### ISSUE TITLE
关于赠送指定数目辣条到指定房间

### ISSUE THREAD

**Issue by biechuyangwang** [yjqiang/bili2.0#241]
问题一：每次执行该功能都使用默认的user(id为0的用户)；
问题二：-n参数不支持传入-1(也就是清空辣条的操作)，

而上述两个问题在功能22(银瓜子购买辣条)都支持
问题一，在功能22中是默认遍历所有用户。
问题二，在功能22中是-1代表最大值。

如果您有空闲可以帮忙处理一下这个问题。

**Comment by yjqiang** [comment]
居然有人用这个功能……  还打算删了呢

**Comment by yjqiang** [comment]
默认会一直是0，这个是为了保持一致

**Comment by biechuyangwang** [comment]
毕竟有时要单推up的up等级，多账号的清空辣条功能，还是很方便的

**Comment by pjy612** [comment]
就怕手贱。。。然后就哭了。。。
