### ISSUE TITLE
关于主站任务中的投币任务

### ISSUE THREAD

**Issue by biechuyangwang** [yjqiang/bili2.0#242]
投币只支持send_coin2video(视频投稿)

yj大佬，有空的能不能增加一个功能，根据upper投币时，顺便也查询一下音频投稿，增加投币成功的几率。

**Comment by yjqiang** [comment]
不会这么做。。。没啥意义，本来投币这里就不是用的全体视频 https://github.com/yjqiang/bili2.0/blob/master/tasks/main_daily_job.py#L160
也就没什么意义去整一堆其他的了。
