### ISSUE TITLE
服务器拉黑了你

### ISSUE THREAD

**Issue by wwh1004** [yjqiang/bili2.0#243]
![Snipaste_2019-12-31_19-22-28](https://user-images.githubusercontent.com/27536652/71620098-eadb0380-2c02-11ea-9872-711f36bfc9c2.png)

我用网页端b站，还是可以抽奖领舰队奖励的，但是脚本显示服务器拉黑了你？？

**Comment by wwh1004** [comment]
好吧，我知道了，好像是key到期了...
key到期了脚本可以提示下吗？

**Comment by yjqiang** [comment]
到期不会提示你的，到期后数据库就清理了，不可能还保留的。拉黑这里我逻辑写错了，有时间会修改掉的。

**Comment by yjqiang** [comment]
https://github.com/yjqiang/YjMonitor/commit/730414363357dec9b46ef215683410b2c82b47ae

**Comment by pjy612** [comment]
大佬 他说的应该是 被清理后 Bili2.0 自动重试 然后 被认为是轮询 然后 就给拉黑了吧？
是不是 Bili2.0 0号的时候如果Key已经多人用或者 Key无效 的话，就别重试了？

**Comment by yjqiang** [comment]
> 大佬 他说的应该是 被清理后 Bili2.0 自动重试 然后 被认为是轮询 然后 就给拉黑了吧？
> 是不是 Bili2.0 0号的时候如果Key已经多人用或者 Key无效 的话，就别重试了？

那倒是可以。。。。就是很多人肯定就忘了过期了
