### ISSUE TITLE
程序运行一段时间后出错，日志中有大量反复请求未成功

### ISSUE THREAD

**Issue by Doraemonsan** [yjqiang/bili2.0#246]
运行约一天后出现的，以下为日志，已抹除登录信息
![image](https://user-images.githubusercontent.com/21234683/71763707-df951a00-2f19-11ea-8a91-4b20e3a415fc.png)
[run copy.log](https://github.com/yjqiang/bili2.0/files/4021733/run.copy.log)

**Comment by yjqiang** [comment]
TimeoutError 你自己本地网络不稳定
