### ISSUE TITLE
安卓平台：休眠过后不会自动启动;1加回车不能打开控制台

### ISSUE THREAD

**Issue by likeman66** [yjqiang/bili2.0#247]
*问题描述**
重新安装过bili2.0，都无法打开控制台。
第二个问题就是休眠过后无法正常自启，今天是从早上十点半开始到下午六点半一直没自动恢复

**截图或者视频或者报错文字**
截图请务必把名字等信息打码

**必要的系统信息描述等**
python 3.8.1
安卓9

**最近何时更新的脚本**
昨天（更新过后两个问题依然没有解决）

**最后确认**
- [ √] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [√ ] 我代码上次更新时间距今没有超过 2 个月以上
- [√ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [√ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by likeman66** [comment]
![2021578393185_ pic_hd](https://user-images.githubusercontent.com/59259075/71889068-55002500-317c-11ea-9132-060171f40f16.jpg)
![2011578393184_ pic_hd](https://user-images.githubusercontent.com/59259075/71889078-5af60600-317c-11ea-902a-91d22967668f.jpg)

**Comment by likeman66** [comment]
![WechatIMG201](https://user-images.githubusercontent.com/59259075/71889166-8842b400-317c-11ea-8220-af1a1054ab88.png)
![WechatIMG202](https://user-images.githubusercontent.com/59259075/71889173-8a0c7780-317c-11ea-8a5a-1b84d5c06731.png)

**Comment by likeman66** [comment]
百分百确定12点半之后没自动恢复，termux因为信息太多，历史消息已经截图不到了

**Comment by zhz1237ok** [comment]
草，还真有人用手机模拟终端来运行python

**Comment by yjqiang** [comment]
这边正常，没有log不好测试，至于命令行问题，可能是 https://github.com/yjqiang/bili2.0/blob/master/run.py#L157 的原因，你试试把他设置为恒有效。

**Comment by likeman66** [comment]
> 草，还真有人用手机模拟终端来运行python

我寻思别人也都没问题啊，咋不能用手机模拟运行呢。别人都会自动重启，也能打开控制台，就我不行

**Comment by yjqiang** [comment]
那张一直刷重连的要么是你网络不对劲，要么是你python环境有问题

**Comment by yjqiang** [comment]
> 草，还真有人用手机模拟终端来运行python

我还用ipad跑呢。。。

**Comment by likeman66** [comment]
> 那张一直刷重连的要么是你网络不对劲，要么是你python环境有问题

python环境有问题是我需要重现安装一次python吗

**Comment by yjqiang** [comment]
> > 那张一直刷重连的要么是你网络不对劲，要么是你python环境有问题
> 
> python环境有问题是我需要重现安装一次python吗

意思是鬼知道什么原因，这东西只能你自己摸索，或者直接放弃。。。

**Comment by yjqiang** [comment]
由于非代码问题，且暂时看起来没有什么办法，关闭
