### ISSUE TITLE
无法登录，显示出现验证码，如图

### ISSUE THREAD

**Issue by scyraxs** [yjqiang/bili2.0#248]
**问题描述**
[2020.1.9]

**截图或者视频或者报错文字**
![2020-01-09_114442](https://user-images.githubusercontent.com/49806577/72036616-534a7480-32d6-11ea-8143-d959303e9635.png)
**必要的系统信息描述等**
python 3.7.3 win10

**最近何时更新的脚本**
2020.1.9

**最后确认**
- [ ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ ] 我代码上次更新时间距今没有超过 2 个月以上
- [ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by scyraxs** [comment]
> **问题描述**
> [2020.1.9]
> 
> **截图或者视频或者报错文字**
>
![2020-01-09_114442](https://user-images.githubusercontent.com/49806577/72036697-a1f80e80-32d6-11ea-83b6-ef5ffcb219e4.png)

> **必要的系统信息描述等**
> python 3.7.3 win10
> 
> **最近何时更新的脚本**
> 2020.1.9
> 
> **最后确认**
> 
> * [ ]  我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
> * [ ]  我代码上次更新时间距今没有超过 2 个月以上
> * [ ]  我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
> * [ ]  我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/224
