### ISSUE TITLE
能否添加一个开关来控制弹幕监控

### ISSUE THREAD

**Issue by Womsxd** [yjqiang/bili2.0#249]
rt.
因为本人用阿里云学生机来进行挂机，领取小电视/舰长的功能用不到，这个时候弹幕监控功能就没有什么用处了，希望可以加个开关来进行关闭

**Comment by yjqiang** [comment]
嗯 其实监控用不了多少电脑性能；
领取小电视/舰长可以conf里面控制；
你执意要关掉弹幕监控的话我可能要看看逻辑这里是否对这个判空有考虑。

**Comment by Womsxd** [comment]
实际上还是服务器的网络带不动监控，有时候直接吃满

**Comment by yjqiang** [comment]
????????
这还是 websocket，要是 tcp 这不得掉线重连掉线重连？

**Comment by Womsxd** [comment]
那应该是其他问题，我自己去排除
