### ISSUE TITLE
休眠用户配置

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#25]
user.toml中有没写username和password等等的账号，则会出现API错误，信息如下（截图无法上传……）
hhhhhhjjjjdjdjddjdjdjjd.........dj 3
(另，催一催bili2.0的62进制跟进)
有点好奇用62进制的初衷是为了什么，觉得有点不太必要，怕被别人盗用？

**Comment by yjqiang** [comment]
没写账户你说过个🥚啊 总不能让我自己填写密码吧……

**Comment by yjqiang** [comment]
62进制在于有的人小号监控可能房间号长，弹幕字数限制

**Comment by rabbit2rabbit** [comment]
对了，关于工作状态，能否在配置文件写个真假，以做工作睡眠模式的开关，有一些帐号不需要这个工作睡眠模式（不怕死）

**Comment by yjqiang** [comment]
睡眠模式 那里只能所有账号一起睡眠或不睡 你想分开设置？

**Comment by rabbit2rabbit** [comment]
分开设置肯定很麻烦的，只需要基本的一起全部睡眠或者不睡眠这样子，就基本满足了
