### ISSUE TITLE
账号登陆相关：账号每次登录都要输入一次验证码

### ISSUE THREAD

**Issue by yuban10703** [yjqiang/bili2.0#253]
之前我的账号多设备登录现在账号每次登录都要输入一次验证码,有什么办法能不改密码登录
![image](https://user-images.githubusercontent.com/39484884/72544090-b1bcb780-38c1-11ea-98c3-427535d82dda.png)
![image](https://user-images.githubusercontent.com/39484884/72544182-d3b63a00-38c1-11ea-9103-66b714329c53.png)

**Comment by yjqiang** [comment]
异常只能需要电脑登录一次解除警报  之后应该就可以了

**Comment by yjqiang** [comment]
或者看看你是不是开了设备保护？https://github.com/yjqiang/bili2.0/issues/210

**Comment by yuban10703** [comment]
改了密码就好了
![`$ PA1FN7)@HF}LV{@VGV~G](https://user-images.githubusercontent.com/39484884/72578071-e35c6f80-390f-11ea-8c45-eeb09a9b0b5f.jpg)
