### ISSUE TITLE
无限循环重登链接弹幕服务器

### ISSUE THREAD

**Issue by 2604237845** [yjqiang/bili2.0#258]
大佬请看这是什么问题。。。。
![QQ截图20200124232737](https://user-images.githubusercontent.com/54972064/73080850-77769a00-3f01-11ea-9b91-d1d4dd873c66.png)

**Comment by yjqiang** [comment]
？哪里循环了

**Comment by 2604237845** [comment]
大佬，没问题了...不清楚挂的好好的，突然就无限重登，我覆盖了一遍文件又好了...
