### ISSUE TITLE
单ip多账号风控原因和两个解决方法

### ISSUE THREAD

**Issue by azalaza** [yjqiang/bili2.0#259]
单ip大约挂了40-50个号 web_session限制了2 tv里限制了5  bls期间偷塔也不会导致403 在今日凌晨00:00居然403了 后台观察了下 是因为几个房间同时丢了几十个小电视  程序一直在领取过期的小电视 一直触发这个奖品已被领完了 请下次在快一点 导致服务器403 
提出两个解决方法 yj哥哥可以考虑一下
第一种解决方法 获取房间当前抽奖个数 超过**数量直接不参与 或者设置超过***数量 只抽**个
第二种解决方法 把全部房间里的抽奖 放到一个数组里 超过设定数字 不往里面继续放
如不在该数组内的 不参与

**Comment by 2604237845** [comment]
这个方法挺好的，YJ大佬可以考虑一下

**Comment by pjy612** [comment]
还不如连过期时间一起传进去，循环处理前和处理中比较过期时间 大于当期时间的直接扔掉

**Comment by yjqiang** [comment]
> 还不如连过期时间一起传进去，循环处理前和处理中比较过期时间 大于当期时间的直接扔掉

已经解决了，`timeout` 就行，原理就是你说的那样
