### ISSUE TITLE
关于一次性监控到多个高能的参与

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#26]
上周日，一晚上的高能都是按百算的，出现过403频繁，还有过后连接服务器卡顿，且出现切换API错误的反馈。
怀疑是一次性参与太多，导致的问题，可否设置成，检测到超过50\100以上的高能，分批次参与，4-5秒参与10个这样子，120秒的高能时间应该足够抽200-300个，不会导致后面一个都参与不了的尴尬。

**Comment by yjqiang** [comment]
高能的参与已经按照最大持续时间加入了人为延迟

**Comment by yjqiang** [comment]
api错误那里已经处理了  会重新登录

**Comment by rabbit2rabbit** [comment]
![Image](https://i.imgur.com/pmo9Ile.jpg)

**Comment by yjqiang** [comment]
验证码识别服务器超出频率阈值，不是bug
