### ISSUE TITLE
最近非常高频率的出现"{'code': 400, 'msg': '你错过了奖励，下次要更快一点哦~'}"

### ISSUE THREAD

**Issue by zhu1040028623** [yjqiang/bili2.0#260]
最近非常高频率的出现"{'code': 400, 'msg': '你错过了奖励，下次要更快一点哦~'}"
想请问下，是我什么地方没有配置好吗还是别的问题？

**Comment by yjqiang** [comment]
如果不是用户过多的话 可能是代码本身原因

**Comment by zhu1040028623** [comment]
明白了就是挂脚本的人太多了，那我在哪里能调节收到小电视或者上舰信息后，去领取的时间呢 我在想如果我快一点领取 是不是就能降低出现400的概率

**Comment by yjqiang** [comment]
目前是做了约束  web_session.py 里面有个semaphore是全局约束的，你不怕403频繁你就直接开大

**Comment by zhu1040028623** [comment]
是调节 web_session.py 里面的 sem = asyncio.Semaphore(3) 把这个3调大对吗

**Comment by yjqiang** [comment]
对

**Comment by zhu1040028623** [comment]
目前我已经将参数调到10 但是还是有很多 400 出现

**Comment by yjqiang** [comment]
那就是人太多了

**Comment by zhu1040028623** [comment]
好的 谢谢你的解答

**Comment by pjy612** [comment]
你确定这个不是节奏风暴的提示？

**Comment by yjqiang** [comment]
@pjy612 有道理啊。。。awsl

**Comment by shoucandanghehe** [comment]
我这里有一个号同时挂了yoki和本项目，基本一个都抢不到233
改到10也抢不到233
