### ISSUE TITLE
UA格式不正确

### ISSUE THREAD

**Issue by yunowo** [yjqiang/bili2.0#261]
94dc8cb1f0c98c3a8385c2d3a7a3690d84a87797 修改的UA为
`Mozilla/5.0 BilidDroid/5.51.1(bbcallen@gmail.com)`，客户端UA为
`Mozilla/5.0 BiliDroid/5.53.1 (bbcallen@gmail.com)`

**Comment by yjqiang** [comment]
@yunowo en 你提交一个pr吧
