### ISSUE TITLE
Docker添加容器时报错（Mac）

### ISSUE THREAD

**Issue by MisakaXeon** [yjqiang/bili2.0#265]
手动运行正常，安装完docker根据作者大大的方法添加容器时提示error: Your local changes to the following files would be overwritten by merge: run.py
请问怎么解决，本人小白2333

MacBook-Pro:bili2.0-master misaka$ docker run --rm -it   -v $(pwd)/user.sample.toml:/app/conf/user.toml   -v $(pwd)/ctrl.sample.toml:/app/conf/ctrl.toml   -v $(pwd)/run.py:/app/run.py   zsnmwy/bili2.0
remote: Enumerating objects: 334, done.
remote: Counting objects: 100% (334/334), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 961 (delta 290), reused 285 (delta 246), pack-reused 627
Receiving objects: 100% (961/961), 419.94 KiB | 242.00 KiB/s, done.
Resolving deltas: 100% (662/662), completed with 53 local objects.
From https://github.com/yjqiang/bili2.0
   215a879..362e793  master     -> origin/master
Updating 215a879..362e793
error: Your local changes to the following files would be overwritten by merge:
	run.py
Please commit your changes or stash them before you merge.
Aborting
MacBook-Pro:bili2.0-master misaka$

**Comment by yjqiang** [comment]
8⃣️💊说了  我也不会这个东西……  docker是其他人贡献的  我自己没改过……

**Comment by MisakaXeon** [comment]
> 8⃣️💊说了 我也不会这个东西…… docker是其他人贡献的 我自己没改过……

好吧谢谢作者大大了

**Comment by yjqiang** [comment]
开着吧  没什么问题  说不定以后我会研究一下这个东西

**Comment by yjqiang** [comment]
@MisakaXeon 你测试看看，https://github.com/yjqiang/bili2.0/pull/266 这个pr管用么

**Comment by MisakaXeon** [comment]
> @MisakaXeon 你测试看看，#266 这个pr管用么

感谢大佬的修改，但是好像还是报错了，不过完全不一样了，这是新指令运行后的日志

`MacBook-Pro:bili2.0-master misaka$ docker run --rm -it \
>   -v $(pwd)/user.sample.toml:/app/conf/user.toml \
>   -v $(pwd)/ctrl.sample.toml:/app/conf/ctrl.toml \
>   -v $(pwd)/task.sample.toml:/app/conf/task.toml \
>   zsnmwy/bili2.0
remote: Enumerating objects: 334, done.
remote: Counting objects: 100% (334/334), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 961 (delta 290), reused 285 (delta 246), pack-reused 627
Receiving objects: 100% (961/961), 419.94 KiB | 263.00 KiB/s, done.
Resolving deltas: 100% (662/662), completed with 53 local objects.
From https://github.com/yjqiang/bili2.0
   215a879..362e793  master     -> origin/master
Updating 215a879..362e793
Fast-forward
 .github/ISSUE_TEMPLATE/bug_report.md     |  29 +++
 .gitignore                               |   2 +
 LICENSE                                  |  21 ++
 README.md                                |  98 ++++----
 bili_console.py                          | 190 ---------------
 bili_global.py                           |   1 -
 bili_sched.py                            | 133 +++++++++++
 bili_statistics.py                       | 302 ++++++++++++++++++++----
 bug                                      |  10 -
 conf/bili.toml                           |   2 +-
 conf/ctrl.sample.toml                    |  57 ++---
 conf/task.sample.toml                    |  72 ++++++
 conf/txt2toml.py                         |  45 ++--
 conf_loader.py                           |  65 ++---
 console_cmd.py                           | 290 +++++++++++++++++++++++
 danmu/base_danmu.py                      | 194 ---------------
 danmu/bili_danmu.py                      |  93 ++++++++
 danmu/bili_danmu_monitor.py              | 120 ++++++++++
 danmu/client.py                          | 118 ++++++++++
 danmu/conn.py                            | 181 ++++++++++++++
 danmu/monitor_danmu_raffle.py            | 154 ------------
 danmu/raffle_handler.py                  |  26 +-
 danmu/yj_monitor.py                      | 326 +++++++------------------
 dyn/add_colomn_joined2old_staus_table.py |  53 -----
 dyn/dyn_raffle_sql.py                    |   1 +
 dyn/monitor_dyn_raffle.py                | 100 +++++---
 exceptions.py                            |   4 +
 json_rsp_ctrl.py                         | 225 ++++++------------
 notifier.py                              | 393 ++++++++++++++++++++++---------
 printer.py                               | 233 +++++++++++-------
 reqs/custom.py                           |  31 +++
 reqs/guard_raffle_handler.py             |  19 +-
 reqs/live_daily_job.py                   |  78 +++---
 reqs/login.py                            | 105 +++++----
 reqs/main_daily_job.py                   |  27 ++-
 reqs/manga_daily_job.py                  |  49 ++++
 reqs/pk_raffle_handler.py                |  25 ++
 reqs/storm_raffle_handler.py             |  12 +-
 reqs/substance_raffle_handler.py         |  31 +--
 reqs/tv_raffle_handler.py                |  70 +++---
 reqs/utils.py                            |  47 ++--
 requirements.txt                         |  14 +-
 run.py                                   | 194 ++++++++++-----
 substance/monitor_substance_raffle.py    |  91 ++++---
 substance/substance_raffle_sql.py        |   1 +
 support.jpeg                             | Bin 0 -> 48196 bytes
 tasks/base_class.py                      |  63 +++++
 tasks/bili_console.py                    | 331 ++++++++++++++++++++++++++
 tasks/custom.py                          |  79 +++++--
 tasks/dyn_raffle_handler.py              | 222 +++++++++--------
 tasks/guard_raffle_handler.py            |  64 ++---
 tasks/live_daily_job.py                  | 352 +++++++++++++--------------
 tasks/login.py                           |  39 ++-
 tasks/main_daily_job.py                  | 238 +++++++++----------
 tasks/manga_daily_job.py                 |  37 +++
 tasks/pk_raffle_handler.py               |  44 ++++
 tasks/storm_raffle_handler.py            |  27 +--
 tasks/substance_raffle_handler.py        |  43 ++--
 tasks/tv_raffle_handler.py               | 121 ++--------
 tasks/utils.py                           | 309 +++++-------------------
 user.py                                  | 209 ++++++++--------
 user_status.py                           | 150 ------------
 utils.py                                 |  31 ++-
 web_session.py                           | 173 +++++++-------
 64 files changed, 3919 insertions(+), 2945 deletions(-)
 create mode 100644 .github/ISSUE_TEMPLATE/bug_report.md
 create mode 100644 LICENSE
 delete mode 100644 bili_console.py
 create mode 100644 bili_sched.py
 delete mode 100644 bug
 create mode 100644 conf/task.sample.toml
 create mode 100644 console_cmd.py
 delete mode 100644 danmu/base_danmu.py
 create mode 100644 danmu/bili_danmu.py
 create mode 100644 danmu/bili_danmu_monitor.py
 create mode 100644 danmu/client.py
 create mode 100644 danmu/conn.py
 delete mode 100644 danmu/monitor_danmu_raffle.py
 delete mode 100644 dyn/add_colomn_joined2old_staus_table.py
 create mode 100644 reqs/manga_daily_job.py
 create mode 100644 reqs/pk_raffle_handler.py
 create mode 100644 support.jpeg
 create mode 100644 tasks/base_class.py
 create mode 100644 tasks/bili_console.py
 create mode 100644 tasks/manga_daily_job.py
 create mode 100644 tasks/pk_raffle_handler.py
 delete mode 100644 user_status.py
Collecting aiohttp==3.6.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c2/f7/f0ad3dbace4762fef5d80aa4124b41bf218e4c4dd6d387a86cede707d9a4/aiohttp-3.6.2-py3-none-any.whl (441kB)
    100% |████████████████████████████████| 450kB 76kB/s 
Collecting aiojobs==0.2.2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/a7/8e/1d41d21e7cd09d744921490be99a9e2cfa498ae1af36b9c3ee0c3395d2c9/aiojobs-0.2.2-py3-none-any.whl
Collecting attrs==19.3.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting decorator==4.4.1 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/8f/b7/f329cfdc75f3d28d12c65980e4469e2fa373f1953f5df6e370e84ea2e875/decorator-4.4.1-py2.py3-none-any.whl
Collecting pampy==0.3.0 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/98/87/c5484ec830cc014523662f34bb9ce73cc6f900a096aec7d88094b82ec0fb/pampy-0.3.0-py3-none-any.whl
Requirement already satisfied: rsa==4.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (4.0)
Collecting schedule==0.6.0 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/57/22/3a709462eb02412bd1145f6e53604f36bba191e3e4e397bea4a718fec38c/schedule-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: toml==0.10.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 8)) (0.10.0)
Requirement already satisfied: typing-extensions>=3.6.5; python_version < "3.7" in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (3.7.2)
Requirement already satisfied: multidict<5.0,>=4.5 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (4.5.2)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna-ssl>=1.0; python_version < "3.7" in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.6/site-packages (from rsa==4.0->-r requirements.txt (line 6)) (0.4.5)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.6/site-packages (from yarl<2.0,>=1.0->aiohttp==3.6.2->-r requirements.txt (line 1)) (2.8)
Installing collected packages: attrs, aiohttp, aiojobs, decorator, pampy, schedule
  Found existing installation: attrs 19.1.0
    Uninstalling attrs-19.1.0:
      Successfully uninstalled attrs-19.1.0
  Found existing installation: aiohttp 3.5.4
    Uninstalling aiohttp-3.5.4:
      Successfully uninstalled aiohttp-3.5.4
Successfully installed aiohttp-3.6.2 aiojobs-0.2.2 attrs-19.3.0 decorator-4.4.1 pampy-0.3.0 schedule-0.6.0
You are using pip version 19.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "./run.py", line 45, in <module>
    dict_user = conf_loader.read_user()
  File "/app/conf_loader.py", line 95, in read_user
    return var.read_user()
  File "/app/conf_loader.py", line 70, in read_user
    return self.toml_load(self.file_user)
  File "/app/conf_loader.py", line 41, in toml_load
    with open(path, encoding="utf-8") as f:
IsADirectoryError: [Errno 21] Is a directory: '/app/conf/user.toml'`

**Comment by HMBSbige** [comment]
@MisakaXeon 我不懂 Mac OS
你把
```
$(pwd)/user.sample.toml
$(pwd)/ctrl.sample.toml
$(pwd)/task.sample.toml
```
都替换成自己配置文件的绝对路径呗

**Comment by MisakaXeon** [comment]
> @MisakaXeon 我不懂 Mac OS
> 你把
> 
> ```
> $(pwd)/user.sample.toml
> $(pwd)/ctrl.sample.toml
> $(pwd)/task.sample.toml
> ```
> 
> 都替换成自己配置文件的绝对路径呗

已经替换成绝对路径
MacBook-Pro:bili2.0-master misaka$ docker run --rm -it \
>   -v /Users/misaka/Desktop/bili2.0-master/user.sample.toml:/app/conf/user.toml \
>   -v /Users/misaka/Desktop/bili2.0-master/ctrl.sample.toml:/app/conf/ctrl.toml \
>   -v /Users/misaka/Desktop/bili2.0-master/task.sample.toml:/app/conf/task.toml \
>   zsnmwy/bili2.0

但是报错和之前一模一样

**Comment by HMBSbige** [comment]
@MisakaXeon 破案了，Windows 和 Mac OS 的 Docker 不支持挂载文件，你想要 Mac 上用 Docker 运行本项目可能要自己想办法了

@yjqiang #266 修复了 Docker 在 Linux 的运行示例，并移除 Windows 的示例

**Comment by MisakaXeon** [comment]
@HMBSbige 好吧明白了，感谢

**Comment by yjqiang** [comment]
@zsnmwy 你来看看 Docker 这里？当初是你加上的。。。。

**Comment by MisakaXeon** [comment]
手都点错了不小心关闭了，抱歉抱歉

**Comment by MisakaXeon** [comment]
@HMBSbige 大佬我已经更换为阿里云服务器装好了docker，环境是CentOS7.6 64 Python3.7.0，还是和MAC上一样的报错，请问是哪里出了问题
[root@iZx8gymgct9u2xZ bili2.0-master]# docker run --rm -it   -v $(pwd)/user.sample.toml:/app/conf/user.toml   -v $(pwd)/ctrl.sample.toml:/app/conf/ctrl.toml   -v $(pwd)/task.sample.toml:/app/conf/task.toml   zsnmwy/bili2.0 
remote: Enumerating objects: 342, done.
remote: Counting objects: 100% (342/342), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 969 (delta 294), reused 288 (delta 246), pack-reused 627
Receiving objects: 100% (969/969), 423.32 KiB | 16.00 KiB/s, done.
Resolving deltas: 100% (666/666), completed with 53 local objects.
From https://github.com/yjqiang/bili2.0
   215a879..8caf8ea  master     -> origin/master
Updating 215a879..8caf8ea
Fast-forward
 .github/ISSUE_TEMPLATE/bug_report.md     |  29 +++++++++++++
 .gitignore                               |   2 +
 LICENSE                                  |  21 ++++++++++
 README.md                                | 102 +++++++++++++--------------------------------
 bili_console.py                          | 190 ------------------------------------------------------------------------------------
 bili_global.py                           |   1 -
 bili_sched.py                            | 133 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 bili_statistics.py                       | 302 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------
 bug                                      |  10 -----
 conf/bili.toml                           |   2 +-
 conf/ctrl.sample.toml                    |  57 +++++++++----------------
 conf/task.sample.toml                    |  72 ++++++++++++++++++++++++++++++++
 conf/txt2toml.py                         |  45 ++++++++++----------
 conf_loader.py                           |  65 ++++++++++++++++-------------
 console_cmd.py                           | 290 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 danmu/base_danmu.py                      | 194 -------------------------------------------------------------------------------------
 danmu/bili_danmu.py                      |  93 +++++++++++++++++++++++++++++++++++++++++
 danmu/bili_danmu_monitor.py              | 120 +++++++++++++++++++++++++++++++++++++++++++++++++++++
 danmu/client.py                          | 118 ++++++++++++++++++++++++++++++++++++++++++++++++++++
 danmu/conn.py                            | 181 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 danmu/monitor_danmu_raffle.py            | 154 --------------------------------------------------------------------
 danmu/raffle_handler.py                  |  26 ++++++------
 danmu/yj_monitor.py                      | 326 +++++++++++++++++++++++++++++++++++++----------------------------------------------------------------------------------------------------------
 dyn/add_colomn_joined2old_staus_table.py |  53 ------------------------
 dyn/dyn_raffle_sql.py                    |   1 +
 dyn/monitor_dyn_raffle.py                | 100 +++++++++++++++++++++++++++++---------------
 exceptions.py                            |   4 ++
 json_rsp_ctrl.py                         | 225 ++++++++++++++++++++++++++++++---------------------------------------------------------------------
 notifier.py                              | 393 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------
 printer.py                               | 233 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------
 reqs/custom.py                           |  31 ++++++++++++++
 reqs/guard_raffle_handler.py             |  19 +++++++--
 reqs/live_daily_job.py                   |  78 +++++++++++++++++------------------
 reqs/login.py                            | 105 ++++++++++++++++++++++++++++------------------
 reqs/main_daily_job.py                   |  27 +++++++++---
 reqs/manga_daily_job.py                  |  49 ++++++++++++++++++++++
 reqs/pk_raffle_handler.py                |  25 +++++++++++
 reqs/storm_raffle_handler.py             |  12 ++++--
 reqs/substance_raffle_handler.py         |  31 +++-----------
 reqs/tv_raffle_handler.py                |  70 ++++++++++++-------------------
 reqs/utils.py                            |  47 ++++++++++++++-------
 requirements.txt                         |  13 +++---
 run.py                                   | 194 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------
 substance/monitor_substance_raffle.py    |  91 +++++++++++++++++++++++++---------------
 substance/substance_raffle_sql.py        |   1 +
 support.jpeg                             | Bin 0 -> 48196 bytes
 tasks/base_class.py                      |  63 ++++++++++++++++++++++++++++
 tasks/bili_console.py                    | 329 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 tasks/custom.py                          |  79 ++++++++++++++++++++++++-----------
 tasks/dyn_raffle_handler.py              | 222 ++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------
 tasks/guard_raffle_handler.py            |  64 +++++++++++------------------
 tasks/live_daily_job.py                  | 352 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------------------------
 tasks/login.py                           |  39 ++++++++++++------
 tasks/main_daily_job.py                  | 238 +++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------------------
 tasks/manga_daily_job.py                 |  37 +++++++++++++++++
 tasks/pk_raffle_handler.py               |  44 ++++++++++++++++++++
 tasks/storm_raffle_handler.py            |  27 +++++-------
 tasks/substance_raffle_handler.py        |  43 +++++++++++--------
 tasks/tv_raffle_handler.py               | 121 ++++++++++-------------------------------------------
 tasks/utils.py                           | 309 +++++++++++++++++++++++++++-------------------------------------------------------------------------------------------------------------
 user.py                                  | 209 +++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------
 user_status.py                           | 150 ------------------------------------------------------------------
 utils.py                                 |  31 +++++++-------
 web_session.py                           | 173 +++++++++++++++++++++++++++++++++++++---------------------------------------
 64 files changed, 3899 insertions(+), 2966 deletions(-)
 create mode 100644 .github/ISSUE_TEMPLATE/bug_report.md
 create mode 100644 LICENSE
 delete mode 100644 bili_console.py
 create mode 100644 bili_sched.py
 delete mode 100644 bug
 create mode 100644 conf/task.sample.toml
 create mode 100644 console_cmd.py
 delete mode 100644 danmu/base_danmu.py
 create mode 100644 danmu/bili_danmu.py
 create mode 100644 danmu/bili_danmu_monitor.py
 create mode 100644 danmu/client.py
 create mode 100644 danmu/conn.py
 delete mode 100644 danmu/monitor_danmu_raffle.py
 delete mode 100644 dyn/add_colomn_joined2old_staus_table.py
 create mode 100644 reqs/manga_daily_job.py
 create mode 100644 reqs/pk_raffle_handler.py
 create mode 100644 support.jpeg
 create mode 100644 tasks/base_class.py
 create mode 100644 tasks/bili_console.py
 create mode 100644 tasks/manga_daily_job.py
 create mode 100644 tasks/pk_raffle_handler.py
 delete mode 100644 user_status.py
Collecting aiohttp==3.6.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c2/f7/f0ad3dbace4762fef5d80aa4124b41bf218e4c4dd6d387a86cede707d9a4/aiohttp-3.6.2-py3-none-any.whl (441kB)
    100% |████████████████████████████████| 450kB 1.1MB/s 
Collecting aiojobs==0.2.2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/a7/8e/1d41d21e7cd09d744921490be99a9e2cfa498ae1af36b9c3ee0c3395d2c9/aiojobs-0.2.2-py3-none-any.whl
Collecting attrs==19.3.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting pampy==0.3.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/98/87/c5484ec830cc014523662f34bb9ce73cc6f900a096aec7d88094b82ec0fb/pampy-0.3.0-py3-none-any.whl
Requirement already satisfied: rsa==4.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (4.0)
Collecting schedule==0.6.0 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/57/22/3a709462eb02412bd1145f6e53604f36bba191e3e4e397bea4a718fec38c/schedule-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: toml==0.10.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 7)) (0.10.0)
Requirement already satisfied: idna-ssl>=1.0; python_version < "3.7" in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.5; python_version < "3.7" in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (3.7.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: multidict<5.0,>=4.5 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (4.5.2)
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.6/site-packages (from rsa==4.0->-r requirements.txt (line 5)) (0.4.5)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.6/site-packages (from idna-ssl>=1.0; python_version < "3.7"->aiohttp==3.6.2->-r requirements.txt (line 1)) (2.8)
Installing collected packages: attrs, aiohttp, aiojobs, pampy, schedule
  Found existing installation: attrs 19.1.0
    Uninstalling attrs-19.1.0:
      Successfully uninstalled attrs-19.1.0
  Found existing installation: aiohttp 3.5.4
    Uninstalling aiohttp-3.5.4:
      Successfully uninstalled aiohttp-3.5.4
Successfully installed aiohttp-3.6.2 aiojobs-0.2.2 attrs-19.3.0 pampy-0.3.0 schedule-0.6.0
You are using pip version 19.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "./run.py", line 45, in <module>
    dict_user = conf_loader.read_user()
  File "/app/conf_loader.py", line 95, in read_user
    return var.read_user()
  File "/app/conf_loader.py", line 70, in read_user
    return self.toml_load(self.file_user)
  File "/app/conf_loader.py", line 41, in toml_load
    with open(path, encoding="utf-8") as f:
IsADirectoryError: [Errno 21] Is a directory: '/app/conf/user.toml'

**Comment by HMBSbige** [comment]
@MisakaXeon 你别照着示例直接复制啊，自己替换配置文件的路径啊

我建议你还是自己学习一下 Docker 再来使用吧

**Comment by MisakaXeon** [comment]
@HMBSbige 感谢大佬的指点，仔细研究了一下docker原理及命令，发现的确是路径问题，少了一个conf，然后把后面默认文件改成修改好的文件，已经成功在centos和mac上运行了，这是我修改后的命令

docker run --rm -it \
  -v $(pwd)/conf/user.toml:/app/conf/user.toml \
  -v $(pwd)/conf/ctrl.toml:/app/conf/ctrl.toml \
  -v $(pwd)/conf/task.toml:/app/conf/task.toml \
  zsnmwy/bili2.0

这是在centos上成功运行的截图
<img width="1680" alt="QQ20200204-175156@2x" src="https://user-images.githubusercontent.com/49719364/73735129-bdd9bd80-4779-11ea-8f46-3b33337c5daf.png">
<img width="1680" alt="QQ20200204-180758@2x" src="https://user-images.githubusercontent.com/49719364/73735173-cf22ca00-4779-11ea-8b13-298f160ee3dd.png">

这是在mac上成功运行的截图
<img width="1543" alt="QQ20200204-175458@2x" src="https://user-images.githubusercontent.com/49719364/73735645-920b0780-477a-11ea-8a21-ce5d7332bfab.png">
<img width="1373" alt="QQ20200204-181531@2x" src="https://user-images.githubusercontent.com/49719364/73735698-a6e79b00-477a-11ea-9729-f4f181ac37a7.png">
<img width="1040" alt="QQ20200204-175644@2x" src="https://user-images.githubusercontent.com/49719364/73735798-c7aff080-477a-11ea-8963-fe7f73d8a1a9.png">
再次感谢！！！

**Comment by yjqiang** [comment]
你们说的我也看不懂。。。不过看起来可以 close this issue 了

**Comment by MisakaXeon** [comment]
emmmm对的，至少mac和linux上运行的问题已经解决了

**Comment by yjqiang** [comment]
@HMBSbige 你呢？你意下如何？

**Comment by HMBSbige** [comment]
昨天换成绝对路径也不行我以为 Mac 和 Windows 一样，既然没什么问题就 close 吧
