### ISSUE TITLE
主站功能 登录 观看 /风纪委员失效 是否为B站更换接口或者B站缓存炸了

### ISSUE THREAD

**Issue by azalaza** [yjqiang/bili2.0#267]
主站功能 在大约4天前开始，登录和观看视频每天都是未完成 看经验记录 每天只自动完成了转发功能 手动登录和观看视频都可以完成 登录和转发是否更换了接口 风纪委员不重启脚本 也不会自动审核！

**Comment by yjqiang** [comment]
观看视频可能是api问题

**Comment by yjqiang** [comment]
不管怎么样，观看视频接口的确老了，我更新并测试了新接口

**Comment by yjqiang** [comment]
其他的估计就是非 api 问题了

**Comment by yjqiang** [comment]
没有其他人汇报这个问题。估计就是其他非api问题

**Comment by popo-bear** [comment]
找客服申诉，是破站在抽风。我手工挂这个经验也这样。
客服开始说我来着，但是我是手工的，视频都看完了，记录显示已看过，挂机的视频1秒钟或0秒钟。技术人员可能对此异议。
