### ISSUE TITLE
暂停XXXXX,等待RESUME指令 

### ISSUE THREAD

**Issue by zhz1237ok** [yjqiang/bili2.0#269]
![image](https://user-images.githubusercontent.com/38283893/74005735-d5e95100-49b4-11ea-85a2-14233ff147c8.png)

这个正常吗？

**Comment by yjqiang** [comment]
你设置了休眠或者403了啊  正常

**Comment by zhz1237ok** [comment]
> 你设置了休眠或者403了啊 正常

![image](https://user-images.githubusercontent.com/38283893/74006992-3463fe80-49b8-11ea-9d3f-0f88783e9a84.png)
现在是下午两点多，过了休眠时间，所以是我的VPS被B站封IP了？还是进小黑屋了

**Comment by zhz1237ok** [comment]
我靠，我从截图才发现，服务器时间不一样，草

**Comment by yjqiang** [comment]
有唤醒就正常

**Comment by zhz1237ok** [comment]
已解决
rm -rf /etc/localtime   
ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

**Comment by yjqiang** [comment]
2333

**Comment by zhz1237ok** [comment]
细思极恐，我以前被封号说不定就是因为这时间不一样，半夜开着才被B封号，平常挂在服务器也没去看过，今天上去好奇看了一眼，发现在暂停
