### ISSUE TITLE
不识别弹幕进行参与舰长抽奖

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#27]
![Image](https://i.imgur.com/B46wfML.jpg)![Image](https://i.imgur.com/pUrRQtZ.jpg)
bili2.0和bili-live-tools的配置文件没写错房间号码，但是没有识别和参与抽奖

**Comment by yjqiang** [comment]
最新版？

**Comment by rabbit2rabbit** [comment]
fine,it's blame me .i will close myself

**Comment by rabbit2rabbit** [comment]
这次证实了，43分一个房间有两个舰长抽奖，监控检测到了，弹幕发了但是live-tools并没有参与到抽奖，没留下截图

**Comment by yjqiang** [comment]
存在过了情况 可能是收到了但是发现重复raffleid 自动忽略了

**Comment by yjqiang** [comment]
这是断线自动重连机制 先切断后重连
