### ISSUE TITLE
风纪委员会自动投票失效

### ISSUE THREAD

**Issue by 2604237845** [yjqiang/bili2.0#270]
2.6号还好好的，昨天开始就失效了，显示本次未获取到案件，实际是有案件的。。。
![1](https://user-images.githubusercontent.com/54972064/74080548-01853d80-4a80-11ea-929a-043a1b4c7c3a.png)
![2](https://user-images.githubusercontent.com/54972064/74080549-077b1e80-4a80-11ea-9a06-859d361d53d3.png)

**Comment by 2604237845** [comment]
尝试重启也不行

**Comment by yjqiang** [comment]
那就只能测试了  私信我qq  写上你的b站账号密码吧

**Comment by 2604237845** [comment]
大佬我没有你的QQ ，刚刚测试了一个新号，发现没有问题，但是个别账号有问题，我在测试测试...晚点来回复！

**Comment by yjqiang** [comment]
你可以把这几个api 结果打印，https://github.com/yjqiang/bili2.0/blob/master/reqs/main_daily_job.py#L5

**Comment by 2604237845** [comment]
> 你可以把这几个api 结果打印，https://github.com/yjqiang/bili2.0/blob/master/reqs/main_daily_job.py#L5

经测试发现极个别用户不知名原因导致获取不到案件，之后我尝试删除账号重新登陆发现恢复了正常，目前没有问题了，谢谢大佬！
