### ISSUE TITLE
B站好像把辣条分成三个一组了，不能手动大量送辣条了

### ISSUE THREAD

**Issue by 526462712** [yjqiang/bili2.0#272]
昨天重新跑了一天脚本，今天发现背包的辣条全都是3个一组，之前的脚本领取的辣条都是同一天的在一个分组

![image](https://user-images.githubusercontent.com/34618949/74302626-191b3980-4d92-11ea-82fb-d6730fbabd6d.png)
![image](https://user-images.githubusercontent.com/34618949/74302647-2afcdc80-4d92-11ea-878e-3babf669ccb2.png)

一个朋友昨天开始跑脚本也是一样的情况
![image](https://user-images.githubusercontent.com/34618949/74302664-40720680-4d92-11ea-80a8-4c972bafe218.png)

现在需要一次送大量辣条，不同组一个一个点起来很麻烦，不知道是不是B站的问题。

**Comment by zhz1237ok** [comment]
没有31天期限的辣条，这是钓鱼辣条，你的号不能要了，要没了

**Comment by yjqiang** [comment]
这是测试的辣条  问过其他人应该没啥钓鱼的  就是测试

**Comment by popo-bear** [comment]
情人节活动的特殊礼物《怦然心动》，抽到就是3根辣条一组，有效期31天。

**Comment by yjqiang** [comment]
> 情人节活动的特殊礼物《怦然心动》，抽到就是3根辣条一组，有效期31天。

还以为是之前的测试呢……  b站咋抽风搞这个？

**Comment by sr1y7** [comment]
今天我也挂到这种钓鱼辣条了（手动滑稽）

**Comment by sr1y7** [comment]
今天我也挂到钓鱼辣条了（手动滑稽）
虽然能堆叠了，但是还是存放31天，获得时3个一组（一般的辣条，每次抽奖要么1个要么5个）
