### ISSUE TITLE
启动卡住

### ISSUE THREAD

**Issue by Windlc2019** [yjqiang/bili2.0#273]
**截图或者视频或者报错文字**
![QQ图片20200213105451](https://user-images.githubusercontent.com/53964405/74397400-8214b700-4e4f-11ea-93cf-edff6e71f784.png)

**必要的系统信息描述等**
python 版本以及系统版本信息
Python 3.8.1 系统Windows 10 1809 LTSC

**最近何时更新的脚本**
几小时前

**最后确认**
- [√] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [√] 我代码上次更新时间距今没有超过 2 个月以上
- [√] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [√] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
本机正常，你如果会 python 的话在login部分打断点就行

**Comment by Windlc2019** [comment]
不会Python... 打断点是什么意思呢

**Comment by yjqiang** [comment]
你试试不用cmd，直接双击试试看

**Comment by yjqiang** [comment]
卡住可能是你cmd光标卡住了、网络很差。第一种情况下把光标远离cmd，输入代码运行，第二种情况换个网。除此之外只能慢慢找卡的地方了

**Comment by Windlc2019** [comment]
![QQ截图20200213134556](https://user-images.githubusercontent.com/53964405/74405111-4a196e00-4e67-11ea-87d5-7b3c358c15b0.png)
我找到个跟我一样的 是bug吗
（网络切换了也不行）

**Comment by yjqiang** [comment]
> ![QQ截图20200213134556](https://user-images.githubusercontent.com/53964405/74405111-4a196e00-4e67-11ea-87d5-7b3c358c15b0.png)
> 我找到个跟我一样的 是bug吗
> （网络切换了也不行）

你这个不一定是bug，等下我看看怎么测试

**Comment by yjqiang** [comment]
[login.zip](https://github.com/yjqiang/bili2.0/files/4196904/login.zip)
解压后替换掉 tasks/login.py 文件，重新运行

**Comment by Windlc2019** [comment]
现在是这样子卡住了
![QQ截图20200213151136](https://user-images.githubusercontent.com/53964405/74410074-2bb96f80-4e73-11ea-9bdd-ce9f1be99a43.png)

**Comment by yjqiang** [comment]
[login.zip](https://github.com/yjqiang/bili2.0/files/4197043/login.zip)
还是替换

**Comment by Windlc2019** [comment]
和之前一样不动

![无标题](https://user-images.githubusercontent.com/53964405/74416163-aab4a500-4e7f-11ea-8bb7-053babe40fc9.png)

**Comment by yjqiang** [comment]
[login.zip](https://github.com/yjqiang/bili2.0/files/4197279/login.zip)
解压后替换掉 reqs/login.py 文件，重新运行

**Comment by Windlc2019** [comment]
现在是直接闪退... 但我截到图了
![无标题](https://user-images.githubusercontent.com/53964405/74438708-b6b35d80-4ea5-11ea-854d-1a32424df164.png)

**Comment by yjqiang** [comment]
解压后替换掉 reqs/login.py 文件，重新运行

**Comment by Windlc2019** [comment]
确实看错了 但还是花式闪退
![无标题](https://user-images.githubusercontent.com/53964405/74441724-4c9db700-4eab-11ea-9b8d-98d2de5c45b4.png)

**Comment by yjqiang** [comment]
看着这张图的代码，你再跟我说一遍***几小时前***更新？

**Comment by Windlc2019** [comment]
是我笨比了 我把网上的和git的混一块了 我重新clone了一份 能运行了 麻烦大佬了
