### ISSUE TITLE
最新版程序+最新版风暴代码，运行中穿插出现Task exception was never retrieved......

### ISSUE THREAD

**Issue by 793145170** [yjqiang/bili2.0#274]
今天更新了程序之后用1.31的风暴代码无限出现这种情况，然后又拿到了最新的风暴代码，测试之后会穿插出现这种情况。

![QQ图片20200214233136](https://user-images.githubusercontent.com/38856864/74544680-7f66ae80-4f82-11ea-955b-446d8720d849.png)

python 3.8.1

两个小时之前下载的程序

**最后确认**
- [√ ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ √] 我代码上次更新时间距今没有超过 2 个月以上
- [ √] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ √] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by 793145170** [comment]
![QQ图片20200214233834](https://user-images.githubusercontent.com/38856864/74545028-251a1d80-4f83-11ea-9b03-5f0c7db71841.png)
这会高峰期复现概率又高了

**Comment by yjqiang** [comment]
这个是tv api  具体问题还要慢慢查

**Comment by yjqiang** [comment]
,"gift":[{"raffleId":711747,"type":"GIFT_30436","from_user":{"uid":0,"uname":"青空与莫","face":"http://i2.hdslb.com/bfs/face/4d1e2aa3e331e1a260681747d5ad803abffd9b67.jpg"},"time_wait":89,"time":149,"max_time":180,"status":1,"sender_type":0,"asset_icon":"http://s1.hdslb.com/bfs/live/004741078e1c394423ffa631a321229f95db4b56.png","asset_animation_pic":"http://i0.hdslb.com/bfs/live/746a8db0702740ec63106581825667ae525bb11a.gif","thank_text":"感谢\u003c%青空与莫%\u003e 赠送的1219蘑菇方舟","weight":0,"gift_id":30436},{"raffleId":711751,"type":"GIFT_30452","from_user":{"uid":0,"uname":"1219丶S君","face":"http://i0.hdslb.com/bfs/face/9e47d0bae32d59715ba30ec8aad0a8ed563c5196.jpg"},"time_wait":48,"time":108,"max_time":120,"status":1,"sender_type":0,"asset_icon":"http://s1.hdslb.com/bfs/live/380bcd708da496d75737c68930965dd67b82879d.png","asset_animation_pic":"https://i0.hdslb.com/bfs/live/7e47e9cfb744acd0319a4480e681258ce3a611fe.gif","thank_text":"感谢\u003c%1219丶S君%\u003e 赠送的摩天大楼","weight":0,"gift_id":30452}]}}

**Comment by yjqiang** [comment]
你是用了谁的key？

**Comment by zhoor120** [comment]
> 你是用了谁的密钥？



> 你是用了谁的密钥？

你好 
我看奖励日志只有小电视的辣条而没有上舰那些勋章亲密度奖励
请问是还有哪里开关没开吗？
join_guard_raffle = -1  # 舰队，（task这里已经设置了）

**Comment by yjqiang** [comment]
> 
> 
> 
> > 你是用了谁的密钥？
> 
> 
> 
> > 你是用了谁的密钥？
> 
> 你好 
> 我看奖励日志只有小电视的辣条而没有上舰那些勋章亲密度奖励
> 请问是还有哪里开关没开吗？
> join_guard_raffle = -1  # 舰队，（task这里已经设置了）
> 

自己开新的issue

**Comment by 793145170** [comment]
这个除了风暴都没开。

**Comment by yjqiang** [comment]
没有再复现  可能就是奇怪东西吧
