### ISSUE TITLE
E大用法

### ISSUE THREAD

**Issue by DZB1230909** [yjqiang/bili2.0#275]
买了那个E大的要怎么用？怎么改代码，官网写得不是很清楚

**Comment by yjqiang** [comment]
> 买了那个E大的要怎么用？怎么改代码，官网写得不是很清楚

我也不知道……

**Comment by yjqiang** [comment]
我问问吧

**Comment by yjqiang** [comment]
yjmonitor_tcp_addr = "tcp://api.expublicsite.com:23335"
key 你买的那个
