### ISSUE TITLE
使用自建监控报错

### ISSUE THREAD

**Issue by Womsxd** [yjqiang/bili2.0#276]
**再确认一次 issue 题目**
请记得把 issue 标题改成问题描述的概述，而不是简单的一句话，《电脑开不了了》、《闪退了》、《救命啊》这些

**问题描述**
git pull升级后报错，包括其他设备上的最新版也报错，翻了下更新，是开源版的监控服务端没有更新

**截图或者视频或者报错文字**
Task exception was never retrieved              future: <Task finished name='Task-1898' coro=<Client._job_main() done, defined at /data/data/com.termux/files/usr/lib/python3.8/site-packages/danmu_abc/client.py:63> exception=KeyError('other_raffle_data')>                                  Traceback (most recent call last):                File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/danmu_abc/client.py", line 65, in _job_main                                     if not await self._one_read():                File "/data/data/com.termux/files/home/bili2.0/danmu/yj_monitor_abc/yj_monitor.py", line 60, in _one_read                                         if not self.handle_danmu(json_body['data']):  File "/data/data/com.termux/files/home/bili2.0/danmu/yj_monitor.py", line 28, in handle_danmu     'guard': [data['other_raffle_data']]
KeyError: 'other_raffle_data'

**必要的系统信息描述等**
python 版本以及系统版本信息
Python3.8.0
安卓 Termux

**最近何时更新的脚本**
5分钟前

**最后确认**
- [ √] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ √] 我代码上次更新时间距今没有超过 2 个月以上
- [√ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ √] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
更新了啊 https://github.com/yjqiang/YjMonitor/commit/5358430b5ab17b92c82b51fe47746ad94a736f78

**Comment by Womsxd** [comment]
排查出来了，监控的节点服务器没有更新，转发的服务器更新了
