### ISSUE TITLE
双端任务无法完成

### ISSUE THREAD

**Issue by Lex573** [yjqiang/bili2.0#278]
双端任务无法完成 要手动进入一次直播间才会完成 进入网页端完成电脑 进入app完成客户端

**Comment by yjqiang** [comment]
我这里应该正常，明天测试看看

**Comment by Billyzou0741326** [comment]
## Web (GET)
api.live.bilibili.com/xlive/web-room/v1/index/getInfoByUser?room_id=1

## App (GET)
api.live.bilibili.com/xlive/app-room/v1/index/getInfoByUser?
| param key         | param value   |
|-------------------|---------------|
| access_key        |               |
| actionKey         |               |
| appKey            |               |
| build             |               |
| channel           | bili          |
| device            | android       |
| mobi_app          | android       |
| platform          | android       |
| room_id           |               |
| statistics        |               |
| ts                |               |
| sign              |               |

**Comment by yjqiang** [comment]
@Billyzou0741326 为啥整了个这个？

**Comment by Billyzou0741326** [comment]
我这个跟心跳一起发之后才过的双端 明天再测一下吧 现在不是很确定…

**Comment by yjqiang** [comment]
> 我这个跟心跳一起发之后才过的双端 明天再测一下吧 现在不是很确定…

似乎点一次就行了，话说你咋试出来的？

**Comment by Billyzou0741326** [comment]
不是我发现的hhh 听说了之后用小号测试了下看到完成了 不过这不一定是唯一可行的组合

**Comment by yjqiang** [comment]
@Billyzou0741326 只发送一次新的那俩请求就可以了。

**Comment by Billyzou0741326** [comment]
ok 不用重复发送太好了

**Comment by popo-bear** [comment]
双端已经修复了，只是启动成迷，有时候偷偷摸摸就成了，有时候零点到16点都没有完成，重启两次程序完成了。

摸不着头脑。
