### ISSUE TITLE
建议不要引入Matplotlib

### ISSUE THREAD

**Issue by YRxCN** [yjqiang/bili2.0#28]
粗略看了一下，Matplotlib在本项目中仅用作颜色相关操作，有点大材小用。并且该库过于庞大，与GUI相关程序包依赖过多，极容易出现问题。个人觉得还不如回退至之前的Webcolors= =

**Comment by yjqiang** [comment]
暂时不想改回去了，可能会自己复现matplotlib这个库吧

**Comment by yjqiang** [comment]
主项目已经移除  之后测试通过后就发过来

**Comment by YRxCN** [comment]
> 主项目已经移除 之后测试通过后就发过来

唔，还没同步过来吗= =

**Comment by yjqiang** [comment]
> > 主项目已经移除 之后测试通过后就发过来
> 
> 唔，还没同步过来吗= =

还有一些事情要做

**Comment by yjqiang** [comment]
@YRxCN 已经完全移除
