### ISSUE TITLE
直播分区疑似关闭

### ISSUE THREAD

**Issue by GOOD-AN** [yjqiang/bili2.0#282]
7号数据无法连接到房间，而无限重试。

**Comment by yjqiang** [comment]
重启能解决么？

**Comment by zhz1237ok** [comment]
作为对比，我这边使用正常

**Comment by GOOD-AN** [comment]
嗯。。。今天白天正常，晚上我再看看

**Comment by popo-bear** [comment]
> 重启能解决么？

时不时的，不是很频繁，现在看就是大面积的7号数据链获取不到直播间号循环，没时间可以不管。

好像是新冠学习频道

**Comment by popo-bear** [comment]
> 嗯。。。今天白天正常，晚上我再看看

重启后如果没有新的刺激不是启动的。估计是那个没改房间分区就开播了。 7号是新冠学习频道，已经废了。
