### ISSUE TITLE
token可能过期 

### ISSUE THREAD

**Issue by houxinxin** [yjqiang/bili2.0#283]
今天上去突然发现提示token可能过期是什么问题了 刚更新了一下
D:\bili2.0-master>python run.py
[2020-02-24 21:05:50] check_results:
# <class 'tasks.login.LoginTask'>
# ((-2, None),)
[2020-02-24 21:05:50] token可能过期 (用户id:0 名字:*****)
json_rsp {'message': 'Account is not logined.', 'ts': 1582549550, 'code': -101}

**Comment by yjqiang** [comment]
能正常运行下去就正常

**Comment by houxinxin** [comment]
> 能正常运行下去就正常

无法正常运行 到这里后就卡住了

**Comment by yjqiang** [comment]
@houxinxin 最新版代码？

**Comment by houxinxin** [comment]
> @houxinxin 最新版代码？

嗯 是的 除了conf没有替换 其他都替换了

**Comment by houxinxin** [comment]
> @houxinxin 最新版代码？

下载的代码包是2/21号的日期

**Comment by yjqiang** [comment]
我这边正常，暂时没有时间细调，你重启不行就只有等我考研复试结束了。

**Comment by houxinxin** [comment]
> 我这边正常，暂时没有时间细调，你重启不行就只有等我考研复试结束了。

哦 大佬你先忙 哈哈
