### ISSUE TITLE
建议风纪投票增加时间设置

### ISSUE THREAD

**Issue by shibeta** [yjqiang/bili2.0#285]
现在脚本挂机是凌晨处理案件，这段时间的投票几乎全是脚本，处理结果很糟糕，很多正常评论被删除。
所以建议风纪脚本可以自定义时间段执行，默认下午执行的话，用于判断的数据更有说服力。
同时，很多b站用户意识到有脚本参与，也出现了“凌晨不要参与众裁，全是脚本”这样的言论，默认凌晨参与众裁对脚本隐蔽不利。

**Comment by yjqiang** [comment]
不会这么做，配置文件已经够复杂了，如果有需要，建议自己改，任务的定时由`schedule`控制，你可以在`run.py`里面自由定制。
