### ISSUE TITLE
关于本程序及附属监控的一些疑问

### ISSUE THREAD

**Issue by shoucandanghehe** [yjqiang/bili2.0#287]
1.本程序是要配合使用https://github.com/yjqiang/YjMonitor/  才能高效率？
2.https://github.com/yjqiang/YjMonitor/  监控对服务器性能要求大概有多高？
3.监控服务器需要监控多少房间才能做到基本全站覆盖？
希望大佬能解答一下

**Comment by yjqiang** [comment]
99.5%要3w房间，每4000房间需要1M带宽。内存这里没统计。

**Comment by shoucandanghehe** [comment]
> 99.5%要3w房间，每4000房间需要1M带宽。内存这里没统计。

4000房间1m带宽倒是不高，不过如果用一台性能足够的机子多开几个挂满3w房间会不会有被B站屏蔽IP的风险？

**Comment by yjqiang** [comment]
> > 99.5%要3w房间，每4000房间需要1M带宽。内存这里没统计。
> 
> 4000房间1m带宽倒是不高，不过如果用一台性能足够的机子多开几个挂满3w房间会不会有被B站屏蔽IP的风险？

不会的

**Comment by shoucandanghehe** [comment]
> > > 99.5%要3w房间，每4000房间需要1M带宽。内存这里没统计。
> > 
> > 
> > 4000房间1m带宽倒是不高，不过如果用一台性能足够的机子多开几个挂满3w房间会不会有被B站屏蔽IP的风险？
> 
> 不会的

明白了，谢谢大佬解答
