### ISSUE TITLE
pip安装requirements时出错

### ISSUE THREAD

**Issue by feilongproject** [yjqiang/bili2.0#288]
在我输入 pip install -r requirements.txt时，输出错误，请问怎么解决
Collecting aiohttp==3.6.2 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement aiohttp==3.6.2 (from -r requi)
No matching distribution found for aiohttp==3.6.2 (from -r requirements.txt (line 1))

**Comment by yjqiang** [comment]
手动安装吧。`pip install aiohttp`
