### ISSUE TITLE
勋章投递和清理过期礼物不协同，导致浪费

### ISSUE THREAD

**Issue by Skimige** [yjqiang/bili2.0#289]
**问题描述**
（刚部署一两天，查看日志检查功能运行情况，今天上午）
过期礼物清理和勋章投递功能存在不协同问题，即便勋章投递已经先行使用了 2000 辣条，后续过期礼物清理的上限是否投满疑似没有更新

**截图或者视频或者报错文字**
注：所有【某房间】和【某主播】均为同一 up
```
正在投递勋章
# 送给房间  【某房间】  礼物: 辣条X2000
[2020-03-01 09:00:17] 勋章 【某主播】 本次提升2000.0亲密度，离上限还剩0.0 (用户id:0 名字:@@@) // 这里已经投满了这个勋章的亲密度，且正确提示上限 0
发现即将过期的礼物
正在清理过期礼物到用户勋章
# 送给房间  【某房间】  礼物: 辣条X1343 // 投到了刚才已经投满的勋章
# 送给房间  【某房间】  礼物: 亿圆X16
[2020-03-01 09:00:18] 勋章 【某主播】 本次提升1503.0亲密度，离上限还剩497.0 (用户id:0 名字:@@@) // 明明刚才上限已经满了，疑似没有正确更新
```

**必要的系统信息描述等**
Python 3.8.1 running on Termux

**最近何时更新的脚本**
https://github.com/yjqiang/bili2.0/commit/739cf314550b4d7452f7092304fa1bad5b68ff5e

**最后确认**
- [x] 我仔细看了requirements.txt，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

---

题外话：本项目有交流群吗？如有的话可否邀请进群？

**Comment by yjqiang** [comment]
那应该是b站api不同步，投递之前会重新获取勋章状态，可能之前投递后，b站没有及时刷新数据，导致api返回结果并不是最新的状况。

**Comment by yjqiang** [comment]
https://github.com/Dawnnnnnn/bilibili-live-tools/wiki#8%E5%85%B3%E4%BA%8E%E7%BE%A4
目前和这个人一起共用群，普通 bug 可以 issue 就行，我个人很少看群消息。

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/1f36730546300f03297b2975d03bcf146997f243/tasks/live_daily_job.py#L270
这是勋章部分核心代码。

**Comment by Skimige** [comment]
> 那应该是b站api不同步，投递之前会重新获取勋章状态，可能之前投递后，b站没有及时刷新数据，导致api返回结果并不是最新的状况。

那我再观察一天吧，确认一下是否是个别情况

**Comment by Skimige** [comment]
仍然存在问题，看来这里得改改
```正在投递勋章
# 送给房间  [A]  礼物: 辣条X2000
[2020-03-02 09:00:32] 勋章 [A] 本次提升2000.0亲密度，离上限还剩0.0 (用户id:0 名字:[REDACTED])
发现即将过期的礼物
正在清理过期礼物到用户勋章
# 送给房间  [A]  礼物: 辣条X2000
[2020-03-02 09:00:33] 勋章 [A] 本次提升2000.0亲密度，离上限还剩0.0 (用户id:0 名字:[REDACTED])
# 送给房间   [B]   礼物: 辣条X789
# 送给房间   [B]   礼物: 亿圆X20
[2020-03-02 09:00:33] 勋章 [B] 本次提升989.0亲密度，离上限还剩1011.0 (用 户id:0 名字:[REDACTED])
```

**Comment by yjqiang** [comment]
你试试加一个sleep，sleep 10s看看

**Comment by pjy612** [comment]
其实还有一个 
自动投喂佩戴的勋章
和投喂固定人 如果 刚好有一样的 也会浪费

**Comment by yjqiang** [comment]
> 其实还有一个
> 自动投喂佩戴的勋章
> 和投喂固定人 如果 刚好有一样的 也会浪费

`正在清理过期礼物到用户勋章`这里逻辑是过期那里的了

**Comment by Skimige** [comment]
```
正在投递勋章
# 送给房间  [A]  礼物: 辣条X1990
[2020-03-03 10:05:33] 勋章 [A] 本次提升1990.0亲密度，离上限还剩0.0 (用户id:0 名字:[REDACTED])
发现即将过期的礼物
正在清理过期礼物到用户勋章
正在投递勋章
[2020-03-03 10:05:44] 勋章 [A] 本日亲密度上限还剩0 (用户id:0 名字:[REDACTED])
# 送给房间   [B]   礼物: 辣条X2000
[2020-03-03 10:05:44] 勋章 [B] 本次提升2000.0亲密度，离上限还剩0.0 (用户id:0 名字:[REDACTED])
# 送给房间 [C]  礼物: 辣条X1552
# 送给房间 [C]  礼物: 亿圆X22
[2020-03-03 10:05:44] 勋章 [C] 本次提升1772.0亲密度，离上限还剩223.0 (用户id:0 名字:[REDACTED])
```

貌似好了（顺带回楼上 @pjy612 一句，我没开那个功能 = = 但是如果有问题的话你也可以加一个试试），不过被 Python 空格缩进坑了一手：
习惯性 Tab 换了照着上面抄了一句 `await asyncio.sleep(10)` 然后 `pm2 restart {id}` 结果报了一天的 `inconsistent use of tabs and spaces in indentation`（

**Comment by yjqiang** [comment]
@Skimige 加在 https://github.com/yjqiang/bili2.0/blob/1f36730546300f03297b2975d03bcf146997f243/tasks/live_daily_job.py#L271 了么

**Comment by Skimige** [comment]
> @Skimige 加在
> 
> https://github.com/yjqiang/bili2.0/blob/1f36730546300f03297b2975d03bcf146997f243/tasks/live_daily_job.py#L271
> 
> 之后了么

是加在这两行之间的

**Comment by yjqiang** [comment]
那你pr一下吧，sleep时间估计7s就够了，凑个整77777777

**Comment by cicada1208** [comment]
不好意思!想请问一下，勋章投递和清理过期礼物，只会投递辣条跟亿圆吗，B坷垃会不会也投出去?
谢谢

**Comment by yjqiang** [comment]
> 不好意思!想请问一下，勋章投递和清理过期礼物，只会投递辣条跟亿圆吗，B坷垃会不会也投出去?
> 谢谢

请自己开一个新issue
