### ISSUE TITLE
能不能把所有礼物不管是否过期都一起送到指定房间

### ISSUE THREAD

**Issue by 18395595314** [yjqiang/bili2.0#29]
![image](https://user-images.githubusercontent.com/41237775/46388572-9b581000-c6ff-11e8-9798-747015d5c862.png)

**Comment by 18395595314** [comment]
这样改对吗??

**Comment by 18395595314** [comment]
我期望是脚本一启动就全送完,而且是多个账号

**Comment by yjqiang** [comment]
是的，把过期时间设置很小，就会全送出。

**Comment by yjqiang** [comment]
但是之前出现过bug，https://github.com/yjqiang/bili2.0/issues/4
