### ISSUE TITLE
开启后反复提示几乎相同内容

### ISSUE THREAD

**Issue by feilongproject** [yjqiang/bili2.0#293]
在运行了run.py之后会一直有类似内容提示
`
_____________________________________                                                   is_dyn_raffle: 59580012 code: 0                                                         59580012 {"a_id":100,"from_cfg":{"audit_level":100,"from":"join_examination"}}
`
请问这是什么原因？又或者这是来干什么用的？

**Comment by yjqiang** [comment]
你开启了动态抽奖  关掉即可
