### ISSUE TITLE
run.py打开闪退：UnicodeDecodeError: 'utf-8' codec can't decode。。。

### ISSUE THREAD

**Issue by zengkuankuan** [yjqiang/bili2.0#294]
![QQ图片20200304125238](https://user-images.githubusercontent.com/53440794/75846475-6b8ec980-5e17-11ea-8fa2-a3b93e061bee.png)

瞬间截的屏

**Comment by yjqiang** [comment]
user.toml 里面有除中英文之外字符吧，反正不合法字符，你拿vs code修改，不要用记事本这些。
