### ISSUE TITLE
勋章投递和清理过期礼物的礼物种类

### ISSUE THREAD

**Issue by cicada1208** [yjqiang/bili2.0#295]
**问题描述**
不好意思!想请问一下，勋章投递和清理过期礼物，只会投递辣条跟亿圆吗，B坷垃会不会也投出去?
谢谢

**必要的系统信息描述等**
python 版本 3.6.6

**最近何时更新的脚本**
2020/03/03

**Comment by yjqiang** [comment]
勋章b克拉不会送的  除非即将过期了  这时候b克拉会送

**Comment by yjqiang** [comment]
辣条和亿元会送  其他的也有一些会送的

**Comment by cicada1208** [comment]
> 勋章b克拉不会送的 除非即将过期了 这时候b克拉会送

了解，谢谢回复
