### ISSUE TITLE
run.py运行不了

### ISSUE THREAD

**Issue by qingfeng52** [yjqiang/bili2.0#296]
我也不知道那错了，帮忙看看
https://pic.downk.cc/item/5e5f55f398271cb2b8f55df0.jpg

**Comment by yjqiang** [comment]
没文件ctrl.toml

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
第4条

**Comment by qingfeng52** [comment]
> 没文件ctrl.toml

谢谢已解决
