### ISSUE TITLE
脚本无法进行手机号验证

### ISSUE THREAD

**Issue by Womsxd** [yjqiang/bili2.0#299]
**再确认一次 issue 题目**
请记得把 issue 标题改成问题描述的概述，而不是简单的一句话，《电脑开不了了》、《闪退了》、《救命啊》这些

**问题描述**
尽量详细叙述发生时间等
今天启动B站的时候发现账号被风控(因为代理IPhhhh)了，然后APP这边验证后正常登入，脚本无法登入需要手机验证
**截图或者视频或者报错文字**
截图请务必把名字等信息打码
08:06:18] 登录失败,错误信息为:{'ts': 1583366779, 'code': 0, 'data': {'status': 1, 'url': 'https://passport.bilibili.com/mobile/verifytel_h5.html?mid=UID&tel=手机号&email=邮箱&source=2&keepTime=0&appId=878&subId=0&ticket=1'}}
**必要的系统信息描述等**
python 版本以及系统版本信息

**最近何时更新的脚本**
几天前还是几小时前
最新版
**最后确认**
- [√ ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [√ ] 我代码上次更新时间距今没有超过 2 个月以上
- [√ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [√ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
没办法的，可以试试网页登陆一下解除状态，尽量挂机和常登陆ip在一起。
