### ISSUE TITLE
关于风纪任务处理时间过于集中

### ISSUE THREAD

**Issue by heatded** [yjqiang/bili2.0#300]
最近一段时间随便点进一个小黑屋的文章公告，底下都有举报脚本风纪的评论。。。
大佬能否加一个随机延迟几小时处理？或者大幅加长每个投票间隔。。
感谢大佬🙏

**Comment by yjqiang** [comment]
你是说投票的案件之间间隔么？比如你8:30:00投了一个案件，然后8:30:01又一个，8:30:02又一个新案件？

**Comment by heatded** [comment]
> 你是说投票的案件之间间隔么？比如你8:30:00投了一个案件，然后8:30:01又一个，8:30:02又一个新案件？

案件间隔其实可以不用改，只要别让所有人都在0-1点把票投完就行，怕B站哪天给全封了。。

**Comment by yjqiang** [comment]
你自己开机时间就是投票启动时间  想自定义暂时没toml接口开放，只能自己改代码

**Comment by heatded** [comment]
> 你自己开机时间就是投票启动时间 想自定义暂时没toml接口开放，只能自己改代码

好吧，谢谢大佬
