### ISSUE TITLE
正在启动 1 号数据连接

### ISSUE THREAD

**Issue by Mabisi** [yjqiang/bili2.0#302]
![image](https://user-images.githubusercontent.com/19968269/76193097-3a9b0400-621e-11ea-8b0e-a48ef8da73b2.png)
一直在启动 1 号数据连接

**Comment by D3ee** [comment]
不要用idle运行，直接双击或者cmd运行，自己关闭把

**Comment by Mabisi** [comment]
> 不要用idle运行，直接双击或者cmd运行，自己关闭把

好了~~谢谢@.@
