### ISSUE TITLE
脚本打开登录后报错

### ISSUE THREAD

**Issue by wzxyisme** [yjqiang/bili2.0#303]
**再确认一次 issue 题目**
请记得把 issue 标题改成问题描述的概述，而不是简单的一句话，《电脑开不了了》、《闪退了》、《救命啊》这些

**问题描述**
尽量详细叙述发生时间等
3月10号我下载最新版本，填好信息后运行正常，ctrl＋c结束运行后把脚本打包备了一份后再次运行就报错了，重新下载运行也不行
**截图或者视频或者报错文字**
截图请务必把名字等信息打码
![image](https://user-images.githubusercontent.com/45878990/76300566-e2d0cb80-62f7-11ea-8911-224fbf494f60.png)

**必要的系统信息描述等**
python 版本以及系统版本信息
python3.8.1
window10 专业版
**最近何时更新的脚本**
几天前还是几小时前
刚刚
**最后确认**
- [👌 ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [👌 ] 我代码上次更新时间距今没有超过 2 个月以上
- [👌 ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [👌 ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/master/conf/ctrl.sample.toml#L21 sleep_range写错了

**Comment by wzxyisme** [comment]
谢谢大佬
