### ISSUE TITLE
控制台查询硬币数量显示-1

### ISSUE THREAD

**Issue by Wahacer** [yjqiang/bili2.0#308]
1.控制台查询硬币数量显示-1
这或许是个小bug？

https://s1.ax1x.com/2020/03/14/8Mcn8e.png

2.建议增加控制台查询投硬币记录及投辣条记录

**Comment by yjqiang** [comment]
2. 投喂辣条记录？从 b 站拉取么，没有这个 api。我本地也没有 log 记录脚本投递情况，全 `print` 的

**Comment by Wahacer** [comment]
2get了，那1呢……

**Comment by yjqiang** [comment]
1.硬币我这里正常，你自己登陆b站看看，是不是本身就是-1的

**Comment by Wahacer** [comment]
> 1.硬币我这里正常，你自己登陆b站看看，是不是本身就是-1的

……暂时还登不上去，先等等看吧，谢谢了，我close了
