### ISSUE TITLE
SSL:CERTIFICATE_UERIFY_FAILED

### ISSUE THREAD

**Issue by Jutean** [yjqiang/bili2.0#31]
在运行0的时候出现的

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/3
关闭ssl证书校验。这类情况的原因可能是vps证书老旧等原因，非本程序bug

**Comment by yjqiang** [comment]
https://github.com/aio-libs/aiohttp/issues/955
这里面不是写明白了么

**Comment by yjqiang** [comment]
I don't know what's wrong with certificates for your site but you may disable certificate checks by passing verify_ssl=False to connector ctor:

session = aiohhtp.ClientSession(connector=aiohttp.TCPConnector(verify_ssl=False))

**Comment by Jutean** [comment]
解决了，我是重装了服务器，然后用网页打开某个直播间完美解决了

**Comment by rabbit2rabbit** [comment]
在不关闭证书验证的情况下，打开bilibili.tv,重新重新安装证书到本地即可。
