### ISSUE TITLE
仅设置了账号，其余文件均为默认 启动就报错

### ISSUE THREAD

**Issue by 1525249038** [yjqiang/bili2.0#310]
C: sers \Admin is trator Des ktopNbi1i2. 0-mas ter >python run . py
Traceback (most recent call last) 8
File "run . py"line 36， in <module>
from dannu.bili. dannu nonitor import DannuPrinter. DanmuRaff leMon itorFile "C: sers \Admin is tratorNDes ktopNbi1i2. 0-mas ter\danmuNbili_ dannu monitor . Py"line 8，in <module>
from dannu.bili_ abc import bili_ danmu File "C: NUsers \Admin is trator Des ktopNbili2 - C-mas terdanmuNbili. abc hili danmu py". line 5，in <module>
from dannu abc import WsConn. Client
Mo duleNo t FoundError: No module naned ' danmu_ abc
G: sers \Admin is tratorNDe s ktop\bili2.0-master>

**Comment by yjqiang** [comment]
看requirements.txt
