### ISSUE TITLE
远程计算机拒绝网络连接

### ISSUE THREAD

**Issue by bilibiliapp** [yjqiang/bili2.0#312]
远程计算机拒绝网络连接 Http：//152.32.186.69:19951/captcha/v1

**Comment by bilibiliapp** [comment]
> 远程计算机拒绝网络连接 Http：//152.32.186.69:19951/captcha/v1

class'aiohttp.client_exceptions.ClientConnectorError'>Cannot connect to host 152.32.186.69:199951 ssl:default [远程计算机拒绝网络连接。]http://152.32.186.69:199951/captcha/v1

**Comment by BlacK201** [comment]
我也遇到了这个情况

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/313
