### ISSUE TITLE
反复请求多次未成功

### ISSUE THREAD

**Issue by ValentinoLee** [yjqiang/bili2.0#313]
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host 152.32.186.69:19951 ssl:default [Connect call failed ('152.32.186.69', 19951)] http://152.32.186.69:19951/captcha/v1
[2020-03-19 15:37:13] 反复请求多次未成功, http://152.32.186.69:19951/captcha/v1,

**Comment by yjqiang** [comment]
可能树验证码服务器挂了，或者本地网络问题

**Comment by zhz1237ok** [comment]
你别把IP也复制出来啊，小老弟，你怎么回事

**Comment by 2604237845** [comment]
确定是验证码服务器挂了，换个服务器就好了
