### ISSUE TITLE
cookie过期登陆需要验证码会一直登陆

### ISSUE THREAD

**Issue by xiaozou416** [yjqiang/bili2.0#314]
删了cookie重新登陆就会登陆成功 或密码错误 设备锁 需要验证码验证等
![验证码一直刷](https://user-images.githubusercontent.com/42770167/77087052-9135e880-6a3d-11ea-9244-4cee15e85ec0.png)

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/306

**Comment by xiaozou416** [comment]
emmm当下为多账号情况下 单账号或者少量并没有发现以下情况
