### ISSUE TITLE
动态抽奖问题

### ISSUE THREAD

**Issue by Timewlies** [yjqiang/bili2.0#315]
我打开了立即参与动态抽奖，然而它并没有转发动态，而且好像没有循环搜索动态。
![动态](https://user-images.githubusercontent.com/39881147/77192655-d9c1d480-6b17-11ea-81fe-803f86603d72.png)

**Comment by yjqiang** [comment]
你得重启自己慢慢看  多半可能是卡在某个id上

**Comment by Timewlies** [comment]
> 你得重启自己慢慢看多半可能是卡在某个id上

我看了一下好像是卡在了63717989这个id上，大佬阔以教一下这么解决嘛?昨晚看了一晚上其他人的提问和解决还是不会。
![2020032107570](https://user-images.githubusercontent.com/39881147/77214382-d8110480-6b49-11ea-87c7-22cc8f7ec775.png)

**Comment by yjqiang** [comment]
希望只是特例，如果b站改了api的话，可能要大改

**Comment by yjqiang** [comment]
这个是解决了，希望其他的正常吧
