### ISSUE TITLE
开启动态抽奖后闪退

### ISSUE THREAD

**Issue by VinsentZWang** [yjqiang/bili2.0#316]
ctrl里打开动态抽奖后

# 实物抽奖开关
substance_raffle = true

# 动态抽奖开关
dyn_raffle = true
# 立刻参与的话，暴力搜索到就参与；否则就等到快开始抽奖了，才会参与
join_dyn_raffle_at_once = false
在task设置了抽奖@的人
# 抽奖@的人，格式为 326499679 = "哔哩哔哩漫画"（例如 {332704117 = "白上吹雪Official", 339567211 = "赤井心Official"}）
# 要求被@的人不能经常改名字，这样也就说明这些用户也可控，即不得随意骚扰他人
dyn_lottery_friends = {哔哩哔哩漫画}
运行之后闪退

**Comment by yjqiang** [comment]
@VinsentZWang 另开一个issue

**Comment by VinsentZWang** [comment]
> @VinsentZWang dyn_lottery_friends格式错了

可以给我个格式示范吗

**Comment by VinsentZWang** [comment]
@yjqiang 
可以给我个格式示范吗

**Comment by yjqiang** [comment]
抽奖@的人，格式为 326499679 = "哔哩哔哩漫画"（例如 {332704117 = "白上吹雪Official", 339567211 = "赤井心Official"}）

**Comment by VinsentZWang** [comment]
@yjqiang 懂了懂了 谢谢

**Comment by VinsentZWang** [comment]
@yjqiang 还是闪退awa
我都直接把你的
dyn_lottery_friends = {332704117 ="白上吹雪Official"}
复制上去了
是不是
# 实物抽奖开关
substance_raffle = true
# 动态抽奖开关
dyn_raffle = true
# 立刻参与的话，暴力搜索到就参与；否则就等到快开始抽奖了，才会参与
join_dyn_raffle_at_once = false
这里出问题了

**Comment by yjqiang** [comment]
截图报错信息    没报错信息差不到问题点

**Comment by VinsentZWang** [comment]
要不我留个QQ你加我联系吧
3511945164

**Comment by yjqiang** [comment]
没时间，复习考研。。。在github吧

**Comment by VinsentZWang** [comment]
找不到报错信息QAQ

**Comment by VinsentZWang** [comment]
找不到报错信息QAQ

**Comment by VinsentZWang** [comment]
没发现报错信息..

**Comment by VinsentZWang** [comment]
没发现报错信息在哪....

**Comment by yjqiang** [comment]
用cmd 运行，`python run.py`。而不是双击文件，这样就不会闪退了，就有报错提示

**Comment by VinsentZWang** [comment]
![F_17)JH27S3PS}{AR74XQ~A](https://user-images.githubusercontent.com/62465329/77225212-163d1100-6ba8-11ea-82d2-6e7f9d8d8d1c.png)
这是错误报告

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/39
