### ISSUE TITLE
想问一下dalao，相关参数怎么设置？比如休眠时间和抽奖识别概率这些的。

### ISSUE THREAD

**Issue by Cohen8s** [yjqiang/bili2.0#317]
休眠时间那个我一设置就会闪退...还有一些功能不会怎么开启...

**Comment by yjqiang** [comment]
# 时间格式举例 sleep_ranges = [[08:00:00, 09:03:00], [14:04:00, 14:46:00]] ，24小时制，不得省略写0或省略秒数或加空格
你写错了吧，贴出你写的那个来。
“一些”功能太宽泛，我不可能解答的
