### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#32]
最近一大批小号出现在storm的弹幕中，我建议，把2.0的关于storm的源码delete，注释的话还是看的到的。公开这个貌似引起了很多人的不满。。。当然，只是建议而已。另，如果用的是源码列表的proxies,也会封死你收集来的。（可能不是用你提供的）（不过我挺希望能delete）

**Comment by yjqiang** [comment]
storm那个我没开，api封着。

**Comment by yjqiang** [comment]
我没有用proxy，用了cdn

**Comment by rabbit2rabbit** [comment]
我看到是缺少了获取弹幕“~”信息缺失和检测到gift39的代码块被注释，这两个我个人觉得还是比较容易就搞定了。。。
p.s今天看到的场面太恐怖了，1/2弹幕都是25ul以下，没牌子没头衔。。

**Comment by yjqiang** [comment]
不会继续做，但是保留他人修改的空间
