### ISSUE TITLE
b站脑瘫 突然启用了bvid

### ISSUE THREAD

**Issue by Twoleaf** [yjqiang/bili2.0#320]
![QQ图片20200323165846](https://user-images.githubusercontent.com/43440669/77299541-95a51e80-6d27-11ea-92b8-349937c74b75.png)

https://www.bilibili.com/read/cv5167957

新接口https://api.bilibili.com/x/web-interface/ranking?rid=0&day=3&type=1&arc_type=0&jsonp=jsonp
使用json解析

**Comment by yjqiang** [comment]
https://api.bilibili.com/x/web-interface/ranking?rid=0&day=1&type=1&arc_type=0&jsonp=jsonp

**Comment by yjqiang** [comment]
https://api.bilibili.com/x/web-interface/view?bvid=BV1P7411U7qj
