### ISSUE TITLE
2020.3.23 docker pip安装时报错

### ISSUE THREAD

**Issue by CanvasQAQ** [yjqiang/bili2.0#321]
之前一直在windows上使用，能够正常运行，今天使用家中群晖NAS的docker（实际还是后台ssh指令，与普通linux一致）
最终报错
```
Collecting aiohttp==3.6.2 (from -r requirements.txt (line 1))
Could not find a version that satisfies the requirement aiohttp==3.6.2 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for aiohttp==3.6.2 (from -r requirements.txt (line 1))
You are using pip version 19.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command
```
由于报错后容器直接关闭，不知道如何去升级这个pip，能否请作者大大提供个思路

**Comment by yjqiang** [comment]
我也不知道docker这里。。。这是其他人贡献的。。。要不就手动吧23333

**Comment by CanvasQAQ** [comment]
> 我也不知道docker这里。。。这是其他人贡献的。。。要不就手动吧23333

哈哈哈，windows上我稍微改了点东西，开机后台运行，输出到log文件，也没怎么手动了，主要是电脑不想一直开，Nas倒是一直开着，所以想往那边考虑了，这个issues我就暂时不关了，等两天有缘人（dalao）出现，如果还是不能解决我就认了吧

**Comment by yjqiang** [comment]
行

**Comment by zhz1237ok** [comment]
https://www.runoob.com/docker/docker-install-python.html

**Comment by CanvasQAQ** [comment]
> https://www.runoob.com/docker/docker-install-python.html

emmm上半部分是新建一个python的容器啊，无法解决在作者提供的容器中升级pip的问题，还是你想让我用作者的代码重新封装一个docker镜像？

**Comment by zhz1237ok** [comment]
群辉NAS是本身不带Python的包的吧，要用wget去下载再装的吧

**Comment by RedEnvelopes** [comment]
推测:我在termux里运行的时候也报了这个错,vi编辑可以看到行末有^M 应该是Linux和win换行符不同导致的

**Comment by Skimige** [comment]
@RedEnvelopes @CanvasQAQ 

- ~~Python 版本过低~~ 排除
- ~~pip 版本过低~~ 排除
- ~~Python 冲突~~ Docker 应该和 Python 2 无关

如果可以，是否可以提供更完整的 log？个人猜测可能是网络问题，可以尝试一下
``` sh
docker run --rm -it \
  -v $PWD/conf/user.toml:/app/conf/user.toml \
  -v $PWD/conf/ctrl.toml:/app/conf/ctrl.toml \
  -v $PWD/conf/task.toml:/app/conf/task.toml \
  Skimige/bili2.0-Docker
```
或

`pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir -r requirements.txt`

**Comment by CanvasQAQ** [comment]
> @ RedEnvelopes @ CanvasQAQ
> 
> * ~Python版本过低~ 排除
> * ~pip版本过低~ 排除
> * ~Python冲突~ Docker应该和Python 2无关
> 
> 如果可以，是否可以提供更完整的log？个人猜测可能是网络问题，可以尝试一下
> 
> ```shell
> 泊坞窗运行--rm -it \
>   -v $ PWD /conf/user.toml:/app/conf/user.toml \
>   -v $ PWD /conf/ctrl.toml:/app/conf/ctrl.toml \
>   -v $ PWD /conf/task.toml:/app/conf/task.toml \
>   Skimige / bili2.0-Docker
> ```
> 
> 或
> 
> `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir -r requirements.txt`

非常感谢你提供的思路，我最终没有使用你提供的镜像(群晖啥都缺，家里网络环境还差，pull镜像基本不成功)，但是经过修改，现在这个已经能够正常的在我的群晖上运行了，下面是我的一些经过：
首先是因为一直报错的是pip版本不够，而pip版本是镜像本身提供的，原版镜像中运行的python是3.6.8，使用的pip版本是19.X.X（具体多少没记录），而在源代码后面的更新中采用的一些库的版本需要更高等级的pip运行，由于docker实行到报错位置会自动关闭容器，所以我一直无法成功的在关闭之前进行升级pip，接下来我注意到了一个地方，就是docker镜像本身是带commond属性的，而这个属性就是运行镜像后实行的脚本，原镜像脚本如下：
```
/bin/sh -c  git pull  && pip install --no-cache-dir -r requirements.txt && python ./run.py
```
从上面可以看到用sh实现了如下的几个命令

- 获取最新git
- 安装相关库
- 执行run.py

那么我需要做的事情就是在安装库之前加上更新pip的指令，于是接下来我查了更改docker CMD的相关方法，在ssh中执行如下代码：
```
  docker commit --change='CMD [ "sh", "-c", "git pull && pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir --upgrade pip && pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir -r requirements.txt && python ./run.py"]'  1dcca84f12a7  zsnmwy/bili2.0:newtest
```
其中参数的设置参考了如下两个网址：
- [docker CMD命令](https://www.jianshu.com/p/78f4591b7ff0)
- [docker commit创建新镜像](https://www.centos.bz/2017/01/docker-commit-create-a-new-image-from-a-containers-changes/)

镜像名称仍然采用了原镜像名，更改了tag为newtest，以此生成了我的一个新镜像，如此更改后，我再运行的容器就是带有pip更新并且使用清华源的版本了。
经过测试，群晖上经过正常的更新步骤，作者的脚本就能够正常运行了
![image](https://user-images.githubusercontent.com/38531788/77775593-b226bb00-7087-11ea-8867-f5a5a1820a4a.png)

话说我最开始完全不懂docker的啊(#`O′)硬生生逼我学了一通
然后希望有能力的大大们能够及时更新dockerhub上的镜像，我猜测别人新运行的docker也会存在这种问题，如果今后我再研究docker的话，我也许会优化相关内容。
最后感谢各位代码的贡献者，我又能愉快的捞辣条了

**Comment by CanvasQAQ** [comment]
> 推测:我在termux里运行的时候也报了这个错,vi编辑可以看到行末有^M 应该是Linux和win换行符不同导致的

我的问题刚刚解决了，你可以看看我的解决过程有没有什么参考价值

**Comment by yjqiang** [comment]
66666666666
