### ISSUE TITLE
关于idle_seconds

### ISSUE THREAD

**Issue by DarrenIce** [yjqiang/bili2.0#323]
这两天会经常卡在等待任务装载那里，我就把bili_schede.py第108行的idle_seconds改成了1，想问一下会有什么影响吗。目前只发现会每秒出一次等待任务装载

**Comment by yjqiang** [comment]
正常的话，这个东西不卡的，除非你403了。
装载是折腾日常任务的，一秒重复一次日常任务太频繁了。

**Comment by DarrenIce** [comment]
那么will sleep不会影响大航海跟捡辣条吗，没影响我就改回去了

**Comment by yjqiang** [comment]
不影响

**Comment by DarrenIce** [comment]
好，谢谢啦
