### ISSUE TITLE
关于task.toml的一些问题

### ISSUE THREAD

**Issue by chenyitian2004** [yjqiang/bili2.0#324]
1：[custom_task_arrangement.username]这里没有说明“用户名如果包含.这个特殊符号需要使用双引号括起来，这里xx.qq.com就是username”，实际使用时是否需要添加。如果设置了错误的username，会不会出现问题。
2：投满正在佩戴的勋章当日亲密度设置为true但未生效？（send_gift设置为-1，同时开启了过期礼物赠送）当日23:59查看仍未生效
3：probability_{task_name}是只有原本sample文件中存在的参数可以设置，还是自己可以主动添加（如probability_join_tv_raffle）。如果可以自己添加，能不能加到全局参数里，应该放在哪个位置（主要是想设置小电视的抽奖概率）。
4：（sub-table({'custom_task_arrangement': {'user0': {}, 'user1': {}}})，name与user.toml内的相同）这段语句的功能是什么，是[custom_task_arrangement.username]的另一种写法吗。

求解答，谢谢

**最后确认**
- [√] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [√] 我代码上次更新时间距今没有超过 2 个月以上
- [√] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [√] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
1. `custom_task_arrangement.username` 名字错误不会产生致命影响，只会起不到作用罢了
2. 投递是间隔一段时间周期尝试，可能正好卡在了那段时间
3. 全局可以，也可以自定义的位置
4.

**Comment by chenyitian2004** [comment]
还有个问题是未正在佩戴的勋章似乎投递礼物并不能增加亲密度？工具会自动切换勋章吗

**Comment by yjqiang** [comment]
有这样？我不知道，我一直都是不切换投递的。应该正常

**Comment by chenyitian2004** [comment]
或许我记错了。。或许以前存在过。。

**Comment by chenyitian2004** [comment]
还有，请问`probability_{task_name}`这里的`{task_name}`是可以替换为任意存在的`{task_name}`吗。
`custom_task_arrangement.username`这里我`username`用了邮箱地址是不是应该加上双引号

**Comment by yjqiang** [comment]
1. name 对应了tasks文件夹里面文件的 task name
2. 是的，必须加双引号

**Comment by chenyitian2004** [comment]
`{task_name}`不是指join_dyn_raffle、join_dyn_raffle这些吗？
所以我在`[global_task_arrangement]`下方加一个`probability_join_tv_raffle = 0.7`（设置小电视概率为0.7）是可以生效的对吧

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/master/tasks/tv_raffle_handler.py#L8

**Comment by chenyitian2004** [comment]
好的，感谢

**Comment by chenyitian2004** [comment]
建议在`[custom_task_arrangement.username]`后面的注释里面加个要写双引号的特殊情况

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/master/conf/task.sample.toml#L71
