### ISSUE TITLE
动态抽奖没有效果

### ISSUE THREAD

**Issue by newtool** [yjqiang/bili2.0#328]
![TIM截图20200325081934](https://user-images.githubusercontent.com/32417809/77490920-48d05d80-6e77-11ea-92d0-74104492aee9.png)
![TIM截图20200325081955](https://user-images.githubusercontent.com/32417809/77490926-4e2da800-6e77-11ea-863b-309823883ce9.png)
动态抽奖之类的都打开了
![TIM截图20200325081809](https://user-images.githubusercontent.com/32417809/77491010-83d29100-6e77-11ea-94ff-a7bfd2991e25.png)
也有在跑
但账号并没有转发的动态和关注的up
![微信截图_20200325090644](https://user-images.githubusercontent.com/32417809/77491209-1a9f4d80-6e78-11ea-9a6d-7582a9682fa5.png)
数据库大小也没有变
要是就我自己是这样，我再检查检查。

**Comment by 2604237845** [comment]
没扫到抽奖怎么转发？

**Comment by newtool** [comment]
![TIM截图20200325092231](https://user-images.githubusercontent.com/32417809/77491870-f17fbc80-6e79-11ea-8248-6af75050243e.png)
这样的算不算扫到

**Comment by 2604237845** [comment]
不算

**Comment by newtool** [comment]
明白了！

**Comment by qzbsll** [comment]
> ![TIM截图20200325092231](https://user-images.githubusercontent.com/32417809/77491870-f17fbc80-6e79-11ea-8248-6af75050243e.png)
> 这样的算不算扫到



> 明白了！

你解决了吗，怎么办的
