### ISSUE TITLE
断网后不断刷新“正在启动-1号数据连接”

### ISSUE THREAD

**Issue by chenyitian2004** [yjqiang/bili2.0#329]
今天不小心碰到了网线，然后发现风扇开始狂转，发现是脚本一直在刷新“正在启动-1号数据连接”，消耗大量系统资源，建议延长重试间隔避免意外断网导致的大量系统资源消耗（期间cpu直接飙到50%）

**Comment by yjqiang** [comment]
。。。暂时没这个打算
