### ISSUE TITLE
不想所有号过12点进入睡眠模式

### ISSUE THREAD

**Issue by 18395595314** [yjqiang/bili2.0#33]
![image](https://user-images.githubusercontent.com/41237775/46906795-d0543600-cf3b-11e8-9160-c82b50f28d2a.png)

**Comment by 18395595314** [comment]
图片里修改的是states.py的代码

**Comment by yjqiang** [comment]
task.py里面run_timestate这里可以开头加个return或者在0.py中不要执行这个函数
