### ISSUE TITLE
动态抽奖使用不了

### ISSUE THREAD

**Issue by qzbsll** [yjqiang/bili2.0#330]
显示
C:\\Windows\\py.exe
55194329 None
r2020-03-2811：31:491正在查找已经结束的实物抽奖：
#[ ]
is_dyn_raffle:65194330 code:0
55194330 None
is_dyn_raffle:65194331 code:0
55194331 None
is_dyn_raffle:65194332 code:0
55194332 None
is_dyn_raffle:65194333 code:0
55194333 None
is_dyn_raffle:65194334 code:0
55194334 None
is_dyn_raffle:65194335 code:0
55194335 None
is_dyn_raffle:65194336 code:0
55194336 None

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/328
