### ISSUE TITLE
在ctrl中填入监控服务器上的密匙导致运行崩溃

### ISSUE THREAD

**Issue by blackzero-a** [yjqiang/bili2.0#331]
**再确认一次 issue 题目**
在ctrl中填入监控服务器上的密匙导致运行崩溃

**问题描述**
尽量详细叙述发生时间等

**截图或者视频或者报错文字**
![QQ截图20200328173019](https://user-images.githubusercontent.com/53086059/77820033-43df0880-711a-11ea-80ca-265e432d8461.png)
![QQ截图20200328173212](https://user-images.githubusercontent.com/53086059/77820036-46416280-711a-11ea-9fba-4c47c6d16e8a.png)

**必要的系统信息描述等**
win7 64 python 版本3.8.2

**最近何时更新的脚本**
3.25

**最后确认**
不加密匙一切正常，加了就会崩溃

**Comment by yjqiang** [comment]
你tcp url写错了
