### ISSUE TITLE
安卓termux使用不能调出控制台

### ISSUE THREAD

**Issue by shoucandanghehe** [yjqiang/bili2.0#335]
log如下
``````
[2020-03-31 09:04:21] 正在启动 0 号数据连接
未发现即将过期的礼物
[2020-03-31 09:04:24] 正在启动 0 号数据连接
[2020-03-31 09:04:27] 正在启动 0 号数据连接
2
1
3
[2020-03-31 09:04:30] 0 号数据连接确认建立连接（i7tC$r4BN[*sd`yd）
4
5
6
1
2
3
4
4
6
7
8
8


[2020-03-31 09:04:45] 正在查找需要参与的实物抽奖：
# []
[2020-03-31 09:04:45] 正在查找已经结束的实物抽奖：
# []
``````
bili2.0为最新版
python 3.8.2

**Comment by yjqiang** [comment]
无安卓手机，无法复现

**Comment by shoucandanghehe** [comment]
啊这

**Comment by zhz1237ok** [comment]
安卓手机运行这种东西要看运气的，毕竟不是标准的linux系统，python依赖也不一定安装齐全

**Comment by HYY-zh** [comment]
> log如下
> 
> ```
> [2020-03-31 09:04:21] 正在启动 0 号数据连接
> 未发现即将过期的礼物
> [2020-03-31 09:04:24] 正在启动 0 号数据连接
> [2020-03-31 09:04:27] 正在启动 0 号数据连接
> 2
> 1
> 3
> [2020-03-31 09:04:30] 0 号数据连接确认建立连接（i7tC$r4BN[*sd`yd）
> 4
> 5
> 6
> 1
> 2
> 3
> 4
> 4
> 6
> 7
> 8
> 8
> 
> 
> [2020-03-31 09:04:45] 正在查找需要参与的实物抽奖：
> # []
> [2020-03-31 09:04:45] 正在查找已经结束的实物抽奖：
> # []
> ```
> 
> bili2.0为最新版
> python 3.8.2

需要安装oh my zsh，装了之后就能显示了

**Comment by zhongfly** [comment]
安卓机可以使用Pydroid 3来运行，控制台能正常使用

**Comment by shoucandanghehe** [comment]
> 需要安装oh my zsh，装了之后就能显示了
感谢，已解决

**Comment by shoucandanghehe** [comment]
```
pkg update
pkg install wget git zsh
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```
