### ISSUE TITLE
访问被拒绝（即小黑屋），但是脚本输入9回车查小黑屋状态时，仍然显示“自由之身”

### ISSUE THREAD

**Issue by sr1y7** [yjqiang/bili2.0#338]
**问题描述**
2020年3月31日，大概下午的时候，辣条不增加，进入浏览器抽奖显示”访问被拒绝“
推测小黑屋原因：使用和浏览器上b站相同的ip。
平时使用vmware虚拟机（网卡为桥接模式）挂脚本，使用主机浏览器看b站，虽然每天辣条好几千，但是未黑屋。2020年3月31日直接使用主机挂机脚本，可能是小黑屋原因。
之前未及时更新pip模块，是因为我用记事本直接修改toml配置文件导致无法启动（后来才知道必须用notepad++等专业软件），我以为是python版本（我对3.6+的理解有歧义，可以是3.6.*、3.7.*、3.8.*的合称，也可以只包括3.6.*）或者pip模块不能更新的原因，因此卸载整个PYTHON3.8.2后安装python3.7.10和requirements.tx的pip。
平时都使用power shell运行脚本，不知道和cmd有什么区别。

**必要的系统信息描述等**
主机（导致小黑屋）是PYTHON3.8.2，虚拟机是PYTHON3.7.10；主机和虚拟机系统都是windows server 2016，相当于WIN10，14393.3595
中小黑屋时requirements.tx里面的模块未及时更新，但是查询黑屋状态时已使用”python -m pip install --upgrade pip“更新。
我平时并非连续使用，会关闭脚本后再上b站查看结果。小黑屋那天发现脚本自身可以查询辣条和徽章等信息，从上午9点左右开始，基本上是连续挂机。

**最近何时更新的脚本**
约6天前，应该是最新版。

**最后确认**
请问查询黑屋状态的功能中，能否显示剩余黑屋时间？现在的情况，是明明是小黑屋，却显示”自由之身“，除非抽奖时发现小黑屋，再次查询时才会显示”恭喜中奖“
建议在主页的”使用方法”中，提示修改配置文件不要用记事本。我是C语言基础挂科的纯小白，没有任何编程常识。

**Comment by shoucandanghehe** [comment]
你用虚拟机和主机挂不都是同一个IP吗？那并不会增加小黑屋风险
小黑屋是肯定得进的，只要你挂辣条机，除非你氪金够多
另外小黑屋目前判断方法应该只有抽奖返回访问被拒绝
小黑屋时间一般为1~15天随机，程序也不知道你小黑屋还有多长时间，B站更不会给api

**Comment by shoucandanghehe** [comment]
配置文件修改记事本可以，就是保存编码要为UTF-8

**Comment by shoucandanghehe** [comment]
Python版本最好为最新

**Comment by sr1y7** [comment]
多谢大佬。
vmware桥接应该不是一个ip。我以前的校园网，单ip限速60k，所以我就桥接，多开虚拟机下载，总网速提高，所以喜欢桥接。
好像挂脚本和浏览器看比利不是一个ip，更不容易小黑屋。

**Comment by shoucandanghehe** [comment]
桥接应该只是不同内网IP
另外我个人经验是脚本在你账号的常用IP下挂不容易黑屋

**Comment by CanvasQAQ** [comment]
同样的时间点我也小黑屋了，估计是B站找到了检测方法封了一大批？

**Comment by shoucandanghehe** [comment]
今天我这里8个号进去7个，可能是B站闲着没事干吧
检测的话，这么频繁的抽奖还需要检测吗？

**Comment by CanvasQAQ** [comment]
认栽，刚刚仔细翻了日志，是31号下午4点到5点开始报小黑屋，顺便一问这东西对账号影响吗，会不会下次进就直接永封啥的

**Comment by shoucandanghehe** [comment]
我这边应该是今天12点以前吧，黑屋的话目前没听过有永封的，一般都是最多15天就出来，不过也有倒霉的刚出去又进来跟没出过一样233

**Comment by shoucandanghehe** [comment]
见过的最长记录45天

**Comment by shoucandanghehe** [comment]
氪个提督你明天就出（滑稽）

**Comment by CanvasQAQ** [comment]
行，那我就不管了，缓一个月再说

**Comment by shoucandanghehe** [comment]
嘛，一般不会有事，一直挂着也一样，只有不挂动态

**Comment by sr1y7** [comment]
大佬，请问运行脚本（虚拟机，桥接）的时候，是同时开着网页端（主机）和安卓客户端的b站更容易小黑屋，还是不开b站更容易小黑屋，或者开不开b站没有影响？

**Comment by shoucandanghehe** [comment]
应该没影响的，想要不经常小黑屋只能多氪金或者把概率调低或者半夜的时候休眠

**Comment by sr1y7** [comment]
多谢大佬，我半夜不挂机就行了。

**Comment by shoucandanghehe** [comment]
脚本不是有设定休眠时间的选项么。。
手动不嫌麻烦嘛

**Comment by sr1y7** [comment]
关机是因为我的电脑不在自己的房间，晚上本来需要关机。我不知道小黑屋到底是人工操作还是程序自动判定。
如果是人工操作，我觉得把上班时间设置成休眠时间，可能更少小黑屋，毕竟礼物多主要也是在下班时间。

**Comment by shoucandanghehe** [comment]
程序自动的。。
哪可能给你用人工。。
一般3~8点不会有礼物，别的时间都是多少的问题

**Comment by sr1y7** [comment]
多谢大佬。我觉得礼物最多大概是下午7点到凌晨1点左右。

**Comment by mzth** [comment]
半夜不挂机好像也不管用了，刚进小黑屋，应该又改规则了

**Comment by sr1y7** [comment]
各位大佬，请问“直播心跳”“心跳礼物”是干什么的？

**Comment by sr1y7** [comment]
> 半夜不挂机好像也不管用了，刚进小黑屋，应该又改规则了

既然那天是下午小黑屋的，试试下午也休眠，有没有用？

请问“直播心跳”“心跳礼物”是干什么的？类似于三天爷/年费老爷/带会员的直播挂机吗？

**Comment by yjqiang** [comment]
@sr1y7 自己新开issue
