### ISSUE TITLE
刚刚发现出现以下报错信息

### ISSUE THREAD

**Issue by GOOD-AN** [yjqiang/bili2.0#339]
![QQ图片20200404163327](https://user-images.githubusercontent.com/53306377/78422464-0cc8a400-7692-11ea-938c-d53ecf6a512b.png)
现导致不会送礼物

**Comment by yjqiang** [comment]
可能清明的问题吧，等明天

**Comment by shoucandanghehe** [comment]
今天B站把所有直播（除了央视）都关了
弹幕和礼物也关了

**Comment by GOOD-AN** [comment]
> 可能清明的问题吧，等明天

好的

**Comment by GOOD-AN** [comment]
> 今天B站把所有直播（除了央视）都关了
> 弹幕和礼物也关了

嗯嗯
