### ISSUE TITLE
动态抽奖检测问题

### ISSUE THREAD

**Issue by HiemalBeryl** [yjqiang/bili2.0#341]
背景：下载到的程序挂了好几天都没有看到动态转发，于是自己找了一个抽奖动态丢给程序运行，程序检测不到给它的抽奖动态
![动态1](https://user-images.githubusercontent.com/63165207/78459094-4082e880-76e9-11ea-8c95-948f104b59ea.png)
这是用于测试的动态
https://t.bilibili.com/372922642989756756?tab=2
![api1](https://user-images.githubusercontent.com/63165207/78458893-77f09580-76e7-11ea-9a1a-25ac832b4ef0.png)
![api2](https://user-images.githubusercontent.com/63165207/78458894-7b841c80-76e7-11ea-9bf3-110c1490cd33.png)
根据api手动查询到的结果
https://api.vc.bilibili.com/lottery_svr/v1/lottery_svr/lottery_notice?business_type=2&business_id=65966021
https://api.vc.bilibili.com/link_draw/v1/doc/detail?doc_id=65966021

![change](https://user-images.githubusercontent.com/63165207/78458896-7e7f0d00-76e7-11ea-8b8f-aee0e8b2c71c.png)
修改了代码以直接访问该抽奖动态
![run1](https://user-images.githubusercontent.com/63165207/78458897-7fb03a00-76e7-11ea-93fa-835f986d3881.png)
然而程序在运行中将该动态视为普通动态并跳过

想问下这种情况是哪里设置错误了吗？还是b站本身的原因？

**Comment by shoucandanghehe** [comment]
这个不清楚，没用过抽动态
@yjqiang
