### ISSUE TITLE
登录接口不行了吗？

### ISSUE THREAD

**Issue by Cohen8s** [yjqiang/bili2.0#342]
cookie过期后就一直这样...无论是个人电脑还是服务器...
![image](https://user-images.githubusercontent.com/46984432/78466900-7c459e80-7739-11ea-8357-2c48e0efbc99.png)

**Comment by yjqiang** [comment]
b站改登陆api了

**Comment by Cohen8s** [comment]
泪崩（哭）我手贱...我为什么要重装系统...
