### ISSUE TITLE
抽奖延迟问题

### ISSUE THREAD

**Issue by shoucandanghehe** [yjqiang/bili2.0#343]
#260 这里说的是并发量
能不能让抽奖延迟低一点，获取到过了等待时间（小电视）马上抽那种
不然风暴以及大量小电视之类的情况会漏掉很多

**Comment by yjqiang** [comment]
不漏啊，合理时间范围内抽取的，延迟是因为多用户的情况，防止密集参与。不会遗漏的

**Comment by shoucandanghehe** [comment]
emm，节奏风暴的话是一般1~3s就抽完了
我这边265个只抽到一个
多用户因为没搞明白怎么写配置文件就直接一个号开一个了）

**Comment by yjqiang** [comment]
不知道。。。正常情况下不会只有一个用户参与

**Comment by shoucandanghehe** [comment]
我是指一个号推送了265个节奏风暴只领到一个
git不给我发提醒邮件了很离谱）

**Comment by yjqiang** [comment]
这不是正常么，节奏风暴看人品的，不是每次都能抢到

**Comment by shoucandanghehe** [comment]
em
行吧
