### ISSUE TITLE
总是报403错误,重新解压启动也会这样

### ISSUE THREAD

**Issue by 18395595314** [yjqiang/bili2.0#35]
![image](https://user-images.githubusercontent.com/41237775/47157810-bee4a280-d31c-11e8-8082-b69fd793c316.png)

**Comment by yjqiang** [comment]
过于频繁就是请求过多导致了ip被短暂拉黑  你有多少用户？

**Comment by 18395595314** [comment]
`150

**Comment by 18395595314** [comment]
ip被封了吗,我现在网页端b站都显示不出来,手机端可以

**Comment by rabbit2rabbit** [comment]
现在只要IP被拉黑，无论是通过什么途径被拉黑，全站（直播区？）拉黑，有点可怕

**Comment by yjqiang** [comment]
不是就是b站判定为ddos可能了  等半小时或者自己换ip就可以了  不与账号绑定的

**Comment by yjqiang** [comment]
150可能有点多吧  建议少点  比如100人

**Comment by 18395595314** [comment]
ok
