### ISSUE TITLE
Bilibili升级弹幕协议

### ISSUE THREAD

**Issue by sion-x** [yjqiang/bili2.0#350]
bilibili似乎在昨天下午关闭了v1协议。目前bili2.0和danmu都挂掉了。~~隔壁的弹幕姬也挂掉了~~。~~但是DDTV没有挂.~~
具体表现为连接建立后很快断开
>[2020-04-10 16:31:17] 2 号数据连接异常或主动断开，正在处理剩余信息
>[2020-04-10 16:31:17] 2 号数据连接退出，剩余任务处理完毕
>[2020-04-10 16:31:17] 正在启动 2 号数据连接
>[2020-04-10 16:31:17] 2 号数据连接选择房间（24541）
>[2020-04-10 16:31:17] 2 号数据连接进入房间（24541）
>[2020-04-10 16:31:17] 2 号数据连接异常或主动断开，正在处理剩余信息
>[2020-04-10 16:31:17] 2 号数据连接退出，剩余任务处理完毕
>[2020-04-10 16:31:17] 正在启动 2 号数据连接

**Comment by zhufj1993** [comment]
是的，我刚上去看了下，的确是这样

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/346
