### ISSUE TITLE
无法完成主站任务

### ISSUE THREAD

**Issue by scyraxs** [yjqiang/bili2.0#351]
**问题描述**
时间:近几次更新后
task.toml为
### #输入数字 0-5 表示主站每日自动投币
givecoin = 5
### #数字表示投币最大尝试次数(如果根据up主投币的话，很可能最后发现硬币满了，投不动了，这是就需要限制尝试次数，否则会死循环)

givecoin_max_try_times = 25
### #av获取(bilitop或者uper)分别代表b站随机或者根据up主mid选取
fetchrule = "uper"
### # up主list([123]或者[123, 234, 123]等)
mid = [223902]

**截图或者视频或者报错文字**
True True 0 False
暂不支持 up 主 list，即将跳过本次主站任务
或者
True False 0 False
暂不支持 up 主 list，即将跳过本次主站任务

**必要的系统信息描述等**
python 版本以及系统版本信息
python3.7.4 termux0.73&python3.8 win10

**最近何时更新的脚本**
今天

**最后确认**
- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
暂时不支持主站的up主拉取视频后投币等，请更改task.toml文件
