### ISSUE TITLE
萌新向各位大佬请教一下配置文件（以task.toml为主）的用法/不是BUG

### ISSUE THREAD

**Issue by sr1y7** [yjqiang/bili2.0#352]
1.请问“直播心跳”和“心跳礼物”是什么？
是类似于老爷/会员挂机涨直播经验的那种吗？

2.请问“每日礼包”是什么？
零氪用户可以无视吗？

3.请问“动态抽奖”可以理解为天选时刻这类吗？

4.请问“实物抽奖”是什么？
只有某些活动期间才有用吗？

5.请问ctrl.toml中的默认监听房间号码，是不是相当于老爷/会员挂机长经验的常驻房间？

6.配置文件里面好像没有关于“摩天大楼”“任意门”“白羊座流星雨”“地图冒险”等抽奖类型，但是抽到的辣条有30天，7天，8天，2天等类型。
能否理解为这些抽奖实际上是有效的，只是没有单独的控制开关？

**Comment by shoucandanghehe** [comment]
3.动态抽奖就是B站的抽奖动态自动转发，不建议开（有封号风险）
4.实物抽奖貌似就是抽手机那一类的
6.应该是有的
（其实我也不太清楚，仅供参考，等yj大佬回答一下吧）

**Comment by Executor-Cheng** [comment]
4. 你为ロ.....？
你哪来那么多疑问啊，自己读代码。

**Comment by yawwwwwn** [comment]
“各位大佬” 不是 “B站客服”。抱歉，但是你走错了。

**Comment by yjqiang** [comment]
同意👆意见，这些问题更像是b站客服

**Comment by sr1y7** [comment]
感谢各位大佬的回答。但是读代码我真的是无能为力，我是c语言基础挂科的那种编程绝缘体。
