### ISSUE TITLE
登录失败，超时报错，验证码无效

### ISSUE THREAD

**Issue by wuzhong233** [yjqiang/bili2.0#354]
**问题描述**
在我使用此程序时，出现登录失败的情况
···
<class 'concurrent.futures._base.TimeoutError'>  https://passport.bilibili.com/api/v3/oauth2/login
此次登录出现验证码,识别结果为3mw3b
···
2020/4/12 12时

**截图或者视频或者报错文字**
```
此次登录出现验证码,识别结果为wpwn2
此次登录出现验证码,识别结果为5g68w
此次登录出现验证码,识别结果为ygfwb
此次登录出现验证码,识别结果为7axa6
此次登录出现验证码,识别结果为pxw2f
此次登录出现验证码,识别结果为nwd7y
......
```
**必要的系统信息描述等**
python 3.7.2 windows10 cmd控制台

**最近何时更新的脚本**
最新脚本

**最后确认**
- 

- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了

- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
登陆借口v3是极验了  暂时没有处理  v2是图像识别

**Comment by wuzhong233** [comment]
所以这是bug呢，还是版本限制，要换到旧版本

**Comment by yjqiang** [comment]
就是b站新接口是极验了  你可以认为是bug
