### ISSUE TITLE
"此次登录出现验证码,识别结果为*****"

### ISSUE THREAD

**Issue by beyond510** [yjqiang/bili2.0#355]
**再确认一次 issue 题目**
运行run.py即报错

> [2020-04-13 13:35:36] check_results:
> # <class 'tasks.login.LoginTask'>
> # ((-2, None),)
> 此次登录出现验证码,识别结果为y8nny
> 此次登录出现验证码,识别结果为bnmy
> 此次登录出现验证码,识别结果为585pa
> 此次登录出现验证码,识别结果为xeyf5
> 此次登录出现验证码,识别结果为2cn2x

**问题描述**
我挂在我闲置的一个电脑上了，所以没办法知道是什么时候开始的这个状态。我重新下载了文件，并且修改了B站密码，但还是这个状态。

**必要的系统信息描述等**
python 版本3.8
WIN1064位系统

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/354
