### ISSUE TITLE
持续获取验证码

### ISSUE THREAD

**Issue by holll** [yjqiang/bili2.0#356]
突然发现提示token可能过期，于是新建了一个user.toml文件重新登录
![截图](https://cdn.jsdelivr.net/gh/holll/cloudimg/mmexport1586766922717.jpg)

python3.8 win10云服务器

1小时前更新的代码

- [x] 我仔细看了requirements.txt，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
?你们是不会用issue么https://github.com/yjqiang/bili2.0/issues/354
