### ISSUE TITLE
不会自动去抢辣条，但是开宝箱等等功能都是正常的，且确定了参数没问题

### ISSUE THREAD

**Issue by zhufj1993** [yjqiang/bili2.0#357]
**再确认一次 issue 题目**
不会自动去抢辣条，但是开宝箱等等功能都是正常的，且确定了参数没问题。
说下详细情况，我在另一台主机上使用是没问题的，但是我重新换了一台主机安装后（安装过程中没有任何报错），不能自动抢辣条等道具（能领宝箱等），且已经确定过参数设置是没有问题，

**问题描述**
CMD里有一个OSError：（winError 995）由于线程退出或应用程序请求，已中止I/O操作

**截图或者视频或者报错文字**
截图请务必把名字等信息打码

**必要的系统信息描述等**
windows server 2012

**最近何时更新的脚本**
今天

**最后确认**
- [ ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ ] 我代码上次更新时间距今没有超过 2 个月以上
- [ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/257
