### ISSUE TITLE
B站弹幕又炸了？

### ISSUE THREAD

**Issue by 2604237845** [yjqiang/bili2.0#361]
![1](https://user-images.githubusercontent.com/54972064/79558563-eca7d480-80d6-11ea-9de4-e8c004cef242.png)

**Comment by Twoleaf** [comment]
403进休眠了，或到你设定的休眠时间了

**Comment by 2604237845** [comment]
> 403进休眠了，或到你设定的休眠时间了

我没设置休眠，休眠也不是这个提示

**Comment by yjqiang** [comment]
可能403吧，炸了不是这个样儿

**Comment by Darlingzero** [comment]
炸了

**Comment by shoucandanghehe** [comment]
B站弹幕服务器炸了
各种监控都炸了

**Comment by 2314933036** [comment]
46:08开始
![image](https://user-images.githubusercontent.com/38069007/79570936-e58bc100-80ec-11ea-96e5-fae29db8a4c8.png)

**Comment by SekiBetu** [comment]
> 46:08开始
> ![image](https://user-images.githubusercontent.com/38069007/79570936-e58bc100-80ec-11ea-96e5-fae29db8a4c8.png)

确实有这个现象，但是很久才会出现一次，认为是B站的服务器波动

**Comment by shoucandanghehe** [comment]
确实是B站问题
现在樱花监控直接停了
我自己的本项目附属监控一个直播间都连不上

**Comment by shoucandanghehe** [comment]
https://github.com/lkeme/BiliHelper-personal/issues/28
疑似B站限制了一个IP下最大弹幕链接量

**Comment by SekiBetu** [comment]
哔哩哔哩在20:30左右改了房间连接数，目前单机器只能连接8房间

**Comment by shoucandanghehe** [comment]
> 哔哩哔哩在20:30左右改了房间连接数，目前单机器只能连接8房间

好像放宽了点
我现在有700多链接了

**Comment by Executor-Cheng** [comment]
假的700吧，我才20条，20分钟之前最多8条

**Comment by pjy612** [comment]
> 假的700吧，我才20条，20分钟之前最多8条

感觉是 1-3分钟内 只允许5-8个连接进去的样子。。。

**Comment by shoucandanghehe** [comment]
> 假的700吧，我才20条，20分钟之前最多8条

```
root@home:~# netstat -n | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}'
LAST_ACK 31
CLOSE_WAIT 1
ESTABLISHED 814
FIN_WAIT1 3
TIME_WAIT 13
SYN_SENT 20
```
这台机子有两个子监控（本项目附属）

**Comment by shoucandanghehe** [comment]
另一台现在572

**Comment by azalaza** [comment]
> 另一台现在572

大佬是什么机器什么配置 我测试下康康

**Comment by shoucandanghehe** [comment]
> > 另一台现在572
> 
> 大佬是什么机器什么配置 我测试下康康

572的是
京东云2c4g5m
四个分布式子监控
每个监控4500房间

**Comment by shoucandanghehe** [comment]
两台都不往上涨了
甚至还掉了几个
B站真狠啊

**Comment by azalaza** [comment]
> 两台都不往上涨了
> 甚至还掉了几个
> B站真狠啊
多半是拉闸了 应该会慢慢掉 测试内大部分人 目前是最多8个

**Comment by shoucandanghehe** [comment]
我这涨上去了
800→1600
不过又在掉了
可能允许临时超过一定链接？

**Comment by shoucandanghehe** [comment]
嗯好
我两台机子都被拉闸了

**Comment by Silentely** [comment]
3台机子已断电 上香

**Comment by sr1y7** [comment]
今天发生更奇葩的事情了。
以前都是30天的辣条比2天的多，今天是2天的辣条远多于30天的辣条了。
是不是摩天大楼（原来是两天）和小电视（原来是30天）对调了，还是小电视出现漏抽或者部分封禁，总不会是今天的氪金大佬一反常态，变成摩天大楼比小电视多了？

**Comment by Executor-Cheng** [comment]
> 今天发生更奇葩的事情了。
> 以前都是30天的辣条比2天的多，今天是2天的辣条远多于30天的辣条了。
> 是不是摩天大楼（原来是两天）和小电视（原来是30天）对调了，还是小电视出现漏抽或者部分封禁，总不会是今天的氪金大佬一反常态，变成摩天大楼比小电视多了？

没错。小电视辣条改为2天了。

**Comment by yjqiang** [comment]
就是限制连接数目了23333
