### ISSUE TITLE
此次登录出现验证码,识别结果为xxxxx

### ISSUE THREAD

**Issue by poly000** [yjqiang/bili2.0#364]
2020.04.20 13:30 UTC+8:00
![Screenshot_20200420_133054](https://user-images.githubusercontent.com/34085039/79717098-3f69d200-830b-11ea-86b3-5250dd3b5f0b.png)

Python 3.8.2 
OS: Arch Linux x86_64 
Kernel: 5.6.4-zen1-1-zen 

几天前

**最后确认**
- [对 ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [对 ] 我代码上次更新时间距今没有超过 2 个月以上
- [对 ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ 对] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by poly000** [comment]
我只是为自己设置了一个弱密码，然后写进user.conf

**Comment by Twoleaf** [comment]
https://github.com/yjqiang/bili2.0/issues/354

**Comment by SekiBetu** [comment]
出现了滑块验证码了

**Comment by Alkitor** [comment]
我出现这个问题，等到第二天自己好了

**Comment by WLY513** [comment]
萌新也出现了同样的问题，请问各位大佬有解决办法吗

**Comment by WLY513** [comment]
我也出现这个问题，等到第三天自己好了

**Comment by wwh1004** [comment]
![image](https://user-images.githubusercontent.com/27536652/80917054-1e839100-8d8f-11ea-8340-5771d8b91e41.png)
一样登录不了

**Comment by WLY513** [comment]
您好，我的做法是，第一天一直登不上，第二天修改密码并且重新下载最新压缩包并安装但还是登不上，第三天可以正常使用（据说这是因为卡bug不停提交验证码导致IP被B站认为是垃圾信息，等几天就好了，期间尽量少开，千万不要一直挂着）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "文煌"<notifications@github.com&gt;; 
发送时间: 2020年5月3日(星期天) 晚上10:41
收件人: "yjqiang/bili2.0"<bili2.0@noreply.github.com&gt;; 
抄送: "璐小洋"<854691189@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [yjqiang/bili2.0] 此次登录出现验证码,识别结果为xxxxx (#364)





 

 一样登录不了
