### ISSUE TITLE
心跳包提示校验失败

### ISSUE THREAD

**Issue by JerryRich** [yjqiang/bili2.0#366]
**问题描述**
开始运行时出现问题

**截图或者视频或者报错文字**
![TIM图片20200422171352](https://user-images.githubusercontent.com/31468229/79964009-af6b8a00-84bc-11ea-866b-337cfbb5085f.png)

似乎不会对脚本的其他功能的运行产生影响

**必要的系统信息描述等**
python 3.8

**最近何时更新的脚本**
刚刚

**最后确认**
- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
现在还这样么。。。我这里一起正常

**Comment by JerryRich** [comment]
> 现在还这样么。。。我这里一切正常

现在正常了
