### ISSUE TITLE
程序不会做每日分享任务

### ISSUE THREAD

**Issue by GreatPull** [yjqiang/bili2.0#367]
![QQ截图20200425092320](https://user-images.githubusercontent.com/51036486/80267996-abb34f80-86d6-11ea-8f95-d483744b71d4.png)
emmm
就像图片这样，我挂了也有几天了，每天都看了，确定程序没做任务。

作者上岸之后就来管管吧~

**Comment by popo-bear** [comment]
估计是改BV闹的，你升级过版本吗，破站吧视频号给改了，分享如果还是老程序，没有那么视频了。

**Comment by someash** [comment]
yj大佬这段时间忙没法更新，想他

**Comment by yjqiang** [comment]
我这里好像还是正常的。。。

**Comment by GreatPull** [comment]
> 我这里好像还是正常的。。。

Emmmmm能不能考虑换一下每日分享的视频，或者加个检测是否分享了视频的机制

**Comment by yjqiang** [comment]
视频分享就是随机选视频的啊……

**Comment by yjqiang** [comment]
检测别想了  b站的参与与log记录延迟长达几小时
