### ISSUE TITLE
bili2.0上船亲密度适配

### ISSUE THREAD

**Issue by zhouxiaoxiao6** [yjqiang/bili2.0#37]

**Comment by zhouxiaoxiao6** [comment]
如果没有的话会考虑加上嘛？

**Comment by rabbit2rabbit** [comment]
检测到就有(ᵒ̴̶̷̤́◞౪◟ ᵒ̴̶̷̤̀ )

**Comment by zhouxiaoxiao6** [comment]
> 检测到就有（ᵒ̴̶̷̤◞4◟ᵒ̴̶̷̤）

默认检测到就有对吗，不需要调试或者干嘛？第一次用不懂。

**Comment by rabbit2rabbit** [comment]
检测到就会添加进任务了，会post的了

**Comment by zhouxiaoxiao6** [comment]
> 检测到就会添加进任务了，会后的了
大概率怎么样，漏船概率。

**Comment by yjqiang** [comment]
有  项目对接是yjmonitor  但是项目开源  接口不公开

**Comment by yjqiang** [comment]
此项目正在准备跟进beta以及对某些架构微调 目前还在测试

**Comment by yjqiang** [comment]
> > 有项目对接是yjmonitor但是项目开源接口不公开
> 
> 什么意思，听不太懂。意思大概是能检测上船会领亲密度，但是上船的项目源不公开？不知道我理解的对不对。

不是 上船的推送不是广播 所以我写了一个监控多个房间的项目yjmonitor 这个项目开源  监控到的结果会发到某个房间  这个房间不公开

**Comment by rabbit2rabbit** [comment]
不公开接口我写不出来。。。能偷偷py下吗٩(๑ᵒ̴̶̷͈᷄ᗨᵒ̴̶̷͈᷅)و

**Comment by zhouxiaoxiao6** [comment]
> 2.0暂时没有配接好 目前只有主项目可以 就是https://github.com/yjqiang/bilibili-live-tools

好的，了解了，谢谢。那2.0的话大概什么时候能配置好，能透露下嘛。还是，佛系。

**Comment by rabbit2rabbit** [comment]
emmm我只是想py代码，自从主项目某个对开发者友好的版本改动之后，函数名都大改了（我也偷懒没看代码了），后续版本都看不懂了

**Comment by yjqiang** [comment]
> > 2.0暂时没有配接好 目前只有主项目可以 就是https://github.com/yjqiang/bilibili-live-tools
> 
> 好的，了解了，谢谢。那2.0的话大概什么时候能配置好，能透露下嘛。还是，佛系。

手上的其他项目都基本暂停  接下来就主要做这个

**Comment by zhouxiaoxiao6** [comment]
> 目都基本暂停 接下来就主要做这个

好的，已知晓，谢谢。

**Comment by yjqiang** [comment]
> emmm我只是想py代码，自从主项目某个对开发者友好的版本改动之后，函数名都大改了（我也偷懒没看代码了），后续版本都看不懂了

老代码费劲看完了 新代码就懒得看了么……

**Comment by yjqiang** [comment]
> emmm我只是想py代码，自从主项目某个对开发者友好的版本改动之后，函数名都大改了（我也偷懒没看代码了），后续版本都看不懂了

相信我  基本没怎么动  主要就是把结构改了一下  然后就是yjmonitor这里对接  再就是改名

**Comment by rabbit2rabbit** [comment]
还是从之前改动的版本看起吧，或许看着看着2.0的新代码就出来了2333
学习使我快乐，学习使我沉迷，我爱学习（希望有个妹纸名字叫“学习”）(⃔ *`꒳´ * )⃕↝

**Comment by yjqiang** [comment]
> 还是从之前改动的版本看起吧，或许看着看着2.0的新代码就出来了2333
> 学习使我快乐，学习使我沉迷，我爱学习（希望有个妹纸名字叫“学习”）(⃔ *`꒳´ * )⃕↝

如果代码某个部分看得特别麻烦可能就是我写得不好  你就提出来

**Comment by rabbit2rabbit** [comment]
1

**Comment by rabbit2rabbit** [comment]
danmu.py完全就是新写的样子（这哪里是改的啊混蛋！）

**Comment by yjqiang** [comment]
本来就是啊……全改了

**Comment by zhouxiaoxiao6** [comment]
> > 不公开接口我写不出来。。。能偷偷py下吗٩(๑ᵒ̴̶̷͈᷄ᗨᵒ̴̶̷͈᷅)و
> 
> https://privnote.com/qxdzF15A#6VumIDIYE
> 这个链接里面是一个房间号 把它填写在主项目的user.toml里面 应该是最下面的一个roomid（有提示，默认是0）

这个链接可以在发一遍嘛，昨天由于没看懂，没有记住此链接房间号。

**Comment by yjqiang** [comment]
> > > 不公开接口我写不出来。。。能偷偷py下吗٩(๑ᵒ̴̶̷͈᷄ᗨᵒ̴̶̷͈᷅)و
> > 
> > https://privnote.com/qxdzF15A#6VumIDIYE
> > 这个链接里面是一个房间号 把它填写在主项目的user.toml里面 应该是最下面的一个roomid（有提示，默认是0）
> 
> 这个链接可以在发一遍嘛，昨天由于没看懂，没有记住此链接房间号。

https://privnote.com/2TT2rSPh#DhbmrBKyV

**Comment by rabbit2rabbit** [comment]
房间监控了多少房间？我可以开5-6个监控，需要我进行补位吗？末尾房间是第几热度房间

**Comment by yjqiang** [comment]
> 房间监控了多少房间？我可以开5-6个监控，需要我进行补位吗？末尾房间是第几热度房间

目前6k房间，暂时不需要了

**Comment by zhouxiaoxiao6** [comment]
> > 房间监控了多少房间？我可以开5-6个监控，需要我进行补位吗？末尾房间是第几热度房间
> 
> 目前6k房间，暂时不需要了

您好，麻烦您了，由于昨晚熬夜太晚，刚醒发现纸条内容已在一个小时前被读取。能私法我一份吗？邮箱424596240@qq.com 谢谢！
