### ISSUE TITLE
强制修改密码后无法使用

### ISSUE THREAD

**Issue by zk775622756** [yjqiang/bili2.0#370]
4月28日下午两点左右账号异常
修改密码后无法使用

<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host 152.32.186.69:19951 ssl:default [远程计 算机拒绝网络连接。] http://152.32.186.69:19951/captcha/v1

**Comment by shoucandanghehe** [comment]
验证码识别服务器问题

**Comment by wangmanv2** [comment]
同样情况出现账号密码都正确，验证码一直这样显示，似乎识别不正常。
![image](https://user-images.githubusercontent.com/42270394/80699365-6b0c6980-8b0e-11ea-85cf-1fa3cd464fb6.png)

**Comment by spiritLHL** [comment]
怎么解决

**Comment by yjqiang** [comment]
验证码服务器老的v2，现在滑动验证码目前没有公开的打码服务器
