### ISSUE TITLE
登入失败

### ISSUE THREAD

**Issue by tpq95** [yjqiang/bili2.0#371]
**问题描述**
登入失败

ermm 更新后，就有这个问题。可是我也没有改密码啊？
请问我需要做什么？

**截图或者视频或者报错文字**
![image](https://user-images.githubusercontent.com/31122808/80574073-bd2c8c80-8a33-11ea-80e4-ac21f9a531c2.png)

**最近何时更新的脚本**
几小时前

**Comment by shoucandanghehe** [comment]
确定是更新后发生的吗？？
应该是更新前有这个问题啊

**Comment by shoucandanghehe** [comment]
把账号改下密码顺便把脚本删掉重新下一次试试

**Comment by tpq95** [comment]
> 把账号改下密码顺便把脚本删掉重新下一次试试

谢谢你，脚本删掉了重新下就行了！
