### ISSUE TITLE
“xxxx遗漏推送统计”计算出错

### ISSUE THREAD

**Issue by Womsxd** [yjqiang/bili2.0#376]
**问题描述**
尽量详细叙述发生时间等

**截图或者视频或者报错文字**
截图请务必把名字等信息打码
![](https://i.loli.net/2020/05/05/roapkJBC1KvYDtz.png)
![](https://i.loli.net/2020/05/05/g3lZeIWHaBTuvi8.jpg)
如图所示
**必要的系统信息描述等**
python 版本以及系统版本信息
Python 3.8.1
Windows10
**最近何时更新的脚本**
几天前还是几小时前
前天
**最后确认**
- [√] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [√] 我代码上次更新时间距今没有超过 2 个月以上
- [√] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [√] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by S9zyne** [comment]
老哥问一下，舰队风暴覆盖率极低，是正常现象吗？

**Comment by shoucandanghehe** [comment]
@S9zyne #171

**Comment by Womsxd** [comment]
> 老哥问一下，舰队风暴覆盖率极低，是正常现象吗？

(自建监控服务器)
https://github.com/yjqiang/YjMonitor

(购买作者提供的)
https://github.com/yjqiang/bili2.0/issues/171

就行解决
