### ISSUE TITLE
 反复请求多次未成功

### ISSUE THREAD

**Issue by q123458384** [yjqiang/bili2.0#377]
反复请求多次未成功, http://152.32.186.69:19951/captcha/v1, {'json': {'image': '/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwxxxxxxxxxxxxxxxxxxxx='}}

access_key = ""
cookie = ""
csrf = ""
uid = ""
refresh_token = ""
这几个也没有自动生成

**Comment by scott90578** [comment]
账号异常出现滑动验证码了，等一两天后再试

**Comment by q123458384** [comment]
> 账号异常出现滑动验证码了，等一两天后再试

谢谢，应该是我前面输错密码导致的~
