### ISSUE TITLE
登录失败，是接口问题吗

### ISSUE THREAD

**Issue by lNeverl** [yjqiang/bili2.0#378]
# <class 'tasks.login.LoginTask'>

# ((-2, None),)
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host 152.32.186.69:19951 ssl:default [Connect call failed ('152.32.186.69', 19951)] http://152.32.186.69:19951/captcha/v1

![Snipaste_2020-05-05_23-14-24](https://user-images.githubusercontent.com/60817289/81082887-b7f29600-8ea8-11ea-8f76-b0dd286f5a8c.jpg)

**Comment by yjqiang** [comment]
是验证码，类似https://github.com/yjqiang/bili2.0/issues/364 ，等我考完吧
