### ISSUE TITLE
可以成功登录，但是后面出现请求频繁

### ISSUE THREAD

**Issue by GOOD-AN** [yjqiang/bili2.0#379]
出现以下提示：
403频繁, https://api.live.bilibili.com/room/v1/Area/getList

**Comment by GOOD-AN** [comment]
好似像ip封禁，用家里wifi无法正常进入直播间，电脑端只有直播画面，手机端直接412错误，切换到手机移动数据上恢复正常。

**Comment by Twoleaf** [comment]
被b站封IP了，一小时恢复

**Comment by GOOD-AN** [comment]
已恢复正常，感谢！
