### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by wwh1004** [yjqiang/bili2.0#381]
确定密码正确，issues里面说的改密码，隔几天登录，换ip都试过，还是登陆不上
账号也是我一个人在用

登录失败提示信息类型很多，有的时候会刷密码错误，有的时候刷一堆验证码

![Snipaste_2020-05-06_23-56-58](https://user-images.githubusercontent.com/27536652/81199473-47a55b00-8ff5-11ea-91e3-a574131ea586.png)

![Snipaste_2020-05-06_23-43-58](https://user-images.githubusercontent.com/27536652/81199501-4ecc6900-8ff5-11ea-820e-ce322501f1b7.png)

**Comment by wwh1004** [comment]
密码错误可能是之前测试输密码打错了，然后验证码的问题，又重启了几次路由器可以了

**Comment by lNeverl** [comment]
> 密码错误可能是之前测试输密码打错了，然后验证码的问题，又重启了几次路由器可以了

重启路由可以解决吗

**Comment by wwh1004** [comment]
> 重启路由可以解决吗

可以换IP，可能多试几次就可以，我前几次都失败了
