### ISSUE TITLE
引用其他py文件时，建议添加__init__.py 以包的方式引入

### ISSUE THREAD

**Issue by skymilong** [yjqiang/bili2.0#382]
__init__.py 只用是一个空文件即可,__init__.py的作用是标识一个文件夹是一个 python包

![](https://user-images.githubusercontent.com/22849197/81541681-17b7d800-93a6-11ea-8fea-9ab2298c22f3.png)

**Comment by yjqiang** [comment]
嗯 我一直这么干着，有时间研究一下，谢谢
