### ISSUE TITLE
无法连接网址   2020-5-12 python3.7环境

### ISSUE THREAD

**Issue by spiritLHL** [yjqiang/bili2.0#383]
![QQ图片20200512092620](https://user-images.githubusercontent.com/62994705/81628250-b5f17f80-9432-11ea-9a57-6e5b5308ac7f.png)

未知错误，尝试修改name为电话号了，但是一样报错，之前曾经输错过name。
错误提示
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host 152.32.186.69:19951 ssl:default [Connect call failed ('152.32.186.69', 19951)] http:

**Comment by spiritLHL** [comment]
已解决，等待一天即可，一定不要输错账号或密码，不然就得等一天了，血的教训。

**Comment by yjqiang** [comment]
打码的是v2  没法用了  现在是滑动验证码 https://github.com/yjqiang/bili2.0/issues/306
