### ISSUE TITLE
清理即将过期礼物功能能否自定义要投喂的勋章和投喂顺序

### ISSUE THREAD

**Issue by ChengnanYu** [yjqiang/bili2.0#385]
由于破站把大航海亲密度改成了一天辣条，所以想开启“清理即将过期礼物”功能。然而目前该功能只支持投喂所有勋章，能否自定义要投喂的勋章，比如已满20级的勋章不再投喂或者直接通过uid来定义。而且目前投喂顺序是按照勋章等级大小顺序，能否自定义投喂的顺序？

**Comment by Enderwaiter** [comment]
可以通过设置投喂自己直播间防止礼物流失配合设置UID投喂牌子的策略解决
![Alt text](https://s1.ax1x.com/2020/05/15/YDzyXF.png "如何设置")

**Comment by Enderwaiter** [comment]
另外还建议把bili_sched.py内的日常任务装载调整为15min装载一次 如果是一个小时的话在十二点装载的时候辣条已经过期了= =

**Comment by SekiBetu** [comment]
> 另外还建议把bili_sched.py内的日常任务装载调整为15min装载一次 如果是一个小时的话在十二点装载的时候辣条已经过期了= =



> 可以通过设置投喂自己直播间防止礼物流失配合设置UID投喂牌子的策略解决
> ![Alt text](https://camo.githubusercontent.com/491f7df0186e97c5a7ff7c4b3827a7c0b31ea986/68747470733a2f2f73312e617831782e636f6d2f323032302f30352f31352f59447a7958462e706e67)

过期时间设成半天不就行了，这个图里250万秒什么鬼

**Comment by Enderwaiter** [comment]
> > 另外还建议把bili_sched.py内的日常任务装载调整为15min装载一次 如果是一个小时的话在十二点装载的时候辣条已经过期了= =
> 
> > 可以通过设置投喂自己直播间防止礼物流失配合设置UID投喂牌子的策略解决
> > ![Alt text](https://camo.githubusercontent.com/491f7df0186e97c5a7ff7c4b3827a7c0b31ea986/68747470733a2f2f73312e617831782e636f6d2f323032302f30352f31352f59447a7958462e706e67)
> 
> 过期时间设成半天不就行了，这个图里250万秒什么鬼

因为我设置的29天过期啊= =就不用我管辣条了 每天都全部投喂出去了

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/master/conf/task.sample.toml#L51
这个不行么，这个可以允许你自己设置具体哪一个勋章

**Comment by Enderwaiter** [comment]
> https://github.com/yjqiang/bili2.0/blob/master/conf/task.sample.toml#L51
> 这个不行么，这个可以允许你自己设置具体哪一个勋章

估计没看到吧= =不过建议把投喂也独立出来一个定时函数如何？设置成15min执行一次任务一天签到24*4次好傻233
我现在为了能在过期前投喂出去就设置了每日任务15min执行一次

**Comment by yjqiang** [comment]
@Enderwaiter 投喂那里时间你自己覆盖就行。独立是啥？

**Comment by Enderwaiter** [comment]
> @Enderwaiter 投喂那里时间你自己覆盖就行。独立是啥？

明白了 因为我是让每日任务15min工作一次了 没去改投喂那里
