### ISSUE TITLE
B站发了官方公告，禁止第三方工具抢辣条

### ISSUE THREAD

**Issue by TOM1995b** [yjqiang/bili2.0#386]
b站已经禁止第三方工具抢辣条，违禁有可能会封号，如果第三方工具不能很好躲过检测，建议出个不抢辣条，只升级的配置选项，比如投币，转发之类的任务。最近严打，且行且珍惜:persevere:

**Comment by 2314933036** [comment]
conf/task.toml
自己改去,注释都写的很清楚了
join_tv_raffle = 0  # 小电视 tv_raffle_handler.py

**Comment by popo-bear** [comment]
> b站已经禁止第三方工具抢辣条，违禁有可能会封号，如果第三方工具不能很好躲过检测，建议出个不抢辣条，只升级的配置选项，比如投币，转发之类的任务。最近严打，且行且珍惜

辣条就是
TV=0（因为多数抽奖按小电视处理，关这一个等于几乎全部）  
舰队=0（亲密度没了都是辣条所以也要关掉）

频繁访问如果怕的话，把实物抽=0、心跳包都=0。
