### ISSUE TITLE
登陆失败反复请求多次未成功

### ISSUE THREAD

**Issue by scyraxs** [yjqiang/bili2.0#387]
**问题描述**
2020.05.18
尝试登录反复请求多次未成功

**截图或者视频或者报错文字**
![S00518-23250448](https://user-images.githubusercontent.com/49806577/82231268-80332600-995f-11ea-9a75-3d19ab99bff5.jpg)

**必要的系统信息描述等**
python 3.8.2 android9 termux0.94

**最近何时更新的脚本**
2020.05.18 23点

**最后确认**
- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by xiaozou416** [comment]
多试几次？

**Comment by xuanfeng6119** [comment]
看下这个https://github.com/yjqiang/bili2.0/issues/306

**Comment by zhongfly** [comment]
验证码服务器挂了

**Comment by xiaozou416** [comment]
免费的打码服务器拉闸了而已之前并没有看到图2333

**Comment by xiaozou416** [comment]
可以关掉一天第二天再登录看看要不要验证码

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/306
