### ISSUE TITLE
登录需最新客户端验证

### ISSUE THREAD

**Issue by scyraxs** [yjqiang/bili2.0#388]
**问题描述**
2020.05.19
无法登陆，会提示需要最新客户端验证
**截图或者视频或者报错文字**
![S00519-06341203(1)(1)](https://user-images.githubusercontent.com/49806577/82266294-e89ff880-999b-11ea-9085-1583d676239e.png)
![20200518_224739(1)](https://user-images.githubusercontent.com/49806577/82266300-ed64ac80-999b-11ea-8cd2-559e5ec54126.jpg)

**必要的系统信息描述等**
python 3.8.2 android9 termux0.94

**最近何时更新的脚本**
05.19 06点更新

**Comment by zhongfly** [comment]
https://github.com/yjqiang/bili2.0/issues/306

**Comment by pjy612** [comment]
设备检测关一下？

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/306
