### ISSUE TITLE
循环数据连接异常或主动断开

### ISSUE THREAD

**Issue by CharlesLi9527** [yjqiang/bili2.0#389]
**问题描述**
5月18日下午突然开始  1–6号数据无限重启 

**截图或者视频或者报错文字**
![mmexport1589957542132](https://user-images.githubusercontent.com/60460119/82414613-e7f58800-9aa9-11ea-85f6-b75fbdb12093.jpg)

**必要的系统信息描述等**
python 3.7

**最近何时更新的脚本**
几天前还是几小时前

**最后确认**
- [ √] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ √] 我代码上次更新时间距今没有超过 2 个月以上
- [ √] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ √] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
这边正常。。。

**Comment by yjqiang** [comment]
你是不是改了 ctrl.toml 文件里面的 `default_monitor_roomid` ?

**Comment by yjqiang** [comment]
你是一直重启？还是偶尔重启？

**Comment by CharlesLi9527** [comment]
> 你是一直重启？还是偶尔重启？

一直重启 没法用 裂开

**Comment by yjqiang** [comment]
建议你重下，我没有这个问题

**Comment by LuguoHu-Hu** [comment]
我的也是这样的问题，请问解决了吗？

**Comment by CharlesLi9527** [comment]
> 个

解决了 重装了然后改了密码 就好了

**Comment by yjqiang** [comment]
.....
