### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Kjcdkcnjji** [yjqiang/bili2.0#39]
PS E:\N\VPS1> python .\0.py
Traceback (most recent call last):
  File ".\0.py", line 28, in <module>
    dict_user = cfg.read_user()
  File "E:\N\VPS1\config_loader.py", line 71, in read_user
    dict_user = toml.load(f)
  File "C:\Users\Haruna\AppData\Local\Programs\Python\Python37\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "C:\Users\Haruna\AppData\Local\Programs\Python\Python37\lib\site-packages\toml\decoder.py", line 227, in loads
    original, i)
toml.decoder.TomlDecodeError: Found invalid character in key name: '['. Try quoting the key name. (line 1 column 2 char 1)

**Comment by rabbit2rabbit** [comment]
读取user配置文件的时候，行1列2的第一个字符是非法字符，检查下

**Comment by yjqiang** [comment]
发现他的文件我复制了一下文字  复制到了pythonista里面  然后回传 解决   猜测可能是中英文之类的问题  目前仍不明确   先开着

**Comment by yjqiang** [comment]
复现了 删了第一行的方括号手动打  正常了  怀疑可能特色符号了吧

**Comment by Kjcdkcnjji** [comment]
> > 我这边又出现了 并且换了机器还是不行 删除第一行的方括号手动打也不行
> 
> 文件qq给我

我这边新建了个空的user文件 然后把原来的复制进去替换就解决了 很迷

**Comment by yjqiang** [comment]
类似WINDOWS自带的记事本等软件，在保存一个以UTF-8编码的文件时，会在文件开始的地方插入三个不可见的字符（0xEF 0xBB 0xBF，即BOM）。它是一串隐藏的字符，用于让记事本等编辑器识别这个文件是否以UTF-8编码。对于一般的文件，这样并不会产生什么麻烦。但对于 PHP来说，BOM是个大麻烦
`with open('user(13).toml', encoding='utf-8-sig') as f:
    dic_user = toml.load(f)`

**Comment by yjqiang** [comment]
['\ufeff', '[', '[', 'u', 's', 'e', 'r', 's', ']', ']'

**Comment by yjqiang** [comment]
千万不要在记事本等里面打开文件了

**Comment by Kjcdkcnjji** [comment]
> 类似WINDOWS自带的记事本等软件，在保存一个以UTF-8编码的文件时，会在文件开始的地方插入三个不可见的字符（0xEF 0xBB 0xBF，即BOM）。它是一串隐藏的字符，用于让记事本等编辑器识别这个文件是否以UTF-8编码。对于一般的文件，这样并不会产生什么麻烦。但对于 PHP来说，BOM是个大麻烦
> `with open('user(13).toml', encoding='utf-8-sig') as f: dic_user = toml.load(f)`

非常感谢
