### ISSUE TITLE
最新更新使用报错

### ISSUE THREAD

**Issue by Gensokyo1995** [yjqiang/bili2.0#390]
**问题描述** 
Python run.py后报错，上一个版本没问题

报错代码
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    import notifier
  File "C:\软件\bili2.0-master\notifier.py", line 8, in <module>
    from user.user import User
ModuleNotFoundError: No module named 'user.user'; 'user' is not a package

**最近何时更新的脚本**
最新版本

**最后确认**
- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
一级文件里面的 user.py 删掉
