### ISSUE TITLE
403频繁

### ISSUE THREAD

**Issue by GreatPull** [yjqiang/bili2.0#391]
就看图吧
![Screenshot_20200528_065509.jpg](https://i.loli.net/2020/05/28/aQXMFlV92wOueYp.jpg)

**Comment by yjqiang** [comment]
无解

**Comment by xiaozou416** [comment]
可以手动拨号更换ip

**Comment by popo-bear** [comment]
6点，没遇到过，楼主是在外国吗。   403一般出现在凌晨舰队起航模式下，0点集团上舰，我最短只坚持了22秒。   0点0分22秒 403              0点2分PY停止
