### ISSUE TITLE
运行后notifier.py第8行报错

### ISSUE THREAD

**Issue by wzxyisme** [yjqiang/bili2.0#394]
**再确认一次 issue 题目**
请记得把 issue 标题改成问题描述的概述，而不是简单的一句话，《电脑开不了了》、《闪退了》、《救命啊》这些

**问题描述**
尽量详细叙述发生时间等
几分钟前

**截图或者视频或者报错文字**
C:\Users\19253\Desktop\Desktop\bili2.0-wzxy>python run.py
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    import notifier
  File "C:\Users\19253\Desktop\Desktop\bili2.0-wzxy\notifier.py", line 8, in <module>
    from user.user import User
ModuleNotFoundError: No module named 'user.user'; 'user' is not a package

![image](https://user-images.githubusercontent.com/45878990/83316911-78c32500-a25b-11ea-81bd-00cb016055cf.png)
![image](https://user-images.githubusercontent.com/45878990/83317023-5a115e00-a25c-11ea-845c-8c9fd89e9956.png)

**必要的系统信息描述
Windows10专业版
python 3.8.3
pip 20.1.1

**最近何时更新的脚本**
几天前还是几小时前
几分钟前，覆盖安装
**最后确认**
- [✓ ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [✓ ] 我代码上次更新时间距今没有超过 2 个月以上
- [✓ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [✓ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/390
