### ISSUE TITLE
运行时偶尔出现：在一个非套接字上尝试了一个操作

### ISSUE THREAD

**Issue by Womsxd** [yjqiang/bili2.0#398]
**再确认一次 issue 题目**
请记得把 issue 标题改成问题描述的概述，而不是简单的一句话，《电脑开不了了》、《闪退了》、《救命啊》这些

**问题描述**
尽量详细叙述发生时间等
运行的时候偶尔会出现：在一个非套接字上尝试了一个操作
然后就是报错刷屏
重启脚本就能正常运行
**截图或者视频或者报错文字**
截图请务必把名字等信息打码
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
[2020-06-07 08:43:33] 反复请求多次未成功, https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join, {'data': {'roomid': 房间号, 'id': 礼物ID, 'type': '类型', 'csrf_token': 'Token'}, 'headers': {这里是header}}
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
[2020-06-07 08:43:34] 反复请求多次未成功, https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join, {'data': {'roomid': 房间号, 'id': 礼物ID, 'type': '类型', 'csrf_token': 'Token'}, 'headers': {这里是header}}
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
[2020-06-07 08:43:35] 反复请求多次未成功, https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join, {'data': {'roomid': 房间号, 'id': 礼物ID, 'type': '类型', 'csrf_token': 'Token'}, 'headers': {这里是header}}
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
[2020-06-07 08:43:36] 反复请求多次未成功, https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join, {'data': {'roomid': 房间号, 'id': 礼物ID, 'type': '类型', 'csrf_token': 'Token'}, 'headers': {这里是header}}
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host api.live.bilibili.com:443 ssl:default [ 在一个非套接字上尝试了一个操作。] https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join
[2020-06-07 08:43:36] 反复请求多次未成功, https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join, {'data': {'roomid': 房间号, 'id': 礼物ID, 'type': '类型', 'csrf_token': 'Token'}, 'headers': {这里是header}}
**必要的系统信息描述等**
python 版本以及系统版本信息
Python 3.8.1
Win10 1909 x86版本
Wifi连接
**最近何时更新的脚本**
几天前还是几小时前
9天前吧
**最后确认**
- [√ ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ √] 我代码上次更新时间距今没有超过 2 个月以上
- [ √] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ √] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
看起来只是单纯的网络波动

**Comment by GOOD-AN** [comment]
这个应该是由于网络原因，一般情况下，关闭并等待两小时以上可恢复

**Comment by Womsxd** [comment]
> 这个应该是由于网络原因，一般情况下，关闭并等待两小时以上可恢复

等2小时应该是403错误，我服务器最近碰到了
