### ISSUE TITLE
最新版本启动时报错

### ISSUE THREAD

**Issue by Superexboom** [yjqiang/bili2.0#399]
环境Centos7 Python版本：3.7.0（已更新过Requirement）
报错如下：
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    import notifier
  File "/root/bili2.0-master/notifier.py", line 8
, in <module>
    from user.user import User
ModuleNotFoundError: No module named 'user.user';
 'user' is not a package

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/390
