### ISSUE TITLE
自动送快过期礼物好像一次性全送掉了...

### ISSUE THREAD

**Issue by 2314933036** [yjqiang/bili2.0#4]

**Comment by 2314933036** [comment]
而且好像只有一个帐号在送,我在观察观察.

**Comment by 2314933036** [comment]
![sbs 3hsujl 9ldvn k 3u6g](https://user-images.githubusercontent.com/38069007/42736038-340d50a6-8891-11e8-9b62-6989e8043c6b.png)
![e mtnwh tdiai5pr rpj](https://user-images.githubusercontent.com/38069007/42736040-3a8b62c4-8891-11e8-9206-1e2ad77c7677.png)
下面是user.toml的部分

**Comment by yjqiang** [comment]
查了很久，仍然不清楚问题点

**Comment by Jutean** [comment]
是不是你佩戴了别的徽章？

**Comment by yjqiang** [comment]
过于久远了…  我觉得没啥必要了好像
