### ISSUE TITLE
无法参与大航海

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bili2.0#41]
检测到航海，却无法参与领取，原因未知，猜测是api的更改
（暂没空检查）

**Comment by yjqiang** [comment]
昨晚的时候仍然正常领取

**Comment by rabbit2rabbit** [comment]
目前来说无法领取，重启0.py也同样

**Comment by yjqiang** [comment]
今天测试  完全正常

**Comment by yjqiang** [comment]
你看看有什么返回值

**Comment by rabbit2rabbit** [comment]
![image](https://user-images.githubusercontent.com/42423154/51664604-c17a2680-1ff4-11e9-92a1-63c0fe3e515e.png)
这里的print没有输出结果，空白的
![image](https://user-images.githubusercontent.com/42423154/51664857-61d04b00-1ff5-11e9-81a2-7bf60ca3aaf0.png)

**Comment by yjqiang** [comment]
你自己在开头加入一些print，最新版没有问题

**Comment by yjqiang** [comment]
如果你自己修改过代码，请自行debug

**Comment by rabbit2rabbit** [comment]
403……我错了……
