### ISSUE TITLE
似乎检测到的小电视有领不到的情况

### ISSUE THREAD

**Issue by GaugeAndGravity** [yjqiang/bili2.0#412]
**问题描述**
见下，今天看了一眼拿来跑这个程序的旧电脑，发现检测到很多小电视，但 check_results 是空的，也领不到辣条

**截图或者视频或者报错文字**
这是输出，空的`[]`应该不对吧
```
[2020-07-27 11:38:30] 6 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 5 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 1 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 5 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 2 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 2 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 4 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 1 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 3 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 4 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 3 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:30] 6 号数据连接检测到  90713  的小电视
[2020-07-27 11:38:33] check_results:
# <class 'tasks.tv_raffle_handler.TvRaffleJoinTask'>
# []
```

**必要的系统信息描述等**
python3 + win 64bit

**最近何时更新的脚本**
保持最新

**最后确认**
- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by xiashu233** [comment]
我的也领不到了 
本次推送抽奖统计：
 161  X 小电视
1.00  X 总督

本次参与抽奖统计：
  1   X 小电视(合计)

本次抽奖结果统计：
  5   X 辣条

**Comment by SekiBetu** [comment]
害，8月底最终改版之后，辣条除了签到获得，其他渠道都没有了，现在是小心心的时代，一个顶50个

**Comment by GaugeAndGravity** [comment]
> 害，8月底最终改版之后，辣条除了签到获得，其他渠道都没有了，现在是小心心的时代，一个顶50个

！

**Comment by linguo2625469** [comment]
已经改版了

**Comment by popo-bear** [comment]
> **问题描述**
> 见下，今天看了一眼拿来跑这个程序的旧电脑，发现检测到很多小电视，但 check_results 是空的，也领不到辣条
> 
> **截图或者视频或者报错文字**
> 这是输出，空的`[]`应该不对吧
> 
> ```
> [2020-07-27 11:38:30] 6 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 5 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 1 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 5 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 2 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 2 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 4 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 1 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 3 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 4 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 3 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:30] 6 号数据连接检测到  90713  的小电视
> [2020-07-27 11:38:33] check_results:
> # <class 'tasks.tv_raffle_handler.TvRaffleJoinTask'>
> # []
> ```
> 
> **必要的系统信息描述等**
> python3 + win 64bit
> 
> **最近何时更新的脚本**
> 保持最新
> 
> **最后确认**
> 
> * [x]  我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
> * [x]  我代码上次更新时间距今没有超过 2 个月以上
> * [x]  我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
> * [x]  我仔细检查了 readme 最近更新情况，并查看了最近更新内容

小电视已经没有抽奖了，舰队也没有了，大楼也没有。

**Comment by popo-bear** [comment]
> 我的也领不到了
> 本次推送抽奖统计：
> 161 X 小电视
> 1.00 X 总督
> 
> 本次参与抽奖统计：
> 1 X 小电视(合计)
> 
> 本次抽奖结果统计：
> 5 X 辣条

8月1日起，所有礼物舰队将不再掉落任何宝箱及抽奖，现在逐步在该，每天都不同。  这5个条子，有可能是生日会流星雨或者是任意门。

**Comment by GaugeAndGravity** [comment]
> > **问题描述**
> > 见下，今天看了一眼拿来跑这个程序的旧电脑，发现检测到很多小电视，但 check_results 是空的，也领不到辣条
> > **截图或者视频或者报错文字**
> > 这是输出，空的`[]`应该不对吧
> > ```
> > [2020-07-27 11:38:30] 6 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 5 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 1 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 5 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 2 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 2 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 4 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 1 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 3 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 4 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 3 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:30] 6 号数据连接检测到  90713  的小电视
> > [2020-07-27 11:38:33] check_results:
> > # <class 'tasks.tv_raffle_handler.TvRaffleJoinTask'>
> > # []
> > ```
> > 
> > 
> > **必要的系统信息描述等**
> > python3 + win 64bit
> > **最近何时更新的脚本**
> > 保持最新
> > **最后确认**
> > 
> > * [x]   我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
> > * [x]   我代码上次更新时间距今没有超过 2 个月以上
> > * [x]   我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
> > * [x]   我仔细检查了 readme 最近更新情况，并查看了最近更新内容
> 
> 小电视已经没有抽奖了，舰队也没有了，大楼也没有。

已经了解了
