### ISSUE TITLE
登陆接口失效：http://152.32.186.69:19951/captcha/v1

### ISSUE THREAD

**Issue by KNulL0** [yjqiang/bili2.0#414]
ConnectorError'> Cannot connect to http://152.32.186.69:19951/captcha/v1

- [ ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ ] 我代码上次更新时间距今没有超过 2 个月以上
- [ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by idayske** [comment]
我的也是  自从昨天开始  登录接口就失效了

**Comment by Kirito-F** [comment]
同，大约在29日凌晨，我手动查询勋章状态，然后就报错了...等了半天终于有issue出来了...还以为又是我电脑问题呢23333

**Comment by idayske** [comment]
暂时用了另一个大佬的  但是那个没风纪委员  就难受

**Comment by Kirito-F** [comment]
> 暂时用了另一个大佬的 但是那个没风纪委员 就难受

啊这[doge]

**Comment by xiaozou416** [comment]
这个是打码服务器拉闸（登录时出现了验证码就会进行打码）打码服务器是v2字母的打码 2.0现在用的是v3的登录接口（极验）可以试试拨号更换一下本地ip登录试试

**Comment by yjqiang** [comment]
现在是极验了，这个接口是图片识别那个老的，其实没用了

**Comment by idayske** [comment]
没办法更换ip   用的云服务器
