### ISSUE TITLE
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host... 

### ISSUE THREAD

**Issue by LeapOverSea** [yjqiang/bili2.0#415]
之前的token过期了，重新下载了bili2.0，无法登录，显示如下
`<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host 152.32.186.69:19951 ssl:default [Connect call failed ('152.32.186.69', 19951)] http://152.32.186.69:19951/captcha/v1
`
![QQ图片20200730203934](https://user-images.githubusercontent.com/41534045/88924000-2cb94e80-d2a5-11ea-8c2b-82336853312f.png)

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/414
