### ISSUE TITLE
启动时无法登录报错

### ISSUE THREAD

**Issue by SYSUHZR** [yjqiang/bili2.0#417]
![image](https://user-images.githubusercontent.com/58602296/89000326-a98e0c00-d329-11ea-8104-6475c1306da2.png)

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/416

**Comment by SYSUHZR** [comment]
@yjqiang 不好意思，注释掉103行结果出现了新的问题呜呜呜
![image](https://user-images.githubusercontent.com/58602296/89045129-91e07300-d37d-11ea-9e33-06a5a1cac2a5.png)
