### ISSUE TITLE
辣条问题

### ISSUE THREAD

**Issue by s282730788** [yjqiang/bili2.0#418]
这几个月都很正常，1天到期的辣条平均每天都能2000+，但几天前开始就抽不到辣条了，1天到期的辣条就几个，30天到期的辣条10到100不等，感觉B站把规则改了，重新下载了脚本也没用

**Comment by SekiBetu** [comment]
哇塞，你也在网上冲浪啊，你是GG还是MM啊？

**Comment by someash** [comment]
辣条基本没了兄弟们，就还省点亿元

**Comment by yjqiang** [comment]
白嫖时代过去了

**Comment by s282730788** [comment]
> 白嫖时代过去了

猛男落泪...  感谢大佬脚本让我白嫖了这么久辣条
