### ISSUE TITLE
<class 'concurrent.futures._base.TimeoutError'>  http://152.32.186.69:19951/captcha/v1

### ISSUE THREAD

**Issue by adsslmy** [yjqiang/bili2.0#419]
[2020-08-01 21:14:50] check_results:
# <class 'tasks.login.LoginTask'>
# ((-2, None),)
<class 'concurrent.futures._base.TimeoutError'>  http://152.32.186.69:19951/captcha/v1

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/416
