### ISSUE TITLE
依然无法登录（416的方案无法解决）

### ISSUE THREAD

**Issue by SYSUHZR** [yjqiang/bili2.0#421]
![image](https://user-images.githubusercontent.com/58602296/89121564-79de3000-d4f2-11ea-9a4c-e809cd1788f2.png)
![image](https://user-images.githubusercontent.com/58602296/89121595-b6119080-d4f2-11ea-960f-89165553ebf4.png)
已经把103行注释掉了，依然无法解决问题

**Comment by idayske** [comment]
可以参考这个https://github.com/Dawnnnnnn/bilibili-live-tools/issues/328#issuecomment-667630199

**Comment by SYSUHZR** [comment]
> 可以参考这个[Dawnnnnnn/bilibili-live-tools#328 (comment)](https://github.com/Dawnnnnnn/bilibili-live-tools/issues/328#issuecomment-667630199)

![image](https://user-images.githubusercontent.com/58602296/89123868-27f2d580-d505-11ea-9ee4-069d09f415f1.png)
![image](https://user-images.githubusercontent.com/58602296/89123882-4527a400-d505-11ea-96da-6f0140b40fda.png)
登录成功，但参与不了抽奖

**Comment by idayske** [comment]
我只用每日主站任务  直播模块不清楚

**Comment by Twoleaf** [comment]
> > 可以参考这个[Dawnnnnnn/bilibili-live-tools#328 (comment)](https://github.com/Dawnnnnnn/bilibili-live-tools/issues/328#issuecomment-667630199)
> 
> ![image](https://user-images.githubusercontent.com/58602296/89123868-27f2d580-d505-11ea-9ee4-069d09f415f1.png)
> ![image](https://user-images.githubusercontent.com/58602296/89123882-4527a400-d505-11ea-96da-6f0140b40fda.png)
> 登录成功，但参与不了抽奖

道具奖励上个月就取消了，哪里还有参与

**Comment by popo-bear** [comment]
> > 可以参考这个[Dawnnnnnn/bilibili-live-tools#328 (comment)](https://github.com/Dawnnnnnn/bilibili-live-tools/issues/328#issuecomment-667630199)
> 
> ![image](https://user-images.githubusercontent.com/58602296/89123868-27f2d580-d505-11ea-9ee4-069d09f415f1.png)
> ![image](https://user-images.githubusercontent.com/58602296/89123882-4527a400-d505-11ea-96da-6f0140b40fda.png)
> 登录成功，但参与不了抽奖

8月1日起，所有礼物、舰队不在掉落任何宝箱及抽奖，公告内容。         但是不绝对，是绝大多数都下架了，少数还有的，生日会、冯提莫还是会产生一些少量辣条，全天最多时候200，全天最少时候几十。    舰队是一毛不拔了，所有舰队没有亲密度、没有奖励，小电视不产生抽奖项目。

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/pull/427
