### ISSUE TITLE
银瓜子兑换硬币和风纪委员投票失效

### ISSUE THREAD

**Issue by dantesawake** [yjqiang/bili2.0#423]
**问题描述**
[2020-08-06 18:45:42] 银瓜子兑换为硬币：invalid request
[2020-08-06 18:45:51] 本次未获取到案件
并且一直获取不到案件，大概持续了三天

**必要的系统信息描述等**
python 3.7

**最近何时更新的脚本**
几分钟前

**Comment by idayske** [comment]
我的没有问题

**Comment by Azurlane-a** [comment]
没案件是风纪委那边的确没案件，可以考虑凌晨开 或者早上开 就有了。

**Comment by dantesawake** [comment]
啊这上个版本的问题，这个版本就好了
