### ISSUE TITLE
登录不了咋回事# <class 'tasks.login.LoginTask'> # ((-2, None),) 

### ISSUE THREAD

**Issue by qazgp** [yjqiang/bili2.0#424]
# <class 'tasks.login.LoginTask'>
# ((-2, None),)
<class 'concurrent.futures._base.TimeoutError'>  http://152.32.186.69:19951/captcha/v1
这里报错

**Comment by 2284787774** [comment]
我也是卡这里报错，感觉是因为最近B站登录要手动点图片验证的问题

**Comment by Azurlane-a** [comment]
同样无法登陆，换IP也不行 电信的。之前联通的换IP可登陆。

**Comment by HYY-zh** [comment]
同样卡v1，issues里面的方法都试过也没啥用，只能等作者修了

**Comment by q123458384** [comment]
我也是卡b1“反复请求多次未成功, xxx/captcha/v1”

**Comment by LuguoHu-Hu** [comment]
我也是卡在这里，问题有解决吗？

**Comment by ggaa1000** [comment]
一样的问题

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/pull/427
