### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by EdwardXiaoran** [yjqiang/bili2.0#426]
无法登录，推测为V1登录接口已经凉了，但根据bilibili-toolkit的日志推测可以用V3接口登录，但我不知道这里如何调整登录接口
有没有大佬指点下？

**必要的系统信息描述等**
Python 3.8.1 Win10 1909

**最近何时更新的脚本**
今天

**最后确认**
- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/pull/427
