### ISSUE TITLE
直播再次改版，取消开宝箱领瓜子

### ISSUE THREAD

**Issue by GOOD-AN** [yjqiang/bili2.0#429]
直播改版，取消开宝箱领瓜子，但是目前程序会不停请求，会直接导致403频繁

**Comment by popo-bear** [comment]
你把任务关掉不完了，task里的宝箱任务-1 改为 0

**Comment by GOOD-AN** [comment]
> 你把任务关掉不完了，task里的宝箱任务-1 改为 0
> 
> open_silver_box = 0  # 直播宝箱 live_daily_job.py

忘了。。。多谢提醒
