### ISSUE TITLE
每日任务中的每日投币没有作用，其它的都是正常，请作者看看是什么原因，谢谢作者。

### ISSUE THREAD

**Issue by powermill** [yjqiang/bili2.0#431]
**再确认一次 issue 题目**
确认

**问题描述**
在目前最新版的程序中，每日任务中的每日投币没有执行，其它的都是正常

**截图或者视频或者报错文字**
无报错内容

**必要的系统信息描述等**
python3.7
windows7

**最近何时更新的脚本**
目前最新脚本

**最后确认**
- [V ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [V ] 我代码上次更新时间距今没有超过 2 个月以上
- [V ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [V ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by vbtueli** [comment]
我的每日投币是正常的，你之前有成功过吗??

**Comment by powermill** [comment]
这个python程序，我刚开始使用，每日投币一直没有成功。
