### ISSUE TITLE
通过腾讯/阿里云函数实现可行吗？

### ISSUE THREAD

**Issue by lance52587** [yjqiang/bili2.0#432]

**Comment by wmhjbj** [comment]
我也很希望能实现云函数部署，而且因为现在银瓜子宝箱取消了，只用完成投币分享风纪委投票等这些功能了，

**Comment by yjqiang** [comment]
可能吧，但我现在没时间尝试这个

**Comment by lance52587** [comment]
> 可能吧，但我现在没时间尝试这个

emmm已经有了，谢谢。https://github.com/happy888888/BiliExp
