### ISSUE TITLE
API sign invalid', 'ts': 1602054202

### ISSUE THREAD

**Issue by scyraxs** [yjqiang/bili2.0#436]
**问题描述**
一星期前或以上发生的

**错误信息**
登录失败,错误信息为:{'code': -3, 'message': 'API sign invalid', 'ts': 1602054202} (用户id:0 名字:123)
主要想用个风纪委员裁判

**必要的系统信息描述等**
python 3.8.6 termux0.101

**最近何时更新的脚本**
最新脚本

**Comment by powermill** [comment]
我也是遇到这个情况，bili应该是修改了登录验证机制

**Comment by dunkirk-4** [comment]
我也出现了同样的问题

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/commit/2c0735bcaf7ae43dc46f72e2247701382d6c5314
