### ISSUE TITLE
安装pip install -r requirements.txt出现错误

### ISSUE THREAD

**Issue by HXF31** [yjqiang/bili2.0#446]
![4BE{4WZ} 3VBTCCI)KKMGY2](https://user-images.githubusercontent.com/41156460/98986259-a11bb300-255f-11eb-9199-814143fde5c2.png)

**Comment by yjqiang** [comment]
https://stackoverflow.com/questions/61365790/error-could-not-build-wheels-for-scipy-which-use-pep-517-and-cannot-be-installe
`pip3 install --upgrade pip`
