### ISSUE TITLE
登录问题api提示没有登录

### ISSUE THREAD

**Issue by dydyiou** [yjqiang/bili2.0#448]
大佬这种情况怎么解决
![}RRM582}L 0V4%)Z_I)EE5B](https://user-images.githubusercontent.com/54195533/99884949-8edefa80-2c6c-11eb-9020-bad961a1f607.png)

**Comment by CberYellowstone** [comment]
同样出现此问题,求解决
@yjqiang

**Comment by jianghansir** [comment]
我也是- -
