### ISSUE TITLE
能否限制直播间数据连接数

### ISSUE THREAD

**Issue by SiH-zh** [yjqiang/bili2.0#458]
脚本现在会启动12个直播间连接数，导致容易403频繁，想问一下在哪修改能限制脚本的直播间监听数量，毕竟现在也没什么礼物能监听了
ctrl.toml里面的强制开两个房间的选项已经关了

![image](https://user-images.githubusercontent.com/61227595/112828622-88e9a200-90c2-11eb-934d-de0dcc00269f.png)

**必要的系统信息描述等**
python3.8.6

**最近何时更新的脚本**
刚刚更新

**最后确认**
- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/3813406c1af7b9e98dc6e560bd78e8d04a69debf/run.py#L129-L134
你把这几行删了就没有监控了

**Comment by SiH-zh** [comment]
好的，感谢
