### ISSUE TITLE
风纪委员正式改版

### ISSUE THREAD

**Issue by Sakura9s** [yjqiang/bili2.0#465]
![image](https://user-images.githubusercontent.com/42808392/134518435-05c95363-3a89-419c-88c7-a5033e99f256.png)
![image](https://user-images.githubusercontent.com/42808392/134518992-6ef134d4-bdd2-4778-8f97-b472a17c1516.png)

**Comment by yjqiang** [comment]
感觉 b 站基本上没有白嫖了。。。
