### ISSUE TITLE
docker相关；多用户使用办法

### ISSUE THREAD

**Issue by chaofan10** [yjqiang/bili2.0#49]

**Comment by chaofan10** [comment]
多用户版本怎么使用docker，在单用户版本那里有两个docker使用链接，哪个是多用户的，求指导

**Comment by yjqiang** [comment]
> 多用户版本怎么使用docker，在单用户版本那里有两个docker使用链接，哪个是多用户的，求指导

docker没做。。。我不太熟悉这东西。单用户这里的docker都是单用户的

**Comment by chaofan10** [comment]
那多用户怎么用的，我找不到使用方法。。。。

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/master/conf/user.toml#L1-L8
这里是user写法，后面是控制。使用办法和单用户一样。如果加入新用户，复制user部分即可。
PS:多用户的user是一个list，https://github.com/toml-lang/toml#array-of-tables

**Comment by wangmanv2** [comment]
emmm...
多用户是的user是一个list是什么意思呢？

```
[[users]]
username = ""
password = ""
[[users]]
username = ""
password = ""
```
还是呢？
```
[[users]]
username = ['username1', 'username2']
password = ['password1', 'password 2']
```
没有学习过 python 望指教

**Comment by yjqiang** [comment]
> emmm...
> 多用户是的user是一个list是什么意思呢？
> 
> ```
> [[users]]
> username = ""
> password = ""
> [[users]]
> username = ""
> password = ""
> ```
> 还是呢？
> 
> ```
> [[users]]
> username = ['username1', 'username2']
> password = ['password1', 'password 2']
> ```
> 没有学习过 python 望指教

`[[users]]
username = "abc1"
password = "************"
access_key = ""
cookie = ""
csrf = ""
uid = ""
refresh_token = ""
[[users]]
username = "abc2"
password = "*********"
access_key = ""
cookie = ""
csrf = ""
uid = ""
refresh_token = ""
`

**Comment by yjqiang** [comment]
其实这与python无关，重点是toml这里

**Comment by wangmanv2** [comment]
您好，我在使用多用戶腳本的時候發現一個問題。

在多用戶下控制檯顯示的控制項目只有id:0的用戶能夠被顯示並處理（即在**控制檯**內的**操作盡對id:0的用戶生效**），而其他用戶不能在控制檯中控制。

這是我的操作方法錯誤造成的麼？

**Comment by yjqiang** [comment]
> 您好，我在使用多用戶腳本的時候發現一個問題。
> 
> 在多用戶下控制檯顯示的控制項目只有id:0的用戶能夠被顯示並處理（即在**控制檯**內的**操作盡對id:0的用戶生效**），而其他用戶不能在控制檯中控制。
> 
> 這是我的操作方法錯誤造成的麼？

不是的，一般来说`指令序号 -u id`为一条比较完整指令，但是如果单独输入`指令序号`那么程序自动补全`-u 0`导致直观上以为只能控制0号用户。你完全可以`1 -u 2`这种，将1号指令用于2号用户。

**Comment by wangmanv2** [comment]
> > 您好，我在使用多用戶腳本的時候發現一個問題。
> > 在多用戶下控制檯顯示的控制項目只有id:0的用戶能夠被顯示並處理（即在**控制檯**內的**操作盡對id:0的用戶生效**），而其他用戶不能在控制檯中控制。
> > 這是我的操作方法錯誤造成的麼？
> 
> 不是的，一般来说`指令序号 -u id`为一条比较完整指令。但是如果单独输入`指令序号`那么程序将自动补全`-u 0`，导致直观上以为只能控制0号用户。你完全可以`1 -u 2`这种，将1号指令用于2号用户。

OK 瞭解了，感謝您的回覆。

**Comment by 526462712** [comment]
请问怎么让不同用户对应不同的控制选项？比如两个号互相给对方投币。用同一个控制文件的话做不到

**Comment by yjqiang** [comment]
> 请问怎么让不同用户对应不同的控制选项？比如两个号互相给对方投币。用同一个控制文件的话做不到

虽然算是预留了这个东西的接口吧。但是还没进行这个实现，而且可能会导致conf配置文件过于复杂，所以暂时不会考虑自定义这里。

**Comment by someash** [comment]
这个问题我好像问过，答案是开新的脚本。。。

**Comment by zsnmwy** [comment]
直接用现在的docker版本就行，只要改好`user.toml`，然后根据readme的方法挂载进去就行。

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/pull/73
