### ISSUE TITLE
实测小黑屋是长期没充钱

### ISSUE THREAD

**Issue by Jutean** [yjqiang/bili2.0#55]

**Comment by Jutean** [comment]
朋友号每天玩个几块钱，活到了现在

**Comment by yjqiang** [comment]
我猜应该是活跃度。而且有人氪金11舰长依旧小黑屋的

**Comment by yjqiang** [comment]
感觉虚无缥缈，这东西玄学，要讨论的话去这里https://github.com/yjqiang/bilibili-live-tools/issues/61
