### ISSUE TITLE
请问一下大航海怎么搞快一点

### ISSUE THREAD

**Issue by Jutean** [yjqiang/bili2.0#58]
需要修改哪些参数？

**Comment by yjqiang** [comment]
啥快一点，说清楚

**Comment by yjqiang** [comment]
参加的话必须要有一个必要延迟3秒，否则会导致不必要的重复进入房间。guard_raffle_handler这里的check里面有个延迟，https://github.com/yjqiang/bili2.0/blob/master/tasks/guard_raffle_handler.py#L37 改了max值，这个就是最大延迟。

**Comment by Jutean** [comment]
好的，谢谢

发自我的 iPhone

在 2019年2月25日，00:30，yjqiang <notifications@github.com<mailto:notifications@github.com>> 写道：


参加的话必须要有一个必要延迟3秒，否则会导致不必要的重复进入房间。guard_raffle_handler这里的check里面有个延迟，https://github.com/yjqiang/bili2.0/blob/master/tasks/guard_raffle_handler.py#L37 改了max值，这个就是最大延迟。
