### ISSUE TITLE
由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。

### ISSUE THREAD

**Issue by Kjcdkcnjji** [yjqiang/bili2.0#6]
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host
120.221.74.132:80 ssl:None [由于系统缓冲区空间不足或队列已满，不能执行套接字上的
操作。] http://120.221.74.132/gift/v3/smalltv/join 14
<class 'concurrent.futures._base.TimeoutError'>  https://account.bilibili.com/ho
me/reward
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host
113.207.83.212:80 ssl:None [由于系统缓冲区空间不足或队列已满，不能执行套接字上的
操作。] http://113.207.83.212/gift/v3/smalltv/join 35
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host
211.159.214.11:80 ssl:None [由于系统缓冲区空间不足或队列已满，不能执行套接字上的
操作。] http://211.159.214.11/gift/v3/smalltv/join 18
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host
120.221.74.132:80 ssl:None [由于系统缓冲区空间不足或队列已满，不能执行套接字上的
操作。] http://120.221.74.132/room/v1/Room/room_entry_action 14
<class 'aiohttp.client_exceptions.ClientConnectorError'> Cannot connect to host
120.92.113.211:80 ssl:None [由于系统缓冲区空间不足或队列已满，不能执行套接字上的
操作。] http://120.92.113.211/gift/v3/smalltv/join 19

**Comment by yjqiang** [comment]
未及时close，fixed now
