### ISSUE TITLE
cmd选定之后，程序暂停运行

### ISSUE THREAD

**Issue by Jutean** [yjqiang/bili2.0#61]
请问是哪里出了问题

**Comment by yjqiang** [comment]
> 请问是哪里出了问题

任务栏选择？什么意思？
反正cmd里面选中之后会不再继续运行。

**Comment by Jutean** [comment]
就是桌面底部的任务栏，程序运行一段时间后，程序在底部任务栏的名字前面就会出现选择二字。

发自我的 iPhone

在 2019年2月27日，15:22，yjqiang <notifications@github.com<mailto:notifications@github.com>> 写道：


请问是哪里出了问题

任务栏选择？什么意思？
反正cmd里面选中之后会不再继续运行。

**Comment by Jutean** [comment]
程序里面还会出现一些别的像是id名称的东西

**Comment by someash** [comment]
(能不能不用邮件回复，上github回复不是更好吗，邮件一长串。。。)

**Comment by Jutean** [comment]
抱歉，刚才忘了，在公司电脑不太方便。

**Comment by yjqiang** [comment]
> 就是桌面底部的任务栏，程序运行一段时间后，程序在底部任务栏的名字前面就会出现选择二字

就是cmd被选中了，这不是bug，至少不是程序问题，windows cmd一向这样。

**Comment by yjqiang** [comment]
> 程序里面还会出现一些别的像是id名称的东西

这是什么？看不懂

**Comment by Jutean** [comment]
好的，谢谢
