### ISSUE TITLE
获取用户投稿的api出现问题（code -400）

### ISSUE THREAD

**Issue by scott90578** [yjqiang/bili2.0#62]
![_20190227171844](https://user-images.githubusercontent.com/24499006/53475674-e100e500-3ab3-11e9-93ff-1aadfb929a36.jpg)

**Comment by yjqiang** [comment]
api出现问题，-400 请求错误，目前不知道是不是一个统一的返回值，类似于1024这样。暂时就是一个小补丁。

**Comment by yjqiang** [comment]
> api出现问题，-400 请求错误，目前不知道是不是一个统一的返回值，类似于1024这样。暂时就是一个小补丁。

api更换不稳定，所以应该不是统一返回值
