### ISSUE TITLE
“清理即将过期礼物”功能好像失效了

### ISSUE THREAD

**Issue by Franinc** [yjqiang/bili2.0#67]
日志里今天下午2点，晚上9点都有一次检测，结果都为：未发现即将过期的礼物
到现在快0点了每日辣条还在包里
clean-expiring-gift = true
set-expiring-time = 0
clean-expiring-gift2room = 23058

**Comment by yjqiang** [comment]
过期时间没有设置set-expiring-time要设置成有效秒数。推荐为43200，即半天。

**Comment by Franinc** [comment]
怪不得，之前看2.0的默认设置相比1.0改成了0还以为程序在这部分有变化就没动😂
