### ISSUE TITLE
关于重复参与的抽奖的问题

### ISSUE THREAD

**Issue by wangmanv2** [yjqiang/bili2.0#70]
当在配置文件列表中输入两个@的人的时候，对于只要求@一个好友的抽奖会对列表里面的每一个账号分别进行@的操作。
如下图：
![Screenshot_2019-03-08-12-57-17-608_com.bilibili.app.in.png](https://i.loli.net/2019/03/08/5c81f82381455.png)
![Screenshot_2019-03-08-12-57-11-970_com.bilibili.app.in.png](https://i.loli.net/2019/03/08/5c81f82387eec.png)

**Comment by yjqiang** [comment]
你user.toml是不是重复了啊……

**Comment by yjqiang** [comment]
一个user.toml里面输入了两个一样的用户

**Comment by wangmanv2** [comment]
没有呀，是不同的用户的。
之前那个toml的问题是因为我在dyn_lottery_friends这个列表里面输入的用户有重复的情况才导致报错。后面修正了以后就没有这种情况了。

**Comment by yjqiang** [comment]
不可能啊……我代码review了一遍，不会出现这种bug吧。你把你整个文件打包，发到 yjqiang1@outlook.com

**Comment by wangmanv2** [comment]
啊啊啊啊啊啊，是我的问题，我在树莓派上吧进程关闭了以后，就直接同步到VPS上运行程序，忘记了我在树莓派上还有一个定时执行的任务。这个问题是两个一起执行的结果。囧
