### ISSUE TITLE
有机率抽奖关注分组失败

### ISSUE THREAD

**Issue by someash** [yjqiang/bili2.0#71]
我这几天下来一共抽奖关注204个，有7个没有成功分组到抽奖关注（在默认分组里面）
![image](https://user-images.githubusercontent.com/32922655/54028138-f5915b80-41de-11e9-85f5-4336b3ec2bf9.png)
这几个除了涂黑的那个都是抽奖关注，但是却分组失误的例子

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bilibili-live-tools/issues/103
