### ISSUE TITLE
is_dyn_raffle: 17042073 code: 0 17042073 {"a_id":100}

### ISSUE THREAD

**Issue by SGlace** [yjqiang/bili2.0#74]
前两天还是好好的，现在莫名其妙的跳出这个

is_dyn_raffle: 17042171 code: 0
17042171 {"a_id":100}
_____________________________________
is_dyn_raffle: 17042172 code: 0
17042172 {}
_____________________________________
is_dyn_raffle: 17042173 code: 0
17042173 {"a_id":100}
_____________________________________
is_dyn_raffle: 17042174 code: 110001
可能不存在或者到达定点
_____________________________________
is_dyn_raffle: 17042175 code: 0
17042175
_____________________________________
is_dyn_raffle: 17042176 code: 0
17042176 {"lbs_cfg":{"address":"美国","distance":0,"location":{"lat":0,"lng":0},"poi":"840","show_distance":"","show_title":"美国","title":"美国","traceType":"country","type":2}}
_____________________________________
is_dyn_raffle: 17042177 code: 0
17042177 {}
_____________________________________
is_dyn_raffle: 17042178 code: 0
17042178 {}

**Comment by SGlace** [comment]
![QQ截图20190309083953](https://user-images.githubusercontent.com/22759345/54063399-17bec400-4247-11e9-8ecd-fbfea89e28d4.png)

**Comment by yjqiang** [comment]
动态

**Comment by yjqiang** [comment]
开关在这里，https://github.com/yjqiang/bili2.0#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
