### ISSUE TITLE
希望动态抽奖中奖的话可以不取关和删除动态

### ISSUE THREAD

**Issue by huajilong** [yjqiang/bili2.0#75]
希望动态抽奖中奖的话可以不取关和删除动态

**Comment by yjqiang** [comment]
目前是拖后2小时，我想想有什么合适的处理办法。

**Comment by yjqiang** [comment]
中奖你是想不再处理，由你自己负责之后的所有工作么？即删除/取关等。

**Comment by huajilong** [comment]
对的

**Comment by huajilong** [comment]
或者可以弄一个中奖分组然后移进去也是一种方法吧

**Comment by yjqiang** [comment]
> 或者可以弄一个中奖分组然后移进去也是一种方法吧

这个就没有必要了吧

**Comment by huajilong** [comment]
emm也是，毕竟中奖也不是多

**Comment by yjqiang** [comment]
这里逻辑有个矛盾点，我还在考虑。如果中奖后，不删除数据库，那么后面`set_result`会有问题；否则如果该up主还有一个抽奖，那么可能仍然取关（但是不会删除了）。

**Comment by yjqiang** [comment]
初步考虑的办法是另开一个表（luckydog）存储当前中奖用户，这样也方便查询。表里存贮了`joined所有列+following_uid`，这样的话unfollow之前再加一个判断（luckydog是否正在follow）就可以规避掉误取关。
@huajilong

**Comment by huajilong** [comment]
如果能做出来的话，应该可以在控制台那里加一个查询多账号是否有中奖吧。（又给大佬挖了个坑）

**Comment by someash** [comment]
不止，甚至还可以控制台看即将开奖的抽奖时间之类的。。。坑是无穷无尽的。。

**Comment by yjqiang** [comment]
DONE
