### ISSUE TITLE
修改配置文件名称为sample

### ISSUE THREAD

**Issue by DkWyatt** [yjqiang/bili2.0#76]
建议把user.toml和ctrl.toml添加.sample后缀，并且在.gitignore里把这两个文件添加进去
用户使用的时候自己复制一份照改就行了
这样每次更新就不用重置本地修改了

**Comment by someash** [comment]
下下来一个新的，把user和ctrl删掉，拿你编辑好的覆盖进去，（除非对user和ctrl的修改）不就好了，为什么要重置本地修改？？？

这样说还不如弄一个定时检查版本更新的。。。。然后自动更新。

**Comment by yjqiang** [comment]
> 建议把user.toml和ctrl.toml添加.sample后缀，并且在.gitignore里把这两个文件添加进去
> 用户使用的时候自己复制一份照改就行了
> 这样每次更新就不用重置本地修改了

是个不错办法，但是我似乎没找到广泛应用的例子，有其他repos这么用的么？

**Comment by DkWyatt** [comment]
https://github.com/abbeyokgo/PyOne
这东西作者更新的很频繁，但是升级也很简单，直接`git pull`再重启服务就好了
只要不牵扯新功能，旧的配置一般都没问题，最好是在commit里备注config新添加的东西

**Comment by yjqiang** [comment]
https://github.com/containous/traefik/blob/master/traefik.sample.toml

**Comment by yjqiang** [comment]
非常感谢
