### ISSUE TITLE
把动态开关从 run.py 加到 /conf/ctrl.sample.toml

### ISSUE THREAD

**Issue by zsnmwy** [yjqiang/bili2.0#77]
应该尽量避免配置的开关放在需要经常更改文件里面。

如果主项目的`run.py`发生修改，而用户这边恰好这边`run.py`不需要这个动态抽奖。譬如我。

当使用docker镜像的时候，一开始就进行`git pull`的时候，`git`就会报错。

https://github.com/yjqiang/bili2.0/blob/52f8bc5d35b4f08422e4cc52f11deafc88fc02d9/Dockerfile#L17-L19

**Comment by a253208088** [comment]
还有节奏风暴

**Comment by yjqiang** [comment]
暂时不会这么做，目前动态和实物均缩减成了一行，注释即可。
节奏风暴暂时没办法。
