### ISSUE TITLE
main启动问题

### ISSUE THREAD

**Issue by yjqiang** [yjqiang/bili2.0#80]
目前main函数启动这里过于混乱，需要一个比较好点的归类的启动顺序。
1. aiohttp session是不能单独init的。。。需要放在coroutine里面。
1. https://stackoverflow.com/questions/26908854/what-is-the-best-way-of-reading-configuration-parameters-from-configuration-file mmp conf的获取与分发问题也好难解决，单例模式过于笨比。

**Comment by chy89224** [comment]
请问在命令窗口会时不时出现各个城市的名字，这是何用？还经常提示‘可能不存在或者到达定点’
is_dyn_raffle: 17294791 code: 0
17294791 {"lbs_cfg":"{\"poi\":\"156420100\",\"show_title\":\"武汉市\",\"type\":1
,\"title\":\"武汉市\",\"location\":{\"lat\":30.556601000000001,\"lng\":114.19899
700000001},\"address\":\"武汉市\",\"distance\":0}"}
_____________________________________
is_dyn_raffle: 17294792 code: 0
17294792 {"a_id":100}
_____________________________________
is_dyn_raffle: 17294793 code: 0
17294793 {"emoji_type":1}
_____________________________________
is_dyn_raffle: 17294794 code: 0
17294794 {"a_id":100}
_____________________________________
is_dyn_raffle: 17294795 code: 110001
可能不存在或者到达定点

**Comment by yjqiang** [comment]
@asd976385560 以后问问题请另开issue，https://github.com/yjqiang/bili2.0/issues/74

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/commit/9662478a0757c90e4bac016514a88a76364e76e2
先这样吧
