### ISSUE TITLE
winerror 10038

### ISSUE THREAD

**Issue by Kjcdkcnjji** [yjqiang/bili2.0#85]

**Comment by yjqiang** [comment]
![photo_2019-03-14_17-00-26](https://user-images.githubusercontent.com/8900942/54344007-09bfd780-467b-11e9-96f3-bdc111e36301.jpg)
https://bugs.python.org/issue33350

**Comment by chy89224** [comment]
请问我界面上显示用户id为0，没事吧

**Comment by yjqiang** [comment]
@chy89224 自己另开issue好吧。。。

**Comment by yjqiang** [comment]
补充：经常多台机器同时发生这个问题

**Comment by yjqiang** [comment]
https://github.com/kyuupichan/aiorpcX/issues/8

**Comment by yjqiang** [comment]
confirmed

**Comment by pjy612** [comment]
弄个自启吧，也出现这个问题了。囧
run.py

#顶部加上
import os

#底部改成
try:
    if other_tasks:
        loop.run_until_complete(asyncio.wait(tasks+other_tasks))
    loop.run_forever()
    if console_thread is not None:
        console_thread.join()
except:
    os._exit(0)
looprun.bat

@echo off
:loop
python run.py
goto loop
pause
然后用looprun.bat 启动。
出了错就把自己干掉然后重启 = =。笨办法。

**Comment by yjqiang** [comment]
python3.8正在折腾eventloop底层 不知道能不能修好

**Comment by yjqiang** [comment]
似乎的确修复了，正在等待确认

**Comment by yjqiang** [comment]
![IMG_1077](https://user-images.githubusercontent.com/8900942/72682536-069e3f00-3b09-11ea-82f3-ac422f5759e0.PNG)
2020.1.19确认一次

**Comment by yjqiang** [comment]
![photo_2020-01-24_20-50-37](https://user-images.githubusercontent.com/8900942/73074402-87d44800-3ef4-11ea-884c-e5f3fd6e1dfb.jpg)
各位过年好😷
