### ISSUE TITLE
有关如何关闭动态抽奖的疑问

### ISSUE THREAD

**Issue by chy89224** [yjqiang/bili2.0#86]
请问关闭动态抽奖是这样吗
other_tasks = [
    raffle_handler.run(),
    # SubstanceRaffleMonitor().run()
    #dyn_raffle_moitor.run(),
    #dyn_raffle_moitor.check_result()
]

**Comment by yjqiang** [comment]
对  之后我会弄的简略一点

**Comment by chy89224** [comment]
那请问界面上显示我的用户id是0,没事吧

**Comment by yjqiang** [comment]
没事
