### ISSUE TITLE
动态删除api意外返回

### ISSUE THREAD

**Issue by yawwwwwn** [yjqiang/bili2.0#87]
`http://api.vc.bilibili.com/dynamic_repost/v1/dynamic_repost/rm_rp_dyn`
`{'code': -6, 'msg': '', 'message': '', 'data': {}}`
`{'code': -22, 'msg': 'error', 'message': 'error', 'data': {}}`

批量删除动态（非本项目）时，大约3/50出现-6的code，1/50出现-22。
根据dynamic_id打开网页均是未删除。其中-22的那条转发的原动态被删。
批量删除为单ip，单账号，每条间隔0.3s。

**Comment by yjqiang** [comment]
{'code': -6, 'msg': '', 'message': '', 'data': {}}表示登出，当你把cookie设置空的时候可以无限复现。

**Comment by yawwwwwn** [comment]
本次批量删除动态未出现 'code': -6，约 2/400 出现 'code': -22。重试一次均顺利删除。

**Comment by yjqiang** [comment]
#103
