### ISSUE TITLE
动态抽奖是默认开启还是关闭，如何开启或关闭

### ISSUE THREAD

**Issue by yushengleiming** [yjqiang/bili2.0#89]

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
https://github.com/yjqiang/bili2.0/blob/master/run.py#L94
默认关闭。

**Comment by yushengleiming** [comment]
是删除一整行还是 删除should_join_immediately=True这个

**Comment by yjqiang** [comment]
> 是删除一整行还是 删除should_join_immediately=True这个

。。。。删除一整行
