### ISSUE TITLE
小电视抽奖失败'data': 'bad token'

### ISSUE THREAD

**Issue by wwh1004** [yjqiang/bili2.0#91]
更新到了最新一次commit，还是这样

# 小电视抽奖状态: invalid request(用户id:0 名字:)
{'code': 65530, 'msg': 'invalid request', 'message': 'invalid request', 'data': 'bad token'}

**Comment by yjqiang** [comment]
> 更新到了最新一次commit，还是这样
> 
> # 小电视抽奖状态: invalid request(用户id:0 名字:)
> {'code': 65530, 'msg': 'invalid request', 'message': 'invalid request', 'data': 'bad token'}

我没有这个错误……奇怪奇怪 明早我试试怎么解决吧……

**Comment by yjqiang** [comment]
如果你能懂py的话，可以https://github.com/yjqiang/bili2.0/blob/master/reqs/tv_raffle_handler.py#L20  这里把token由原来的空变成有效字符串。然后看看。不会的话，你可以qq或者yjqiang1@icloud.com 私信我你的整个项目文件夹。我自己处理。

**Comment by yjqiang** [comment]
目前有个奇怪的东西，https://github.com/yjqiang/bili2.0/commit/69b518d4aba34120e94747b88966db9d70706024 ，这个之前就是有人报这个错，空token不行。但是我自己账号可以……token瞎写都行……

**Comment by wwh1004** [comment]
很奇怪，今天晚上突然好了，以后还出问题再看看吧，脚本我是挂在了树莓派上24小时开着。

**Comment by yjqiang** [comment]
嗯嗯

**Comment by wwh1004** [comment]
有没有可以开启记录日志的地方，刚才看了下配置文件和主目录，没发现和日志有关的
感觉没有日志文件完全不知道什么时候出了什么错

**Comment by yjqiang** [comment]
> 有没有可以开启记录日志的地方，刚才看了下配置文件和主目录，没发现和日志有关的
> 感觉没有日志文件完全不知道什么时候出了什么错

python对asyncio这里似乎并不怎么支持日志，再加上我的使用办法，导致几乎没法像正常非协程那样卡死然后输出就行，这货挂了某个地方经常还能接着其他地方跑。所以debug不太容易。

**Comment by yjqiang** [comment]
目前可能的办法就是对一些api response约束，防止意外response返回。https://github.com/yjqiang/bili2.0/commit/c1e0c205b2c68ace2f25c1f23ba75d52f3f0035e

**Comment by wwh1004** [comment]
要不你加下我qq 2365103939，又出问题了...
![Snipaste_2019-03-29_22-14-22](https://user-images.githubusercontent.com/27536652/55238714-26a9fc80-5270-11e9-9056-c689d28fb9d0.png)

**Comment by Love4Taylor** [comment]
加上 `user.dict_bili['csrf']` 后正常了

**Comment by jjnnnh** [comment]
还有`pc_heartbeat`一样问题，发现另一个号电脑双端未完成

**Comment by yjqiang** [comment]
b站似乎加强了token检测，heartbeart tv这里都是token，还有那个medal

**Comment by yjqiang** [comment]
> 还有`pc_heartbeat`一样问题，发现另一个号电脑双端未完成

你监控一下这个问题，尽量贴出信息。心跳这里，包其实有俩，分别是pc和app，你看看是不是都这样还是只有pc

**Comment by jjnnnh** [comment]
> > 还有`pc_heartbeat`一样问题，发现另一个号电脑双端未完成
> 
> 你监控一下这个问题，尽量贴出信息。心跳这里，包其实有俩，分别是pc和app，你看看是不是都这样还是只有pc

我已经把改了这块在试
`    async def pc_heartbeat(user):
        url = f'{API_LIVE}/User/userOnlineHeart'
        payload = {'csrf_token': user.dict_bili['csrf']}
        json_rsp = await user.bililive_session.request_json('POST', url, data=payload, headers=user.dict_bili['pcheaders'])
        return json_rsp`

**Comment by jjnnnh** [comment]
> > 还有`pc_heartbeat`一样问题，发现另一个号电脑双端未完成
> 
> 你监控一下这个问题，尽量贴出信息。心跳这里，包其实有俩，分别是pc和app，你看看是不是都这样还是只有pc

我已经改了在试
    async def pc_heartbeat(user):
        url = f'{API_LIVE}/User/userOnlineHeart'
        payload = {'csrf_token': user.dict_bili['csrf']}
        json_rsp = await user.bililive_session.request_json('POST', url, data=payload, headers=user.dict_bili['pcheaders'])
        return json_rsp

**Comment by jjnnnh** [comment]
> > > 还有`pc_heartbeat`一样问题，发现另一个号电脑双端未完成
> > 
> > 
> > 你监控一下这个问题，尽量贴出信息。心跳这里，包其实有俩，分别是PC和应用程序，你看看是不是都这样还是只有PC
> 
> 只有pc，我已经改了在试
> ` async def pc_heartbeat(user):`
> ` url = f'{API_LIVE}/User/userOnlineHeart'`
> ` payload = {'csrf_token': user.dict_bili['csrf']}`
> ` json_rsp = await user.bililive_session.request_json('POST', url, data=payload, headers=user.dict_bili['pcheaders'])`
> ` return json_rsp`

**Comment by jjnnnh** [comment]
> > > 还有`pc_heartbeat`一样问题，发现另一个号电脑双端未完成
> > 
> > 
> > 你监控一下这个问题，尽量贴出信息。心跳这里，包其实有俩，分别是pc和app，你看看是不是都这样还是只有pc
> 
> 我已经改了在试
> ` async def pc_heartbeat(user):`
> ` url = f'{API_LIVE}/User/userOnlineHeart'`
> ` payload = {'csrf_token': user.dict_bili['csrf']}`
> ` json_rsp = await user.bililive_session.request_json('POST', url, data=payload, headers=user.dict_bili['pcheaders'])`
> ` return json_rsp`

OK，上截图，PC心跳信息临时调到user.warn
[http://jjnnnh.free.idcfengye.com/test/#91-0.png](url)
[http://jjnnnh.free.idcfengye.com/test/#91-1.png](url)

**Comment by jjnnnh** [comment]
403繁忙那个，我有调用大航海列表接口

**Comment by yjqiang** [comment]
抓包的话：
pc_heartbeat
csrf_token: ba22bd7a45db67212a7e0c5b12016cea
csrf: ba22bd7a45db67212a7e0c5b12016cea
visit_id:
