### ISSUE TITLE
监听不到大航海信息

### ISSUE THREAD

**Issue by AncientFires** [yjqiang/bili2.0#93]
弹幕信息发到了这个房间： 930487 。

之前一直用的好好的，今天进去想改下配置的时候发现监听不到大航海信息了。
然后试着把默认弹幕打印的房间号也设置成这个，发现弹幕成功发出，也能正常打印。
但就是没有之前的 “0号弹幕监控检测到XX的大航海” 消息了

**Comment by yjqiang** [comment]
如果你仔细看b站的弹幕，你会发现b站给你加了一个喵。。。我佛了

**Comment by AncientFires** [comment]
在 /danmu/monitor_danmu_raffle.py 第133行后加入
msg = msg.replace('~喵','')
