### ISSUE TITLE
我同时挂三个号，但为什么三个号各自抽到的辣条数量会有所不一样。

### ISSUE THREAD

**Issue by yushengleiming** [yjqiang/bili2.0#96]

**Comment by yjqiang** [comment]
抽奖前后（从推送到参与）有人为延迟，可能存在细微差距。如果在可接受范围内，不是bug。

**Comment by yushengleiming** [comment]
我的三个号，今日目前最大相差有120多。 不知道是不是误差范围

**Comment by yjqiang** [comment]
> 我的三个号，今日目前最大相差有120多。 不知道是不是误差范围

你看看各个用户具体参与情况吧……

**Comment by yushengleiming** [comment]
1指令好像只能看id：0的 怎么看其他用户呢

**Comment by yjqiang** [comment]
> 1指令好像只能看id：0的 怎么看其他用户呢

1 -u id (eg: 1 -u 0会展示第0个用户，id表示配置文件内的编号，不是uid)

**Comment by yushengleiming** [comment]
一不小心重置了脚本，不知道有没有历史的抽奖记录可以查询。

**Comment by yjqiang** [comment]
没有，你什么时候更新的脚本啊？

**Comment by yushengleiming** [comment]
昨天晚上更新的，然后今天傍晚回家后看的

**Comment by yushengleiming** [comment]
前一段时间我还做过一个测试，用两种不同脚本，三个号，其中一个号挂两个脚本。三者之间，挂两个脚本的号的确辣条要多上几百。是不是有调整过抽奖概率

**Comment by yjqiang** [comment]
> 前一段时间我还做过一个测试，用两种不同脚本，三个号，其中一个号挂两个脚本。三者之间，挂两个脚本的号的确辣条要多上几百。是不是有调整过抽奖概率

没有调过，理论上不会少这么多。

**Comment by yushengleiming** [comment]
> > 前一段时间我还做过一个测试，用两种不同脚本，三个号，其中一个号挂两个脚本。三者之间，挂两个脚本的号的确辣条要多上几百。是不是有调整过抽奖概率
> 
> 没有调过，理论上不会少这么多。

但事实上的确少了。我有个朋友找的淘宝店好像还要更多，比我每天多了快500不知道是怎么来的。

**Comment by yjqiang** [comment]
你只挂一个号比对一下。这个问题可能有几种原因：用户多了可能过期；b站api存在已知问题（已经确认过），有时结果不返回，无法统计；其他原因。

**Comment by yushengleiming** [comment]
那我开俩个脚本，一个挂一个号，一个挂两个号。明天再对比一下。

**Comment by yushengleiming** [comment]
不知道有没有可能是硬件问题，以前用服务器的时候还蛮正常的，最近换的树莓派，开始有这些问题了。

**Comment by yjqiang** [comment]
> 不知道有没有可能是硬件问题，以前用服务器的时候还蛮正常的，最近换的树莓派，开始有这些问题了。

建议试着换换环境，如果网络过差，也会这样。

**Comment by yushengleiming** [comment]
本次推送抽奖统计：                              本次推送抽奖统计：        
 211  X 摩天大楼                                    212  X 摩天大楼        
82.00 X 王冠小电视                               82.00 X 王冠小电视                                             
89.00 X 小电视飞船                               19   X 舰长
17.00 X 任意门                                      89.00 X 小电视飞船
8.00  X 总督                                           17.00 X 任意门
 12   X 舰长                                            8.00  X 总督
  1   X 提督                                            1.00  X 二十倍节奏风暴
1.00  X 二十倍节奏风暴

本次参与抽奖统计：                              本次参与抽奖统计：
 398  X 小电视(合计)                              398  X 小电视(合计)
 19   X 大航海(合计)                              25   X 大航海(合计)

本次抽奖结果统计：                             本次抽奖结果统计：
1282  X 辣条                                         1140  X 辣条
 
抽奖数量是几乎一样，但辣条数量却不一样，不知道是不是在误差内

**Comment by yjqiang** [comment]
最新版大航海我记得应该有亲密度统计啊？那个呢？

**Comment by yushengleiming** [comment]
> 最新版大航海我记得应该有亲密度统计啊？那个呢？

我有两个号没有带勋章所以好像没有亲密度统计，一个好像加了400+的亲密度

**Comment by yushengleiming** [comment]
> 最新版大航海我记得应该有亲密度统计啊？那个呢？
我有两个号没有带勋章所以好像没有亲密度统计，一个好像加了200+的亲密度

**Comment by yushengleiming** [comment]
我有两个号没有带勋章所以好像没有亲密度统计，一个好像加了200+的亲密度

**Comment by yjqiang** [comment]
误差绝对不对  我之后处理一下试试看

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/commit/9bed4655cbd990fe4b210c77b72b2b44f427c58c
@yushengleiming 你试试看

**Comment by yushengleiming** [comment]
我直接下载了个新的脚本 然后运行出现了下面的错误
Traceback (most recent call last):
  File "run.py", line 74, in <module>
    printer_danmu = loop.run_until_complete(get_printer_danmu())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "run.py", line 61, in get_printer_danmu
    yjmonitor_danmu_roomid = other_control['yjmonitor_danmu_roomid']
KeyError: 'yjmonitor_danmu_roomid'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x759ded70>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x75a01960>, 348043.003361098)]']

**Comment by yjqiang** [comment]
@yushengleiming 自己修改ctrl.toml，我修改了一些细节，参见sample

**Comment by yushengleiming** [comment]
谢谢大佬，我已经挂好，明天再看看会不会有较大的误差。

**Comment by yushengleiming** [comment]
处理后，误差缩小到5个辣条了。感谢大佬的修复

**Comment by yjqiang** [comment]
这个东西误差出在notice时间这里，之前我是预估的，看来好像不应该。。。你再观察一两天，确认之后，告诉我，这个issue就可以关闭了。

**Comment by yjqiang** [comment]
@yushengleiming 确认了么？
