### ISSUE TITLE
完全萌新，不懂就问

### ISSUE THREAD

**Issue by 526462712** [yjqiang/bili2.0#99]
2月28日版本能正常运行，新版本不行，请问是为什么呢？要怎么解决呢？谢谢
![bili2](https://user-images.githubusercontent.com/34618949/55525145-7a7a7280-56c2-11e9-8f9c-1e366aa5a17e.png)

**Comment by yjqiang** [comment]
#68
请务必提前搜索错误情况，这个报错没说一百遍至少十几个人报了。
